<?php
$template = new template();
?>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <?=$template->page_header('Tabela de tipos de email');?>
    <?php
        //page-header
        $btnAdiconar = $template->btnAdicionarRegistro(URL.'configuracoes/tabelas/tipo_email/cadastrar');
        echo $template->actions_buttons($btnAdiconar);
    ?>
    <div class="middle-content">
        <?php
        $thead = '  <tr>
                        <th>Nome</th>
                        <th width="100">Status (Ativo/Inativo)</th>
                        <th width="180">Ações</th>
                    </tr>';
        $tfoot = '  <tr>
                        <th>Nome</th>
                        <th>Status (Ativo/Inativo)</th>
                        <th>Ações</th>
                    </tr>';	 
        if($tipoEmail != false):
            $tbody = '';
            foreach ($tipoEmail as $tipoEmail):
            	$status = ($tipoEmail['status_tipo_email'] == 'Ativo') ? true : false;

                $tbody .='  <tr id="'.$tipoEmail['id_tipo_email'].'">
                                <td>'.$tipoEmail['nome_tipo_email'].'</td>
                                <td>
                                    '.$template->checkboxStatus($tipoEmail['id_tipo_email'],'status',$status).'
                                </td>
                                <td>
                                    '.$template->btnEditarRegistro(URL.'configuracoes/tabelas/tipo_email/editar/'.$tipoEmail['id_tipo_email']).
                                    $template->btnExcluirRegistro('javascript:void(0)',$tipoEmail['id_tipo_email']).
                                '</td>
                            </tr>';
            endforeach;
            echo $template->tabela($thead, $tfoot, $tbody);
        else:
            echo '<h2>Não há registros cadastrados</h2>';
        endif;

        
        ?>
    </div>

</div>
<script>
$(document).ready(function() {
    var table = $('.dataTable').DataTable({
    	order: []
    });
    table.$('.btn_excluir').on('click',function(){
        var id = $(this).attr('id');
        var status = 'Excluído';

        $("#dialogResult").html('Deseja mesmo excluir?');
		$("#dialogResult").dialog({
			autoOpen: true,
			buttons: [
				{
					text: "Ok",
					click: function() {
						$( this ).dialog( "close" );

				    	$.post(url+'configuracoes/tabelas/tipo_email/excluir',{id:id,status:status},function(data){
							if(data == true)
								$('tr#'+id).hide();
						});
					}
				},
				{
					text: "Cancelar",
					click: function() {
						$( this ).dialog( "close" );
					}
				}
			]
		});



		
        
    });

    table.$('input[name=status]').on('change',function(){
    	var id = $(this).attr('id')
    	var status = 'Inativo';
		if($(this).is(':checked'))
			status = 'Ativo';

		$.post(url+'configuracoes/tabelas/tipo_email/atualizarStatus',{id:id,status:status},function(data){

		})

    });


});
</script>