<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <div class="page-header">
        <h1>Gerenciador eclesiastico</h1>
    </div>

   

   	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-6">
        <header class="box_header">
            <h2>Igreja</h2>
        </header>
        <div class="well well-sm"><?=$igreja['nome_igreja']?> - <?=$igreja['rua_igreja']?>, <?=$igreja['numero_igreja']?> <?=$igreja['complemento_igreja']?>. <?=$igreja['bairro_igreja']?> - <?=$igreja['cidade_igreja']?> - <?=$igreja['estado_igreja']?></div>
        
    </div>


    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-6">
        <header class="box_header">
            <h2>Estatísticas</h2>
        </header>

        <div class="content">
			<!--estatisticas-->
        </div>
    </div>
</div>
<script type="text/javascript" src="<?=URL?>js/jquery.validate.js"></script>
<script type="text/javascript" src="<?=URL?>js/jquery.maskedinput.min.js"></script>
<script type="text/javascript">
	$(function(){
		//telefone
        $('.addTel').on('click',function(){
            var error = 0;
            var campTel = $('#defaultCampos #defaultTel').clone().removeAttr('id').removeAttr('style');
            campTel.find('input').val('');
            $(this).before(campTel);
        });
        
        $(document).on('click','.delCel',function(){
            $(this).parent().parent().remove();
        });


        $('input[name=data_fundacao]').datepicker({ dateFormat: 'dd/mm/yy' });
		$('input[name=cep]').wvmask('cep')
		$('input[name=numero]').wvmask('numero')
		$('input[name=cnpj]').mask('999.999.999-99');
		//mascara para telefones de 8 e 9 dígitos
        var maskBehavior = function (val) {
            return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
        },
        options = {onKeyPress: function(val, e, field, options) {
            field.mask(maskBehavior.apply({}, arguments), options);
            }
        };
        $('input[name=telefone]').mask(maskBehavior, options);

        $('#form_cadastro_igreja').validaCep();


        var telefones = Object();
        $('#form_cadastro_igreja').submit(function(){
	        var parameters = Object();
	            parameters['telefones'] = telefones;
	        $('#form_cadastro_igreja').uploadForm({
	            'parameters': parameters
	        });
	        return false;
	    });

	});

</script>

