<?php
/**
*@author Wellington cezar (programador jr) - wellington.infodahora@gmail.com
*/
$template = new template();
?>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" id="rol_membros">
    <?=$template->page_header('Escola Bíblica Dominical <small>Cadastrar alunos</small>');?>
    <?php
        //page-header
        $btnVoltar = $template->btnVoltar(URL.'ebd/classes/');
        echo $template->actions_buttons($btnVoltar);
    ?>

    <div class="panel generalErrors panel-danger" style="text-align:left; display:none;  background-color: #f2dede;">
        <h4 class="panel-heading">Ocorreu(ram) o(s) seguinte(s) erro(s):</h4>
        <div class="alert alert-danger" role="alert">

        </div>
    </div>

    <form id="form_cadastro_aluno" action="<?=URL?>ebd/classes/alunos/inserir" method="POST">
        <!--DADOS FAMILIARES-->
        <div >
            <header class="box_header">
                <h2>Cadastro de alunos para a classe: <strong><?=$classe['nome_classe_ebd']?></strong></h2>
            </header>

            <div class="content">
                <div class="form-group input-group">
                    <span class="input-group-addon" id="basic-addon1">Classe</span>
                    <input type="text" class="form-control" placeholder="Classe" name="classe" value="<?=$classe['nome_classe_ebd']?>" disabled>
                    <input type="hidden" class="form-control" placeholder="Classe" name="id_classe" value="<?=$classe['id_classe_ebd']?>">
                </div>
                <div class="form-group input-group">
                    <span class="input-group-addon">Membros:</span>
                    <select name="membro" id="membro" class="form-control">
                        <option selected="selected" disabled="disabled" value="">Membros:</option>
                        <?php if($membros != false):?>
                        <?php foreach ($membros as $membro):?>
                        <?php $fotoM = ($membro['foto_membro'] != '') ? URL.'uploads/membros/p/'.$membro['foto_membro'] : URL.'img/imagens/perfil-icone.png'?>
                        <option value="<?=$membro['id_membro']?>" data-class="avatar" data-style="background-image: url('<?=$fotoM?>');  background-size: 100%;  width: 22px;  height: 22px;"><?=$membro['nome_membro']?> <?=$membro['sobrenome_membro']?></option>
                        <?php endforeach;?>
                        <?php endif;?>
                    </select>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <button type="submit" class="btn btn-success btn_salvar pull-right"><span class="glyphicon glyphicon-ok"></span> Cadastrar</button>
            </div>
        </div>
    </form>
</div>

<script type="text/javascript" src="<?=URL?>js/jquery.validate.js"></script>
<script type="text/javascript" src="<?=URL?>js/jquery.maskedinput.min.js"></script>



<script type="text/javascript">
    $(function(){
        $('input[name=faixa_etaria_min]').wvmask('numero');
        $('input[name=faixa_etaria_max]').wvmask('numero');

        $('input[name=faixa_etaria_min]').change(function(event) {
            $('input[name=faixa_etaria_max]').attr('min',$(this).val())
        });


        $('#form_cadastro_aluno').submit(function(){
            $('#form_cadastro_aluno').uploadForm({

            });
            return false;
        });

        /************************************/
        //campos select
        $.widget( "custom.iconselectmenu", $.ui.selectmenu, {
          _renderItem: function( ul, item ) {
            var li = $( "<li>", { text: item.label } );
     
            if ( item.disabled ) {
              li.addClass( "ui-state-disabled" );
            }
     
            $( "<span>", {
              style: item.element.attr( "data-style" ),
              "class": "ui-icon " + item.element.attr( "data-class" )
            })
              .appendTo( li );
            return li.appendTo( ul );
          }
        });

        $( "#membro" )
        .iconselectmenu()
        .iconselectmenu( "menuWidget")
        .addClass( "ui-menu-icons avatar" );
        /************************************/
    });

</script>

