<?php require_once('head.phtml');?>
<body>
    <!--[if lt IE 7]>
        <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
    <div id="wrap">
    <?php require_once('header.phtml');?>
        <section id="container"><!--class="col-xs-12 col-sm-12 col-md-12 col-lg-12"-->
            <?php require_once('menu.phtml');?>
            <section id="container_center" class="col-xs-12 col-sm-11 col-md-11 col-lg-11">

               
                    
            
