<?php
$titulo = isset($titulo) && $titulo != ''  ? trim($titulo).' - ' : '';
$keywords = isset($keywords) ? trim($keywords).' - ' : '';
$description = isset($description) ? trim($description).' - ' : '';
?>
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="pt-br"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <!--[if lt IE 9]>
            <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <![endif]-->
        <title><?=$titulo?>Gerenciador Eclesiastico</title>
        <meta name="keywords" content="<?=$keywords?>">
        <meta name="description" content="<?=$description?>">
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" >
        <!--<link rel="stylesheet" href="css/bootstrap-theme.min.css">-->
        <link rel="stylesheet" type="text/css" href="<?=URL?>css/bootstrap.min.css">
        <link rel="stylesheet" href="<?=URL?>css/bootstrap-submenu.min.css">
        <link rel="stylesheet" type="text/css" href="<?=URL?>css/normalize.css">
        <link rel="stylesheet" type="text/css" href="<?=URL?>css/animate.css">
        <link rel="stylesheet" type="text/css" href="<?=URL?>css/jquery-ui.css">
        <link rel="stylesheet" type="text/css" href="<?=URL?>css/main.css">
        <link rel="stylesheet" type="text/css" href="<?=URL?>css/large_desktops.css">
        <link rel="stylesheet" type="text/css" href="<?=URL?>css/desktops.css">
        <link rel="stylesheet" type="text/css" href="<?=URL?>css/tablets.css">
        <link rel="stylesheet" type="text/css" href="<?=URL?>css/extra_small_devices.css">
        
        

        <meta name="robots" content="noindex, nofollow">
        <!--[if IE]>
            <link rel="shortcut icon" href="img/favicon.ico">
        <![endif]-->
        <link rel="icon" href="<?=URL?>img/favicon.png">
        <!-- iPad iOS7+ com Retina Display -->
        <link rel="apple-touch-icon" sizes="152x152" href="apple-touch-icon-152x152.png">
        <!-- iPad iOS7- com Retina Display -->
        <link rel="apple-touch-icon" sizes="144x144" href="apple-touch-icon-144x144.png">
        <!-- iPhone iOS7+ com Retina Display -->
        <link rel="apple-touch-icon" sizes="120x120" href="apple-touch-icon-120x120.png">
        <!-- iPhone iOS7- com Retina Display -->
        <link rel="apple-touch-icon" sizes="114x114" href="apple-touch-icon-114x114.png">
        <!-- iPad iOS7+ sem retina display e iPad Mini-->
        <link rel="apple-touch-icon" sizes="76x76" href="apple-touch-icon-76x76.png">
        <!-- iPad iOS7- sem retina display  -->
        <link rel="apple-touch-icon" sizes="72x72" href="apple-touch-icon-72x72.png">
        <!-- iPhone iOS7-, iPod Touch e Android 2.2+  -->
        <link rel="apple-touch-icon" href="apple-touch-icon.png">

        <script src="<?=URL?>js/vendor/modernizr-2.6.2-respond-1.1.0.min.js"></script>
        <!--[if lt IE 9]><script src="js/selectivizr-min.js"></script><![endif]-->

        <!--<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>-->
        <script type="text/javascript" src="<?=URL?>js/jquery-1.11.2.min.js"></script>
        <script type="text/javascript" src="<?=URL?>js/jquery.form.js"></script>
        <script type="text/javascript" src="<?=URL?>js/vendor/bootstrap.min.js"></script>
        <script src="<?=URL?>js/vendor/bootstrap-submenu.min.js"></script>
        <script type="text/javascript" src="<?=URL?>js/plugins.js"></script>
        <script type="text/javascript" src="<?=URL?>js/jquery-ui.js"></script>
        <script type="text/javascript" src="<?=URL?>js/main.js"></script>
        <script type="text/javascript" src="<?=URL?>js/hoverIntent.js"></script>

        <script type="text/javascript" src="<?=URL?>js/jquery.dataTables.min.js"></script>
        <script type="text/javascript" src="<?=URL?>js/dataTables.bootstrap.js"></script>
        <script type="text/javascript" src="<?=URL?>js/jquery.submitForm.js"></script>
        <script type="text/javascript" src="<?=URL?>js/cep.js"></script>
        
        <link rel="stylesheet" type="text/css" href="<?=URL?>css/jquery.dataTables.min.css">
        <link rel="stylesheet" type="text/css" href="<?=URL?>css/dataTables.bootstrap.css">
       
        <link rel="stylesheet" type="text/css" href="<?=URL?>css/component.css">
        
        <script src="<?=URL?>js/jquery.dlmenu.js"></script>
        <link rel="stylesheet" type="text/css" href="<?=URL?>css/table.css">

        <!--crop-->
        <link rel="stylesheet" type="text/css" href="<?=URL?>js/crop/css/jquery.Jcrop.min.css">
        <script src="<?=URL?>js/crop/js/jquery.Jcrop.js"></script>
        <script type="text/javascript" src="<?=URL?>js/uploadForm.js"></script>
        <!--/crop-->


        <link href="<?=URL?>js/croper/cropper.min.css" rel="stylesheet">
        <script>
        var url = "<?=URL?>";
        </script>


    </head>