<header class="header">
	<div class="logo">
		<img src="<?=URL?>img/logo/logo.png">
	</div>
	<div class="contact">
		<div class="phone">
			<strong>Telefone</strong>
			<p>(11) 4742-8823</p>
		</div>

		<div class="email">
			<strong>E-mail</strong>
			<p>infodahora@infodahora.com.br</p>
		</div>
	</div>

	<?php
	$fotoUsuario = ($_SESSION['login_adm']['foto'] != '') ? URL.'uploads/usuarios/p/'.$_SESSION['login_adm']['foto'] : URL.'img/imagens/perfil-icone.png';
	?>
	<div class="user">
		<figure>
			<!--<form id="form_cadastro_usuario" action="<?=URL?>configuracoes/usuarios/usuarios/uploadfoto" method="POST" enctype="multipart/form-data">-->
				<label for="fotoUsuario" style="cursor:pointer">
					<img src="<?=$fotoUsuario?>" id="img_previous">
					<!--<input type="file" name="fotoUsuario" id="fotoUsuario"  style="display:none"/>-->
				</label>
			<!--</form>-->
		</figure>
		<ul>
			<li><strong>Logado como:</strong> <?=$_SESSION['login_adm']['nome']?></li>
			<li><strong>Grupo:</strong> <?=$_SESSION['login_adm']['permissao']?></li>
			<li><a href="<?=URL?>login/sair" style="text-decoration:none">Sair <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span></a></li>
		</ul>
	</div>
</header>

<script type="text/javascript">
	$(function(){
		/*$('#form_cadastro_usuario').uploadImage({
            'width' : '150',
            'height' : '150',
            'original' :false,
            'submitform' : true
        });*/
	})


</script>