<div class="navbar navbar-default" role="navigation">
    <div class="container menu-container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <?php
            $url = new url();
            $activeLink = ($url->getSegment(0) == 'home' || $url->getSegment(0) == false) ? 'active' : '';
            ?>
            <a class="navbar-brand <?=$activeLink?>" href="<?=URL?>" ><figure><img src="<?=URL?>uploads/modulos/mod_0/home.png"></figure>Home</a>
        </div>
        <div class="collapse navbar-collapse navbar-ex1-collapse">
            <?php
            //library - menu
            $menu = new menu();
            echo $menu->geraMenu();
            ?>
        </div>
    </div>
</div>
<ol class="breadcrumb">
<?php
new breadcrumb();
?>
</ol>
<style type="text/css">
.breadcrumb a{
color: #035628;
font-weight: bold;
}

</style>
<script type="text/javascript">
$(function(){
    $('.dropdown-submenu > a').submenupicker();
})
</script>