<?php
/**
*@author Wellington cezar (programador jr) - wellington.infodahora@gmail.com
*/
$template = new template();
?>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    
    <?=$template->page_header('Escola Bíblica Dominical <small>classes</small>');?>
    <?php
        //page-header
        $btnClasse = $template->btnDefault('classes', URL.'ebd/classes/home','<span class="glyphicon glyphicon-user"></span> Classes');
    
        echo $template->actions_buttons($btnClasse);
    ?>
    <div class="middle-content">
        home da ebd
    </div>

</div>
<script>
$(document).ready(function() {
    var table = $('.dataTable').DataTable({
    	order: [1,'asc']
    });
    table.$('.btn_excluir').on('click',function(){
        var id = $(this).attr('id');
        var status = 'Excluído';

        $("#dialogResult").html('Deseja mesmo excluir?');
		$("#dialogResult").dialog({
			autoOpen: true,
			buttons: [
				{
					text: "Ok",
					click: function() {
						$( this ).dialog( "close" );

				    	$.post(url+'ebd/classes/excluir',{id:id,status:status},function(data){
							if(data == true){
								$('tr#'+id).hide();

                                $("#dialogResult").html('Registro enviado para a lixeira');
                                $("#dialogResult").dialog({
                                    autoOpen: true,
                                    buttons: [
                                        {
                                            text: "Ok",
                                            click: function() {
                                                $( this ).dialog( "close" );
                                            }
                                        }
                                    ]
                                });


                            }
						});
					}
				},
				{
					text: "Cancelar",
					click: function() {
						$( this ).dialog( "close" );
					}
				}
			]
		});



		
        
    });

    table.$('input[name=status]').on('change',function(){
    	var id = $(this).attr('id')
    	var status = 'Inativo';
		if($(this).is(':checked'))
			status = 'Ativo';

		$.post(url+'ebd/classes/atualizarStatus',{id:id,status:status},function(data){
            
		});

    });


});
</script>