<?php 
$template = new template();

?>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <?=$template->page_header('Adicionar tipo de recebimento');?>
    <?php
    $btnVoltar = $template->btnVoltar(URL.'configuracoes/tabelas/tipo_recebimento/');
    echo $template->actions_buttons($btnVoltar);
    ?>
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-left">
        <form action="<?=URL?>configuracoes/tabelas/tipo_recebimento/inserir" id="form_tipo_recebimento" method="POST">
            <div class="form-group has-feedback">
                <label for="tiporecebimento">Letra correspondente: </label>
                <select class="form-control" name="letra">
                    <option value="" selected="selected" disabled="disabled">Selecione uma letra</option>
                    <option value="Letra A">Letra A</option>
                    <option value="Letra B">Letra B</option>
                    <option value="Letra C">Letra C</option>
                    <option value="Letra D">Letra D</option>
                    <option value="Letra E">Letra E</option>
                    <option value="Letra F">Letra F</option>
                    <option value="Letra G">Letra G</option>
                    <option value="Letra H">Letra H</option>
                    <option value="Letra I">Letra I</option>
                    <option value="Letra J">Letra J</option>
                    <option value="Letra K">Letra K</option>
                    <option value="Letra L">Letra L</option>
                    <option value="Letra M">Letra M</option>
                    <option value="Letra N">Letra N</option>
                    <option value="Letra O">Letra O</option>
                    <option value="Letra P">Letra P</option>
                    <option value="Letra Q">Letra Q</option>
                    <option value="Letra R">Letra R</option>
                    <option value="Letra S">Letra S</option>
                    <option value="Letra T">Letra T</option>
                    <option value="Letra U">Letra U</option>
                    <option value="Letra V">Letra V</option>
                    <option value="Letra W">Letra W</option>
                    <option value="Letra X">Letra X</option>
                    <option value="Letra Y">Letra Y</option>
                    <option value="Letra Z">Letra Z</option>
                </select>
            </div>

            <div class="form-group has-feedback">
                <label for="tiporecebimento">Nome do tipo de recebimento</label>
                <input type="text" class="form-control" id="tiporecebimento" placeholder="Nome do tipo de recebimento" name="nome">
            </div>

            <div class="form-group has-feedback">
                <div class="input-group">
                    <span class="input-group-addon"><input type="checkbox" name="status" ></span>
                    <input type="text" class="form-control" value="Publicar ?" readonly="readonly">
                </div>
            </div>
            <button type="submit" class="btn btn-default" name="btn_salvar">Salvar</button>
        </form>
    </div>
</div>
<style>
.popover-content {
  padding: 0px 0px;
}
</style>
<script>
$(function() {    
    $('#form_tipo_recebimento').submitForm({
    	'reload' : true
    });
});




</script>