<?php 
$Letra_A = '';$Letra_B = '';$Letra_C = '';$Letra_D = '';$Letra_E = '';$Letra_F = '';$Letra_G = '';
$Letra_H = '';$Letra_I = '';$Letra_J = '';$Letra_K = '';$Letra_L = '';$Letra_M = '';$Letra_N = '';
$Letra_O = '';$Letra_P = '';$Letra_Q = '';$Letra_R = '';$Letra_S = '';$Letra_T = '';$Letra_U = '';
$Letra_V = '';$Letra_W = '';$Letra_X = '';$Letra_Y = '';$Letra_Z = '';
$template = new template();
?>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <?=$template->page_header('Editar tipo recebimento: <small>'.$nome_tipo_recebimento.'</small>');?>
    <?php
    $btnVoltar = $template->btnVoltar(URL.'configuracoes/tabelas/tipo_recebimento/');
    echo $template->actions_buttons($btnVoltar);
    ?>

    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-left">
        <form action="<?=URL?>configuracoes/tabelas/tipo_recebimento/atualizar" id="form_tipo_recebimento" method="POST">
            <div class="form-group">
                <label for="tiporecebimento">Letra correspondente: </label>
                <?php 
                $letra_tipo_recebimento = str_replace(' ', '_', $letra_tipo_recebimento);
                $$letra_tipo_recebimento = 'selected';
                ?>
                <select class="form-control" name="letra">
                    <option value="" selected="selected" disabled="disabled">Selecione uma letra</option>
                    <option value="Letra A" <?=$Letra_A?>>Letra A</option>
                    <option value="Letra B" <?=$Letra_B?>>Letra B</option>
                    <option value="Letra C" <?=$Letra_C?>>Letra C</option>
                    <option value="Letra D" <?=$Letra_D?>>Letra D</option>
                    <option value="Letra E" <?=$Letra_E?>>Letra E</option>
                    <option value="Letra F" <?=$Letra_F?>>Letra F</option>
                    <option value="Letra G" <?=$Letra_G?>>Letra G</option>
                    <option value="Letra H" <?=$Letra_H?>>Letra H</option>
                    <option value="Letra I" <?=$Letra_I?>>Letra I</option>
                    <option value="Letra J" <?=$Letra_J?>>Letra J</option>
                    <option value="Letra K" <?=$Letra_K?>>Letra K</option>
                    <option value="Letra L" <?=$Letra_L?>>Letra L</option>
                    <option value="Letra M" <?=$Letra_M?>>Letra M</option>
                    <option value="Letra N" <?=$Letra_N?>>Letra N</option>
                    <option value="Letra O" <?=$Letra_O?>>Letra O</option>
                    <option value="Letra P" <?=$Letra_P?>>Letra P</option>
                    <option value="Letra Q" <?=$Letra_Q?>>Letra Q</option>
                    <option value="Letra R" <?=$Letra_R?>>Letra R</option>
                    <option value="Letra S" <?=$Letra_S?>>Letra S</option>
                    <option value="Letra T" <?=$Letra_T?>>Letra T</option>
                    <option value="Letra U" <?=$Letra_U?>>Letra U</option>
                    <option value="Letra V" <?=$Letra_V?>>Letra V</option>
                    <option value="Letra W" <?=$Letra_W?>>Letra W</option>
                    <option value="Letra X" <?=$Letra_X?>>Letra X</option>
                    <option value="Letra Y" <?=$Letra_Y?>>Letra Y</option>
                    <option value="Letra Z" <?=$Letra_Z?>>Letra Z</option>
                </select>
            </div>
            <div class="form-group has-feedback">
                <label for="estadocivil">Nome do estado civil</label>
                <input type="text" class="form-control" id="estadocivil" placeholder="Nome do estado civil" name="nome" value="<?=$nome_tipo_recebimento?>">
            </div>


            <div class="form-group has-feedback">
                <div class="input-group">
                    <span class="input-group-addon"><input type="checkbox" name="status" <?=$status_tipo_recebimento?>></span>
                    <input type="text" class="form-control" value="Publicar ?" readonly="readonly" >
                </div>
            </div>

            <input type="hidden" class="form-control" id="id" name="id" value="<?=$id_tipo_recebimento?>">
            <button type="submit" class="btn btn-default" name="btn_salvar">Salvar</button>
        </form>
    </div>
</div>
<style>
.popover-content {
  padding: 0px 0px;
}
</style>
<script>
$(function() {    
    $('#form_tipo_recebimento').submitForm({
    	'reload' : true
    });
});
</script>