<?php
/**
*@author Wellington cezar (programador jr) - wellington.infodahora@gmail.com
*/
$template = new template();
?>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    
    <?=$template->page_header('Lista de membros');?>
    <?php
        //page-header
        $btnAdiconar = $template->btnAdicionarRegistro(URL.'rol-de-membros/home/cadastrar','<span class="glyphicon glyphicon-user"></span> Adicionar membro');
    
        echo $template->actions_buttons($btnAdiconar);
    ?>
    <div class="middle-content">
        <?php
        $thead = '  <tr>   
                        <th width="40">Foto</th>
                        <th width="160">Nome</th>
                        <th width="120">Igreja</th>
                        <th width="100">Data de Nascimento</th>
                        <th width="100">Status (Ativo/Inativo)</th>
                        <th width="100">Ações</th>
                    </tr>';
        $tfoot = '  <tr>
                        <th>Foto</th>
                        <th>Nome</th>
                        <th>Igreja</th>
                        <th>Data de Nascimento</th>
                        <th>Status (Ativo/Inativo)</th>
                        <th>Ações</th>
                    </tr>';	 
        if($membros != false):
            $tbody = '';
            foreach ($membros as $membro):
            	$status = ($membro['status_membro'] == 'Ativo') ? true : false;
                $foto = ($membro['foto_membro'] != '') ? URL.'uploads/membros/p/'.$membro['foto_membro'] : URL.'img/imagens/perfil-icone.png';

                $tbody .='  <tr id="'.$membro['id_membro'].'">
                                <td><img src="'.$foto.'" style="width: 60px;"></td>
                                <td>'.$membro['nome_membro'].' '.$membro['sobrenome_membro'].'</td>
                                
                                <td>'.$membro['nome_igreja'].'</td>
                                <td>'.date('d/m/Y', strtotime($membro['data_nascimento_membro'])).'</td>
                                <td>
                                    '.$template->checkboxStatus($membro['id_membro'],'status',$status).'
                                </td>
                                <td>
                                    '.$template->btnEditarRegistro(URL.'rol-de-membros/home/editar/'.$membro['id_membro']).$template->btnExcluirRegistro('javascript:void(0)',$membro['id_membro']).
                                '</td>
                            </tr>';
                

            endforeach;
            echo $template->tabela($thead, $tfoot, $tbody);
        else:
            echo '<h2>Não há registros cadastrados</h2>';
        endif;
        ?>
    </div>

</div>
<script>
$(document).ready(function() {
    var table = $('.dataTable').DataTable({
    	order: [1,'asc']
    });
    table.$('.btn_excluir').on('click',function(){
        var id = $(this).attr('id');
        var status = 'Excluído';

        $("#dialogResult").html('Deseja mesmo excluir?');
		$("#dialogResult").dialog({
			autoOpen: true,
			buttons: [
				{
					text: "Ok",
					click: function() {
						$( this ).dialog( "close" );

				    	$.post(url+'rol-de-membros/home/excluir',{id:id,status:status},function(data){
							if(data == true){
								$('tr#'+id).hide();

                                $("#dialogResult").html('Registro enviado para a lixeira');
                                $("#dialogResult").dialog({
                                    autoOpen: true,
                                    buttons: [
                                        {
                                            text: "Ok",
                                            click: function() {
                                                $( this ).dialog( "close" );
                                            }
                                        }
                                    ]
                                });


                            }
						});
					}
				},
				{
					text: "Cancelar",
					click: function() {
						$( this ).dialog( "close" );
					}
				}
			]
		});



		
        
    });

    table.$('input[name=status]').on('change',function(){
    	var id = $(this).attr('id')
    	var status = 'Inativo';
		if($(this).is(':checked'))
			status = 'Ativo';

		$.post(url+'rol-de-membros/home/atualizarStatus',{id:id,status:status},function(data){
            
		});

    });


});
</script>