<div class="container">
    <?php
        $btnCadastrar = $this->templateFactory->getButton("cadastrar",array('href'=>URL.'suprimentos/requisicoes/gerenciar/cadastrar'), URL.'suprimentos/requisicoes/gerenciar/cadastrar');
        echo $this->templateFactory->getButton("actions_buttons",array('buttons'=>$btnCadastrar));
    ?>
    <div class="page-header">
      <h1>Estoque - <small>Zona reservada</small></h1>
    </div>
    <div class="middle-content">
        <?php
            $thead = '  <tr>
            				<th width="20">ID</th>
            				<th width="20">Produto</th>
                            <th width="160">Quantidade Total</th>
                            <th width="160">Nível</th>
                            <th width="180">Ações</th>
                        </tr>';
            $tfoot = '  <tr>
							<td>ID</td>            
                            <th>Produto</th>
                            <th>Quantidade Total</th>
                            <td>Nível</td>
                            <td>Ações</td>
                        </tr>';  

                $tbody = '';
                foreach ($estoque as $estoqueProd):

            $tbody .='  <tr id="'.$estoqueProd->getId().'">
        					<td>'.$estoqueProd->getId().'</td>
                            <td>'.$estoqueProd->getProduto()->getNome().'</td>
                            <td>'.$dataformat->formatar($estoqueProd->getQuantidadeTotal(),'decimal').' '.$estoqueProd->getUnidadeMedidaParaEstoque()->getUnidadeMedida()->getNome().'</td>
                            <td>
								<h4><span class="pull-left label-danger label">5</span></h4>
								<h4><span class="pull-right label-success label">20</span></h4>
								<div class="progress">
								  	<div class="progress-bar progress-bar-success progress-bar-striped active" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 20%">
								    	<span class="sr-only">10% Complete</span>
								 	</div>
								</div>
                            </td>
                            <td>'
                                .$this->templateFactory->getButton('lotes',array('href'=>URL.'estoque/lotes/'.$estoqueProd->getId(), 'title'=>'Lotes')).
                            '</td>
                        </tr>';
                endforeach;
                echo $this->templateFactory->getTable('tabela', array('thead'=>$thead, 'tfoot'=>$tfoot, 'tbody'=>$tbody));
            ?>
    </div>

</div>
<div class="modal fade" id="modalProdutosRequisitados">
        <div class="modal-dialog animated zoomIn ">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Lista De Produtos Requisitados</h4>
                </div>
                <div class="modal-body">
                   
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">OK</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

<script type="text/javascript">
    $(function(){
        //DATATABLE
        var table = $('.dataTable').DataTable({
            order: [0,'asc']
        });

        //EXCLUIR
        table.$('.btn_cancelar').on('click',function(){
            var id = $(this).attr('id');
            var status = $(this).data('value');
            var modalDelete = $('#modalDelete').modal('show')
            $('.btn_ok','#modalDelete').on('click', function(event) {
                $.post(url+'suprimentos/requisicoes/gerenciar/cancelar',{id:id,status:status},function(data){
                    console.log(data)
                    if(data == true){
                        $('#modalDelete').modal('hide');
                        $('tr#'+id).hide();
                    }
                });
            });
        });

        table.$('.btn_visualizar').on('click',function(){
            $('#modalProdutosRequisitados').modal('show');
            
            $.post($(this).attr('href'), {}, function(data, textStatus, xhr) {
                $('#modalProdutosRequisitados .modal-body').html(data);
            });


            return false;
        })

    })
</script>


