<div class="container">
    <div class="page-header">
      <h1>Fornecedores<small> Cadastro</small></h1>
    </div>
    <form action="">

        <div class="panel panel-default">
          <div class="panel-heading">Dados Empresáriais</div>
          <div class="panel-body">

            <div class="row">
            <div class="col-xs-6 col-md-3">
                <a href="#" class="thumbnail">
                    <img src="<?=URL?>skin/img/imagens/logo_coca.jpg" alt="...">
                </a>
            </div>
        </div>
             <div >
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">Razão Social</span>
                <input type="text" class="form-control" placeholder="Razão Social" aria-describedby="basic-addon1">
            </div>
        </div>

        <div >
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">Nome Fantasia</span>
                <input type="text" class="form-control" placeholder="Nome Fantasia" aria-describedby="basic-addon1">
            </div>
        </div>

        <div >
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">CNPJ</span>
                <input type="text" class="form-control" placeholder="CNPJ" aria-describedby="basic-addon1">
            </div>
        </div>

        <div >
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">CPF</span>
                <input type="text" class="form-control" placeholder="CPF" aria-describedby="basic-addon1">
            </div>
        </div>

       <div>
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">Pessoa</span>
                <select class="form-control">
                    <option value="" selected="selected" disabled="disabled">..Selecione..</option>
                    <option value="g">Física</option>
                    <option value="kg">Jurídica</option>
                </select>
            </div>
        </div>
        <div >
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">Site</span>
                <input type="text" class="form-control" placeholder="Site" aria-describedby="basic-addon1">
            </div>
        </div>
        <div >
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">Observações</span>
                <input type="text" class="form-control" placeholder="Observações" aria-describedby="basic-addon1">
            </div>
        </div>
        
        <div class="panel panel-default">
            <div class="panel-heading">Contatos</div>
            <div class="panel-body">
            
            <div >
                <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">Nome Para Contato</span>
                <input type="text" class="form-control" placeholder="Nome Para Contato" aria-describedby="basic-addon1">
                </div>
            </div>
            <div>
                <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">Telefone</span>
                <input type="text" class="form-control" placeholder="Telefone" aria-describedby="basic-addon1">
                </div>
            </div>
            <div >
                <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">E-mail</span>
                <input type="text" class="form-control" placeholder="E-mail" aria-describedby="basic-addon1">
                </div>
            </div>
            
        </div> 



        </div> <!-- fim panel dados gerais -->

        
       
       <div class="panel panel-default">
       <div class="panel-heading">Endereço</div>
       <div class="panel-body">
   
        <div>
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">CEP</span>
                <input type="text" class="form-control" placeholder="CEP" aria-describedby="basic-addon1">
            </div>
        </div>
       <div>
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">Logradouro</span>
                <input type="text" class="form-control" placeholder="Logradouro" aria-describedby="basic-addon1">
            </div>
        </div>

        <div>
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">Número</span>
                <input type="text" class="form-control" placeholder="Número" aria-describedby="basic-addon1">
            </div>
        </div>

        

        <div>
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">Cidade</span>
                <input type="text" class="form-control" placeholder="Cidade" aria-describedby="basic-addon1">
            </div>
        </div>

        <div >
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">Bairro</span>
                <input type="text" class="form-control" placeholder="Bairro" aria-describedby="basic-addon1">
            </div>
        </div>
        <div>
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">UF</span>
                <input type="text" class="form-control" placeholder="UF" aria-describedby="basic-addon1">
            </div>
        </div>
         <div>
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">País</span>
                <input type="text" class="form-control" placeholder="País" aria-describedby="basic-addon1">
            </div>
        </div>
         
</div><!-- fim panel Endereço -->
     
        <div class="btn-group" role="group">
            <button type="submit" class="btn btn-default">Enviar</button>
        </div>
    </form>
</div>