<div class="actions-buttons">
    <div class="container">
        <a class="btn btn-primary pull-right btn_adicionar" href="<?=URL?>fornecedores/home/cadastrar" role="button" id="btn_adicionar"><span class="glyphicon glyphicon-plus"></span>Cadastrar</a>
    </div>
</div>

<div class="container">
    <div class="page-header">
      <h1>Funcionários</h1>
    </div>
    <div class="middle-content">
        <img src="<?=URL?>img/loading3.gif" style="display: block;  margin: auto;  width: 200px;" id="loadTable">
        <table class="dataTable rwd-table" cellspacing="0" width="100%" style="display:none">
            <thead>
                <tr>   
                    <th width="100">Código</th>
                    <th width="40">Foto</th>
                    <th width="160">Razão Social</th>
                    <th width="160">Nome Fantasia</th>
                    <th width="120">CNPJ</th>
                    <th width="100">Status (Ativo/Inativo)</th>
                    <th width="180">Ações</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th>Código</th>
                    <th>Foto</th>
                    <th>Razão Social</th>
                    <th>Nome Fantasia</th>
                    <th>CNPJ</th>
                    <th>Status (Ativo/Inativo)</th>
                    <th>Ações</th>
                </tr>
            </tfoot>
            <tbody>
            <?php
            if(!empty($fornecedores)):
                foreach ($fornecedores as $forn):
                    $foto = $forn->getFoto() != '' ? URL.'skin/uploads/fornecedores/p/'.$forn->getFoto() : URL.'skin/img/imagens/semfoto.jpg';
            ?>
                <tr id="<?=$forn->getId()?>">
                    <td><?=$forn->getCodigo()?></td>
                    <td><img src="<?=$foto?>" style=" width: 60px; height: 60px;"></td>
                    <td><?=$forn->getNome().' '.$forn->getSobrenome()?></td>
                    <td><?=$forn->getCargo()?></td>
                    <td><?=$forn->getCpf()?></td>
                    <td>
                        <select name="status" id="<?=$forn->getId()?>" class="statusSelect">
                            <option value="<?=status::ATIVO?>" class="active" <?=($forn->getStatus() == status::ATIVO) ? 'selected="selected"' : ''?>>Ativo</option>
                            <option value="<?=status::INATIVO?>" class="inactive" <?=($forn->getStatus() == status::INATIVO) ? 'selected="selected"' : ''?>>Inativo</option>
                        </select>
                    </td>
                    <td>
                        <a class="btn btn-primary btn_editar btn-sm" href="<?=URL?>fornecedores/home/editar/<?=$forn->getId()?>" role="button" id-record="<?=$forn->getId()?>" ><span class="glyphicon glyphicon-pencil"></span> Editar</a>
                        <a class="btn btn-danger btn_excluir btn-sm" href="javascript:void(0)" role="button" id="<?=$forn->getId()?>" data-value="<?=status::EXCLUIDO?>" ><span class="glyphicon glyphicon-remove"></span>Excluir</a>
                    </td>
                </tr>
            <?php
                endforeach;
            endif;
            ?>
                
            </tbody>
        </table>
    </div>

</div>

<script type="text/javascript">
    $(function(){
        //DATATABLE
        var table = $('.dataTable').DataTable({
            order: [0,'asc']
        });

        //STATUS
        table.$('select[name=status]').on('change',function(){
            var id = $(this).attr('id');
            var status = $(this).val();
            $.post(url+'fornecedores/home/atualizarStatus',{id:id,status:status},function(data){
                console.log(data)
                if(data == true)
                    messageDialog('Status atualizado','success',false,null);
                else
                    messageDialog('Erro ao atualizar','warning',false,null);
            });

        });

        //EXCLUIR
        table.$('.btn_excluir').on('click',function(){
            var id = $(this).attr('id');
            var status = $(this).data('value');
            var modalDelete = $('#modalDelete').modal('show')
            $('.btn_ok','#modalDelete').on('click', function(event) {
                $.post(url+'fornecedores/home/excluir',{id:id,status:status},function(data){
                    console.log(data)
                    if(data == true){
                        $('#modalDelete').modal('hide');
                        $('tr#'+id).hide();
                    }
                });
            });
        });


    })
</script>
