<div class="container">
    <?php

        $btnVoltar = $template->getButton('voltar',array('href'=>URL.'funcionarios/usuarios'));
        echo $template->getButton('actions_buttons',array('buttons'=>$btnVoltar));
    ?>
    <div class="page-header">
      <h1>Usuários <small>Cadastro</small></h1>
    </div>
    <form action="<?=URL?>funcionarios/usuarios/gerenciar/inserir" method="post" id="form_usuarios">
        <div class="panel panel-default">
            <div class="panel-heading">Dados Gerais</div>
            <div class="panel-body">
                 <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Nível de acesso</span>
                    <select name="nivel" id="nivel" class="form-control">
                        <option selected="selected" disabled="disabled" value="">..Selecione..</option>
                        <?php if(!empty($niveisAcesso)):?>
                        <?php foreach ($niveisAcesso as $nivelAcesso):?>
                        <option value="<?= $nivelAcesso->getId()?>"><?=$nivelAcesso->getNome()?></option>
                        <?php endforeach;?>
                        <?php endif;?>
                    </select>
                </div>
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Funcionário</span>
                    <select name="funcionario" id="funcionarios" class="form-control">
                        <option selected="selected" disabled="disabled" value="">..Selecione..</option>
                        <?php if(!empty($funcionarios)):?>
                        <?php foreach ($funcionarios as $funcionario):?>
                        <option value="<?= $funcionario->getId()?>"><?=$funcionario->getNome()?></option>
                        <?php endforeach;?>
                        <?php endif;?>
                    </select>
                </div>
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Email</span>
                    <input type="email" class="form-control" placeholder="Email" name="email" >
                </div>
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Login</span>
                    <input type="text" class="form-control" placeholder="Login" name="login">
                </div>
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Senha</span>
                    <input type="password" class="form-control" placeholder="Senha" name="senha">
                </div>
                <div class="btn-group pull-right" role="group">
                    <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-ok"></span> Salvar</button>
                </div>

            </div>
        </div>
     </div>
    </form>
</div>

<script type="text/javascript" src="<?=URL?>skin/js/uploadForm.js"></script>
<link href="<?=URL?>skin/js/croper/cropper.min.css" rel="stylesheet">
<link href="<?=URL?>skin/js/croper/main.css" rel="stylesheet">
<script src="<?=URL?>skin/js/croper/cropper.min.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/jquery.maskedinput.min.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/jquery.maskMoney.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/jquery.validate.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/funcionarios/usuarios/cadastrar.js"></script>
