<div class="container">
    <?php
        $btnVoltar = $template->btnVoltar(URL.'funcionarios/usuarios');
        echo $template->actions_buttons($btnVoltar);
    ?>
    <div class="page-header">
      <h1>Usuários <small>Cadastro</small></h1>
    </div>
    <form action="<?=URL?>funcionarios/usuarios/inserir" method="post" id="form_funcionarios">
        <div class="panel panel-default">
            <div class="panel-heading">Dados Gerais</div>
            <div class="panel-body">
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Email</span>
                    <input type="text" class="form-control" placeholder="Email" name="email" >
                </div>
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Funcionario</span>
                    <input type="text" class="form-control" placeholder="Funcionario" name="funcionario">
                </div>
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Login</span>
                    <input type="text" class="form-control" placeholder="Login" name="login">
                </div>
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Senha</span>
                    <input type="text" class="form-control" placeholder="Senha" name="senha">
                </div>
            </div>
        </div>


       

     </div>
    </form>
</div>

<script type="text/javascript" src="<?=URL?>skin/js/uploadForm.js"></script>
<link href="<?=URL?>skin/js/croper/cropper.min.css" rel="stylesheet">
<link href="<?=URL?>skin/js/croper/main.css" rel="stylesheet">
<script src="<?=URL?>skin/js/croper/cropper.min.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/jquery.maskedinput.min.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/jquery.maskMoney.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/jquery.validate.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/funcionarios/cadastrar.js"></script>
