<div class="container">
    <?php

        $btnCadastrar = $this->templateFactory->getButton("cadastrar",array('href'=>URL.'funcionarios/usuarios/gerenciar/cadastrar'));
        echo $this->templateFactory->getButton("actions_buttons",array('buttons'=>$btnCadastrar));

    ?>
    <div class="page-header">
      <h1>Usuários</h1>
    </div>
    <div class="middle-content">
            <?php
            $thead = '  <tr>
            				<th width="20">ID</th>
                            <th width="100">Nível</th>
                            <th width="160">Funcionário</th>
                            <th width="160">Email</th>
                            <th width="160">Login</th>
                            <th width="100">Status (Ativo/Inativo)</th>
                            <th width="180">Ações</th>
                        </tr>';
            $tfoot = '  <tr>
            				<th>ID</th>
                            <th>Nível</th>
                            <th>Funcionario</th>
                            <th>Email</th>
                            <th>Login</th>
                            <th>Status(Ativo/Inativo)</th>
                            <th>Ações</th>
                        </tr>';  
            if(!empty($usuarios)):
                $tbody = '';
                foreach ($usuarios as $usu):

                    $ativo = ($usu->getStatus() == status::ATIVO) ? 'selected="selected"' : '';
                    $inativo = ($usu->getStatus() == status::INATIVO) ? 'selected="selected"' : '';

            $tbody .='  <tr id="'.$usu->getId().'">
            				<td>'.$usu->getId().'</td>
                            <td>'.$usu->getNivelAcesso()->getNome().'</td>
                            <td>'.$usu->getFuncionario()->getNome().' '.$usu->getFuncionario()->getSobrenome().'</td>
                            <td>'.$usu->getEmail().'</td>
                            <td>'.$usu->getLogin().'</td>
                            <td>';
                            if($usu->getNivelAcesso()->getPermissoes() != '*'):

            $tbody .='  		<select name="status" id="'.$usu->getId().'" class="statusSelect">
                                    <option value="'.status::ATIVO.'" class="active" '.$ativo.'>Ativo</option>
                                    <option value="'.status::INATIVO.'" class="inactive" '.$inativo.'>Inativo</option>
                                </select>';

                            endif;
            $tbody .='  	</td>
                            <td>'.$this->templateFactory->getButton('editar',array('href'=> URL.'funcionarios/usuarios/gerenciar/editar/'.$usu->getId()));
                           	if($usu->getNivelAcesso()->getPermissoes() != '*'):
            $tbody .= 			$this->templateFactory->getButton('excluir', array('id'=> $usu->getId()));
                            endif;
            $tbody .= 		'</td>
                        </tr>';
                endforeach;
                echo $template->getTable('tabela', array('thead'=>$thead, 'tfoot'=>$tfoot, 'tbody'=>$tbody));
            else:
                echo '<h2>Não há registros cadastrados</h2>';
            endif;
            ?>

    </div>

</div>

<script type="text/javascript">
    $(function(){
        //DATATABLE
        var table = $('.dataTable').DataTable({
            order: [0,'asc']
        });

        //STATUS
        table.$('select[name=status]').on('change',function(){
            var id = $(this).attr('id');
            var status = $(this).val();
            $.post(url+'funcionarios/usuarios/gerenciar/atualizarStatus',{id:id,status:status},function(data){
                console.log(data)
                if(data == true)
                    messageDialog('Status atualizado','success',false,null);
                else
                    messageDialog('Erro ao atualizar','warning',false,null);
            });

        });

        //EXCLUIR
        table.$('.btn_excluir').on('click',function(){
            var id = $(this).attr('id');
            var status = $(this).data('value');
            var modalDelete = $('#modalDelete').modal('show')
            $('.btn_ok','#modalDelete').on('click', function(event) {
                $.post(url+'funcionarios/usuarios/gerenciar/excluir',{id:id,status:status},function(data){
                    console.log(data)
                    if(data == true){
                        $('#modalDelete').modal('hide');
                        $('tr#'+id).hide();
                    }
                });
            });
        });


    })
</script>

