<?php 
$template = new template();
?>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <?=$template->page_header('Lista dos módulos');?>
    <?php
    //$btnVoltar = $template->btnVoltar(URL.'configuracoes/modulos/');
    //echo $template->actions_buttons($btnVoltar);
    ?>
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-left list_grupo_usuario" >
        <form action="javascript:void(0)" id="form_modulos" method="POST">
            <button class="btn btn-defult checkAll">Selecionar todos</button><button class="btn btn-defult uncheckAll">Remover seleção</button>
            <div class="tree" style="padding-top: 14px;padding-right: 14px;">
            <?php
            if($modulos != false):
            ?>
                <ul id="update-position">
                <?php
                foreach ($modulos as $keyMod => $mod):
                ?>
                    <li id="listItem_<?=$keyMod?>"><!--modulo-->
                        <div class="form-group has-feedback">
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <input type="checkbox" name="status" id="<?=$keyMod?>" tipo="modulo" campo="status_modulo" <?=($mod['status'] == 'Ativo') ? 'checked' : ''?>>
                                </span>
                                <?php
                                    $Ativo = '';
                                    $Inativo = '';
                                    $$mod['status_selecao'] = 'selected';
                                ?>
                                <span class="input-group-addon">
                                    <select name="status" id="<?=$keyMod?>" id="<?=$keyMod?>" tipo="modulo" campo="status_selecao" <?=($mod['status'] == 'Ativo') ? 'checked' : ''?>>
                                        <option value="" disabled="disabled" selected="selected">Indefinido</option>
                                        <option value="Ativo" <?=$Ativo?>>Ativo</option>
                                        <option value="Inativo" <?=$Inativo?>>Inativo</option>
                                    </select>
                                </span>
                                <input type="text" class="form-control" placeholder="<?=$mod['url']?>" value="<?=$mod['nome']?>" tipo="modulo" id="<?=$keyMod?>" campo="nome_modulo">
                                <!--
                                <span class="input-group-addon">
                                    <button>Excluir</button>
                                </span>
                                -->
                            </div>
                        </div>
                        <?php
                        if(!empty($mod['paginas'])):
                        ?>
                        <ul>
                            <?php
                            foreach ($mod['paginas'] as $keyModPag => $modPag):
                                
                            ?>
                            <li>
                                <div class="form-group has-feedback">
                                    <div class="input-group">
                                        <span class="input-group-addon">
                                            <input type="checkbox" name="status" id="<?=$keyModPag?>" tipo="pagina" campo="status_pagina" <?=($modPag['status'] == 'Ativo') ? 'checked' : ''?>>
                                        </span>
                                        <?php
                                            $Ativo = '';
                                            $Inativo = '';
                                            $$modPag['status_selecao'] = 'selected';
                                        ?>
                                        <span class="input-group-addon">
                                            <select name="status" id="<?=$keyModPag?>" tipo="pagina" campo="status_selecao" <?=($modPag['status'] == 'Ativo') ? 'checked' : ''?>>
                                                <option value="" disabled="disabled" selected="selected">Indefinido</option>
                                                <option value="Ativo" <?=$Ativo?>>Ativo</option>
                                                <option value="Inativo" <?=$Inativo?>>Inativo</option>
                                            </select>
                                        </span>
                                        <input type="text" class="form-control" placeholder="<?=$modPag['url']?>" value="<?=$modPag['nome']?>" tipo="pagina" id="<?=$keyModPag?>" campo="nome_pagina">
                                    </div>
                                </div>
                                <?php
                                if(!empty($modPag['acoes'])):
                                ?>
                                <ul>
                                    <?php
                                    foreach ($modPag['acoes'] as $keyModPagAct => $modPagAct):
                                    ?>
                                    <li>
                                        <div class="form-group has-feedback">
                                            <div class="input-group">
                                                <span class="input-group-addon">
                                                    <input type="checkbox" name="status" id="<?=$keyModPagAct?>" tipo="acao" campo="status_action" <?=($modPagAct['status'] == 'Ativo') ? 'checked' : ''?>>
                                                </span>
                                                <?php
                                                    $Ativo = '';
                                                    $Inativo = '';
                                                    $$modPagAct['status_selecao'] = 'selected';
                                                ?>
                                                <span class="input-group-addon">
                                                    <select name="status" id="<?=$keyModPagAct?>" tipo="acao" campo="status_selecao" <?=($modPagAct['status'] == 'Ativo') ? 'checked' : ''?>>
                                                        <option value="" disabled="disabled" selected="selected">Indefinido</option>
                                                        <option value="Ativo" <?=$Ativo?>>Ativo</option>
                                                        <option value="Inativo" <?=$Inativo?>>Inativo</option>
                                                    </select>
                                                </span>
                                                <input type="text" class="form-control" placeholder="<?=$modPagAct['url']?>" value="<?=$modPagAct['nome']?>" tipo="acao" id="<?=$keyModPagAct?>" campo="nome_action">
                                            </div>
                                        </div>
                                    </li>
                                    <?php
                                    endforeach;
                                    ?>
                                </ul>
                                <?php
                                endif;
                                ?>



                            </li>
                            <?php
                            endforeach;
                            ?>
                        </ul>
                        <?php
                        endif;
                        ?>





                        <?php
                        if(!empty($mod['submodulos'])):
                            
                        ?>
                        <ul>
                            <?php
                            foreach ($mod['submodulos'] as $keyModSubmod => $modSubmod):
                                
                                
                            ?>
                            <li>
                                <div class="form-group">
                                    <div class="input-group has-feedback">
                                        <span class="input-group-addon">
                                            <input type="checkbox" name="status" id="<?=$keyModSubmod?>" tipo="submodulo" campo="status_modulo" <?=($modSubmod['status'] == 'Ativo') ? 'checked' : ''?>>
                                        </span>
                                        <?php
                                            $Ativo = '';
                                            $Inativo = '';
                                            $$modSubmod['status_selecao'] = 'selected';
                                        ?>
                                        <span class="input-group-addon">
                                            <select name="status" id="<?=$keyModSubmod?>" tipo="submodulo" campo="status_selecao" <?=($modSubmod['status'] == 'Ativo') ? 'checked' : ''?>>
                                                <option value="" disabled="disabled" selected="selected">Indefinido</option>
                                                <option value="Ativo" <?=$Ativo?>>Ativo</option>
                                                <option value="Inativo" <?=$Inativo?>>Inativo</option>
                                            </select>
                                        </span>
                                        <input type="text" class="form-control" placeholder="<?=$modSubmod['url']?>" value="<?=$modSubmod['nome']?>" tipo="submodulo" id="<?=$keyModSubmod?>" campo="nome_modulo">
                                    </div>
                                </div>
                                <?php
                                if(!empty($modSubmod['paginas'])):
                                ?>
                                <ul>
                                    <?php
                                    foreach ($modSubmod['paginas'] as $keyModSubmodPag => $modSubmodPag):
                                    ?>
                                    <li>
                                        <div class="form-group has-feedback">
                                            <div class="input-group">
                                                <span class="input-group-addon">
                                                    <input type="checkbox" name="status" id="<?=$keyModSubmodPag?>" tipo="pagina" campo="status_pagina" <?=($modSubmodPag['status'] == 'Ativo') ? 'checked' : ''?>>
                                                </span>
                                                <?php
                                                    $Ativo = '';
                                                    $Inativo = '';
                                                    $$modSubmodPag['status_selecao'] = 'selected';
                                                ?>
                                                <span class="input-group-addon">
                                                    <select name="status" id="<?=$keyModSubmodPag?>" tipo="pagina" campo="status_selecao" <?=($modSubmodPag['status'] == 'Ativo') ? 'checked' : ''?>>
                                                        <option value="" disabled="disabled" selected="selected">Indefinido</option>
                                                        <option value="Ativo" <?=$Ativo?>>Ativo</option>
                                                        <option value="Inativo" <?=$Inativo?>>Inativo</option>
                                                    </select>
                                                </span>
                                                <input type="text" class="form-control" placeholder="<?=$modSubmodPag['url']?>" value="<?=$modSubmodPag['nome']?>" tipo="pagina" id="<?=$keyModSubmodPag?>" campo="nome_pagina">
                                            </div>
                                        </div>

                                        <?php
                                        if(!empty($modSubmodPag['acoes'])):
                                        ?>
                                        <ul>
                                            <?php
                                            foreach ($modSubmodPag['acoes'] as $keyModSubmodPagAct => $modSubmodPagAct):
                                            ?>
                                            <li>
                                                <div class="form-group has-feedback">
                                                    <div class="input-group">
                                                        <span class="input-group-addon">
                                                            <input type="checkbox" name="status" id="<?=$keyModSubmodPagAct?>" tipo="acao" campo="status_action" <?=($modSubmodPagAct['status'] == 'Ativo') ? 'checked' : ''?>>
                                                        </span>
                                                        <?php
                                                            $Ativo = '';
                                                            $Inativo = '';
                                                            $$modSubmodPagAct['status_selecao'] = 'selected';
                                                        ?>
                                                        <span class="input-group-addon">
                                                            <select name="status" id="<?=$keyModSubmodPagAct?>" tipo="acao" campo="status_selecao" <?=($modSubmodPagAct['status'] == 'Ativo') ? 'checked' : ''?>>
                                                                <option value="" disabled="disabled" selected="selected">Indefinido</option>
                                                                <option value="Ativo" <?=$Ativo?>>Ativo</option>
                                                                <option value="Inativo" <?=$Inativo?>>Inativo</option>
                                                            </select>
                                                        </span>
                                                        <input type="text" class="form-control" placeholder="<?=$modSubmodPagAct['url']?>" value="<?=$modSubmodPagAct['nome']?>" tipo="acao" id="<?=$keyModSubmodPagAct?>" campo="nome_action"> 
                                                    </div>
                                                </div>
                                            </li>
                                            <?php
                                            endforeach;
                                            ?>
                                        </ul>
                                        <?php
                                        endif;
                                        ?>


                                    </li>
                                    <?php
                                    endforeach;
                                    ?>
                                </ul>
                                <?php
                                endif;
                                ?>
                            </li>
                            <?php
                            endforeach;
                            ?>
                        </ul>
                        <?php
                        endif;
                        ?>
                    </li>
                <?php
                endforeach;
                ?>

                </ul>
            <?php
            endif;
            ?>
            </div>
        </form>
    </div>
</div>
<style>
.popover-content {
  padding: 0px 0px;
}
</style>
<script type="text/javascript" src="<?=URL?>js/jquery-tree/js/jquery.tree.js"></script>
<link rel="stylesheet" type="text/css" href="<?=URL?>js/jquery-tree/css/jquery.tree.css"/>
<script>
$(function() {    
    $('#form_usuarios').submitForm({
    	'reload' : true
    });
    
    $('.tree').tree({
        collapseUiIcon: 'ui-icon-plus',
        expandUiIcon: 'ui-icon-minus',
        leafUiIcon: 'ui-icon-bullet'
    });
            
    $('.checkAll').click(function(){
        $('.tree').tree('checkAll');
        return false;
    });

    $('.uncheckAll').click(function(){
        $('.tree').tree('uncheckAll');
        return false;
    });
    //atualiza o nome dos módulos, submodulos, paginas e ações
    var valueAnt = '';
    $('#form_modulos input[type=text]').on('focusin',function(event) {
        valueAnt = $(this).val();
    });

    $('#form_modulos input[type=text]').on('focusout',function(event) {
        var input = $(this);
        if(valueAnt != $(this).val())
        {
            var id = $(this).attr('id');
            var campo = $(this).attr('campo');
            var tipo = $(this).attr('tipo');
            var valor = $(this).val();
            $.post('<?=URL?>configuracoes/modulos/home/atualizar',{tipo:tipo, id:id, campo:campo, valor:valor},function(data){
                if(data)
                {
                    input.after('<span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>');
                    setTimeout(function(){
                        $('.form-control-feedback').remove();
                    },2000);
                }
            })
        }
    });

    //atualiza o status geral
    $('#form_modulos input[name=status]').on('change',function(event) {
        var input = $(this);
        var id = $(this).attr('id');
        var campo = $(this).attr('campo');
        var tipo = $(this).attr('tipo');
        var valor = $(this).val();

        if($(this).is(':checked'))
            valor = 'Ativo';
        else
            valor = 'Inativo';

        $.post('<?=URL?>configuracoes/modulos/home/atualizar',{tipo:tipo, id:id, campo:campo, valor:valor},function(data){
            if(data)
            {
                input.after('<span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>');
                setTimeout(function(){
                    $('.form-control-feedback').remove();
                },2000);
            }
        });
    });


    //atualiza o status geral
    $('#form_modulos select[name=status]').on('change',function(event) {
        var input = $(this);
        var id = $(this).attr('id');
        var campo = $(this).attr('campo');
        var tipo = $(this).attr('tipo');
        var valor = $(this).val();



        $.post('<?=URL?>configuracoes/modulos/home/atualizar',{tipo:tipo, id:id, campo:campo, valor:valor},function(data){
            if(data)
            {
                input.after('<span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>');
                setTimeout(function(){
                    $('.form-control-feedback').remove();
                },2000);
            }
        });
    });




    $('#update-position').sortable({
        update : function () {
        var order = $('#update-position').sortable('toArray'); 
        console.log(order)
        var obj = $('#result');
        
        $(obj).fadeOut(function() {}, 
                    function(){ 
                        $.post('<?=URL?>configuracoes/modulos/home/updatePosition',{ordem:order, acao:'atualiza_posicao_produto'},function(data){
                            if(data == true)
                            {
                                $("#dialogResult").html("Atualizado com sucesso");
                                $("#dialogResult").dialog({
                                    autoOpen: true,
                                    buttons: [
                                        {
                                            text: "Ok",
                                            click: function() {
                                                $( this ).dialog( "close" );
                                            }
                                        }
                                    ]
                                });
                            }else
                            {
                                $("#dialogResult").html(data);
                                $("#dialogResult").dialog({
                                    autoOpen: true,
                                    buttons: [
                                        {
                                            text: "Ok",
                                            click: function() {
                                                $( this ).dialog( "close" );
                                            }
                                        }
                                    ]
                                });
                            }
                            
                        });
                        $(obj).fadeIn(); 
                    }
                ); //EXIBE MENSAGEM DE ERRO
                /*setTimeout(function(){ $(obj).fadeOut(function() {}, 
                    function(){ $(obj).html(' '); $(obj).fadeIn(); }
                ); }, 4000); //EXIBE O VALOR QUE FOI DIGITADO*/
        }
    });
    $( "#update-position" ).disableSelection();
    $('.ui-icon-minus').trigger('click')
});




</script>