                </div>
            </div>
            
<!--             <a href="<?=URL?>acesso_negado" data-module="50" data-title="modulo 1" class="openTab">modulo 1</a>
            <a href="<?=URL?>acesso_negado" data-module="52" data-title="modulo 2" class="openTab">modulo 2</a>
            <a href="<?=URL?>pagina" data-module="50" class="openTab">modulo 1.1</a>
            <a href="javascript:void(0)" data-module="50" class="closeTab">fechar modulo 1</a>
            <a href="javascript:void(0)" data-module="52" class="closeTab">fechar modulo 2</a> -->

        </div>
        <?php
        require_once('menu.phtml');
        ?>
    </div><!--wrap-->
    <div id="previousTab" style="display:none">
    </div>
</body>

</html>