<!DOCTYPE html>
<html lang="pt-br" ng-app>
<head>
    <meta charset="utf-8">
    <!--[if lt IE 9]>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <![endif]-->
    <title><?=$titlePage?> - Sistema de Automação Comercial</title>
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    
    <link rel="stylesheet" type="text/css" href="<?=URL?>skin/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="<?=URL?>skin/css/normalize.css" />
    <link rel="stylesheet" type="text/css" href="<?=URL?>skin/css/animate.css" />
    <link rel="stylesheet" type="text/css" href="<?=URL?>skin/css/main.css" />
    <link rel="stylesheet" type="text/css" href="<?=URL?>skin/css/large_desktops.css" />
    <link rel="stylesheet" type="text/css" href="<?=URL?>skin/css/desktops.css" />
    <link rel="stylesheet" type="text/css" href="<?=URL?>skin/css/tablets.css" />
    <link rel="stylesheet" type="text/css" href="<?=URL?>skin/css/extra_small_devices.css" />
    <link rel="stylesheet" type="text/css" href="<?=URL?>skin/js/kendoui/css/kendo.common-material.min.css" />
    <link rel="stylesheet" href="<?=URL?>skin/js/kendoui/css/kendo.default.min.css" />
    

    <meta name="robots" content="noindex, nofollow" />
    <!--[if IE]>
        <link rel="shortcut icon" href="img/favicon.ico">
    <![endif]-->
    <link rel="icon" href="<?=URL?>skin/img/favicon.png" />
    

    <script type="text/javascript" src="<?=URL?>skin/js/angular.min.js"></script>
    <script type="text/javascript" src="<?=URL?>skin/js/jquery-1.11.3.min.js"></script>
    <script type="text/javascript" src="<?=URL?>skin/js/bootstrap.min.js"></script>
    
    <script type="text/javascript" src="<?=URL?>skin/js/main.js"></script>
    <script type="text/javascript" src="<?=URL?>skin/js/freewall.js"></script>
    <script src="<?=URL?>skin/js/kendoui/js/kendo.all.min.js"></script>

    <script src="<?=URL?>skin/js/nanobar.js"></script>
    <script>
        var url = "<?=URL?>";
    </script>
</head>