<?php require_once('head.phtml');?>
<body>
    <div id="wrap" >
        <header class="header">
        <div class="top">
            <figure class="logo">
                <img src="<?=URL?>skin/img/logo/logo.png">
            </figure>


            <div class="user dropdown">
                <a href="" class="btn btn-default dropdown-toggle" id="dropdownMenu1" data-toggle="dropdown">
                    <figure>
                        <img src="<?=URL?>skin/img/imagens/1439113442_Client_Male_Light.png">
                    </figure>
                    <p class="username">Nome do usuário</p>
                </a>
                <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu1">
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li><a href="#">Separated link</a></li>
                </ul>
            </div>
          </div>
            <nav class="navbar navbar-default">
              <div class="container-fluid">
                  <!-- Brand and toggle get grouped for better mobile display -->
                  <div class="navbar-header">
                      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                          <span class="sr-only">Toggle navigation</span>
                          <span class="icon-bar"></span>
                          <span class="icon-bar"></span>
                          <span class="icon-bar"></span>
                      </button>
                      <a class="navbar-brand" href="#">Dashboard <span class="glyphicons glyphicons-stats"></span></a>
                  </div>

                  <!-- Collect the nav links, forms, and other content for toggling -->
                  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                      <ul class="nav navbar-nav">
                          <li ><a href="<?=URL?>funcionarios"><span class="glyphicons glyphicons-group"></span>Funcionários</a></li>
                          <li ><a href="" >Fornecedor</a></li>
                          <li ><a href="<?=URL?>produtos">Produto</a></li>
                          <li ><a href="" >Venda</a></li>
                          <li ><a href="">Caixa</a></li>
                          <li ><a href=""><span class="glyphicons glyphicons-cargo"></span>Estoque</a></li>
                          <li ><a href="">Relatórios</a></li>
                          <li ><a href=""><span class="glyphicons glyphicons-cogwheels"></span>Configurações</a></li>
                          
                      </ul>
                  </div><!-- /.navbar-collapse -->
              </div><!-- /.container-fluid -->
            </nav>
        </header>

    
<ol class="breadcrumb">
    <li><a href="#">Home</a></li>
    <li><a href="#">Library</a></li>
    <li class="active">Data</li>
</ol>
        <div class="wrap-content">

            <div class="demo-section k-header">
                <div id="tabstrip">