<?php require_once('head.phtml');?>
<body>
    <div id="wrap" >
        <header class="header">
            <div class="top">
                <figure class="logo">
                    <img src="<?=URL?>skin/img/logo/logo.png">
                </figure>


                <div class="user dropdown">
                      <a href="" class="btn btn-default dropdown-toggle" id="dropdownMenu1" data-toggle="dropdown">
                          <figure>
                              <img src="<?=URL?>skin/img/imagens/perfil-icone.png">
                          </figure>
                          <p class="username">Nome do usuário</p>
                      </a>
                      <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu1">
                          <li><a href="#">Sair</a></li>
                          <li><a href="#">Logoff</a></li>
                      </ul>
                  </div>
                </div>
                <nav class="navbar navbar-default">
                    <div class="container-fluid">
                        <!-- Brand and toggle get grouped for better mobile display -->
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <a class="navbar-brand" href="<?=URL?>"><span class="glyphicons glyphicons-show-thumbnails"></span><p>Dashboard</p></a>
                        </div>

                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <ul class="nav navbar-nav">
                                <li class="dropdown "><a href="<?=URL?>funcionarios" class="dropdown-toggle active" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicons glyphicons-group"></span><p>Funcionários</p></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="<?=URL?>funcionarios/home">Gerenciar Funcionários</a></li>
                                    </ul>
                                </li>
                               
                               <li class="dropdown "><a href="<?=URL?>fornecedores" class="dropdown-toggle active" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicons glyphicons-handshake"></span><p>fornecedores</p></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="<?=URL?>fornecedores/home">Gerenciar Fornecedores</a></li>
                                    </ul>
                                </li>
                                
                                <li class="dropdown "><a href="<?=URL?>produtos" class="dropdown-toggle active" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicons glyphicons-package"></span><p>produtos</p></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="<?=URL?>produtos/home">Gerenciar Produtos</a></li>
                                    </ul>
                                </li>
                                <li ><a href="<?=URL?>vendas"><span class="glyphicons glyphicons-notes"></span><p>Vendas</p></a></li>
                                <li ><a href="<?=URL?>caixa"><span class="glyphicons glyphicons-calculator"></span><p>Caixa</p></a></li>
                                <li ><a href="<?=URL?>estoque"><span class="glyphicons glyphicons-cargo"></span><p>Estoque</p></a></li>
                                <li ><a href="<?=URL?>relatorios"><span class="glyphicons glyphicons-stats"></span><p>Relatórios</p></a></li>
                                <li ><a href="<?=URL?>configuracoes"><span class="glyphicons glyphicons-cogwheels"></span><p>Configurações</p></a></li>
                            </ul>
                        </div><!-- /.navbar-collapse -->
                    </div><!-- /.container-fluid -->
                </nav>
            </header>
            
        <div class="wrap-content">

      