<div class="menu-container animated fadeOutDown">
    <nav class="navbar-menu">
        <ul id="freewall" class="free-wall">
            <li ><a href="<?=URL?>home/page" class="brick box1" data-module="0" data-title="Home"><figure><img src="<?=URL?>skin/img/imagens/1439164733_Home.png"></figure>Home</a></li>
            <li ><a href="" class="brick box2 inactive"><figure><img src="<?=URL?>skin/img/imagens/1439113161_provider.png"></figure>Fornecedor</a></li>
            <li ><a href="<?=URL?>produtos" class="brick box3" data-module="2" data-title="Produtos"><figure><img src="<?=URL?>skin/img/imagens/benchmarking.png"></figure>Produto</a></li>
            <li ><a href="" class="brick box1" data-module="2" data-title="Venda"><figure><img src="<?=URL?>skin/img/imagens/1439113094_dollar__.png"></figure>Venda</a></li>
            <li ><a href="" class="brick box5"><figure><img src="<?=URL?>skin/img/imagens/electronic_billing_machine.png"></figure>Caixa</a></li>
            <li ><a href="" class="brick box6"><figure><img src="<?=URL?>skin/img/imagens/1439113073_inventory-maintenance.png"></figure>Estoque</a></li>
            <li ><a href="<?=URL?>funcionarios" class="brick box3" data-module="1" data-title="Funcionários"><figure><img src="<?=URL?>skin/img/imagens/1439113228_people.png"></figure>Funcionários</a></li>
            <li ><a href="" class="brick box1"><figure><img src="<?=URL?>skin/img/imagens/bids_and_budget.png"></figure>Relatórios</a></li>
            <li ><a href="" class="brick box2"><figure><img src="<?=URL?>skin/img/imagens/utility.png"></figure>Utilitários</a></li>
            <li ><a href="" class="brick box4"><figure><img src="<?=URL?>skin/img/imagens/config2.png"></figure>Configurações</a></li>
        </ul>   
    </nav>
</div>
    
<div id="nav-icon3">
    <span></span>
    <span></span>
    <span></span>
    <span></span>
</div>