<div class="container">
    <div class="page-header">
      <h1>Funcionários <small>Cadastro</small></h1>
    </div>
    <form action="">
        <div class="panel panel-default">
            <div class="panel-heading">Dados Gerais</div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-xs-6 col-md-3">
                        <label for="foto" class="thumbnail inputFoto">
                            <img src="<?=URL?>skin/img/imagens/1439113161_provider.png" alt="...">
                            <input type="file" name="foto" id="foto">
                        </label>
                    </div>
                </div>
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Nome</span>
                    <input type="text" class="form-control" placeholder="Nome" aria-describedby="basic-addon1">
                </div>
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Sobrenome</span>
                    <input type="text" class="form-control" placeholder="Sobrenome" aria-describedby="basic-addon1">
                </div>
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Data de nascimento</span>
                    <input type="text" class="form-control" placeholder="Data de nascimento" aria-describedby="basic-addon1">
                </div>

                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Sexo</span>
                    <select class="form-control">
                        <option value="" selected="selected" disabled="disabled">..Selecione..</option>
                        <option value="M">Masculino</option>
                        <option value="F">Feminino</option>
                    </select>
                </div>

                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">RG</span>
                    <input type="text" class="form-control" placeholder="RG" aria-describedby="basic-addon1">
                </div>
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">CPF</span>
                    <input type="text" class="form-control" placeholder="CPF" aria-describedby="basic-addon1">
                </div> 
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Estado Civil</span>
                    <select class="form-control">
                        <option value="" selected="selected" disabled="disabled">..Selecione..</option>
                        <option value="Casado">Casado(a)</option>
                        <option value="Solteiro">Solteiro(a)</option>
                        <option value="Divorciado">Divorciado(a)</option>
                        <option value="Viúvo">Viúvo(a)</option>
                    </select>
                </div>
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Escolaridade</span>
                    <select class="form-control">
                        <option value="" selected="selected" disabled="disabled">..Selecione..</option>
                        <option value="Casado">Ensino Fundamental Incompleto</option>
                        <option value="Solteiro">Ensino Fundamental Completo</option>
                        <option value="Divorciado">Ensino Médio Incompleto</option>
                        <option value="Viúvo">Ensino Médio Completo</option>
                        <option value="Viúvo">Ensino Superior Incompleto</option>
                        <option value="Viúvo">Ensino Superior Completo</option>
                    </select>
                </div>
            </div>
        </div>


        <div class="panel panel-default">
            <div class="panel-heading">Endereço</div>
            <div class="panel-body">
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Logradouro</span>
                    <input type="text" class="form-control" placeholder="Lougradouro" aria-describedby="basic-addon1">
                </div>
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Cidade</span>
                    <input type="text" class="form-control" placeholder="Cidade" aria-describedby="basic-addon1">
                </div>
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">UF</span>
                    <select class="form-control">
                        <option value="" selected="selected" disabled="disabled">..Selecione..</option>
                        <option value="M">SP</option>
                        <option value="F">RJ</option>
                    </select>
                </div>
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Número</span>
                    <input type="text" class="form-control" placeholder="Número " aria-describedby="basic-addon1">
                </div>

                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Bairro</span>
                    <input type="text" class="form-control" placeholder="bairro" aria-describedby="basic-addon1">
                </div>
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">CEP</span>
                    <input type="text" class="form-control" placeholder="CEP" aria-describedby="basic-addon1">
                </div>
            </div>
        </div><!-- fim panel endereco -->

        <div class="panel panel-default">
            <div class="panel-heading">Contatos</div>
            <div class="panel-body">
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Telefone</span>
                    <input type="text" class="form-control" placeholder="Telefone" aria-describedby="basic-addon1">
                </div>
                
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Celular</span>
                    <input type="text" class="form-control" placeholder="Celular" aria-describedby="basic-addon1">
                </div>
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">E-mail</span>
                    <input type="text" class="form-control" placeholder="E-mail" aria-describedby="basic-addon1">
                </div>
            </div>
        </div>


        <div class="panel panel-default ">
            <div class="panel-heading">Dados Admissionais</div>
            <div class="panel-body">
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Código de Admissão</span>
                    <input type="text" class="form-control" placeholder="Código de Admissão" aria-describedby="basic-addon1">
                </div>
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Cargo</span>
                    <input type="text" class="form-control" placeholder="Cargo" aria-describedby="basic-addon1">
                </div>
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Data De Admissão</span>
                    <input type="text" class="form-control" placeholder="Data De Admissão" aria-describedby="basic-addon1">
                </div>
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Data De Cadastro</span>
                    <input type="text" class="form-control" placeholder="Data De Cadastro" aria-describedby="basic-addon1">
                </div>
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Salário</span>
                    <input type="text" class="form-control" placeholder="Salário" aria-describedby="basic-addon1">
                </div>

                <div class="btn-group pull-right" role="group">
                    <button type="submit" class="btn btn-success">Salvar</button>
                </div>

            </div>
        </div>
    </form>
</div>
