<div class="container">
    <div class="page-header">
      <h1>Funcionários <small>Cadastro</small></h1>
    </div>
    <form action="<?=URL?>funcionarios/home/inserir" method="post" id="form_funcionarios">
        <div class="panel panel-default">
            <div class="panel-heading">Dados Gerais</div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-xs-6 col-md-3">
                        <label for="foto" class="thumbnail inputFoto preview-lg">
                            <div class="thumbnail img-preview preview-lg">
                                <img src="<?=URL?>skin/img/imagens/1439113161_provider.png" id="img_previous">
                            </div>
                            <input type="file" name="foto" id="foto">
                        </label>
                    </div>
                </div>

                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Nome</span>
                    <input type="text" class="form-control" placeholder="Nome" name="nome" >
                </div>
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Sobrenome</span>
                    <input type="text" class="form-control" placeholder="Sobrenome" name="sobrenome">
                </div>
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Data de nascimento</span>
                    <input type="text" class="form-control" placeholder="Data de nascimento" name="dataNascimento">
                </div>

                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Sexo</span>
                    <select class="form-control" name="sexo">
                        <option value="" selected="selected" disabled="disabled">..Selecione..</option>
                        <option value="M">Masculino</option>
                        <option value="F">Feminino</option>
                    </select>
                </div>

                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">RG</span>
                    <input type="text" class="form-control" placeholder="RG" name="rg">
                </div>
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">CPF</span>
                    <input type="text" class="form-control" placeholder="CPF" name="cpf">
                </div> 
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Estado Civil</span>
                    <select class="form-control" name="estadoCivil">
                        <option value="" selected="selected" disabled="disabled">..Selecione..</option>
                        <option value="Casado">Casado(a)</option>
                        <option value="Solteiro">Solteiro(a)</option>
                        <option value="Divorciado">Divorciado(a)</option>
                        <option value="Viúvo">Viúvo(a)</option>
                    </select>
                </div>
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Escolaridade</span>
                    <select class="form-control" name="escolaridade">
                        <option value="" selected="selected" disabled="disabled">..Selecione..</option>
                        <option value="Casado">Ensino Fundamental Incompleto</option>
                        <option value="Solteiro">Ensino Fundamental Completo</option>
                        <option value="Divorciado">Ensino Médio Incompleto</option>
                        <option value="Viúvo">Ensino Médio Completo</option>
                        <option value="Viúvo">Ensino Superior Incompleto</option>
                        <option value="Viúvo">Ensino Superior Completo</option>
                    </select>
                </div>
            </div>
        </div>


        <div class="panel panel-default">
            <div class="panel-heading">Endereço</div>
            <div class="panel-body">

                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">CEP</span>
                    <input type="text" class="form-control" placeholder="CEP" name="cep" id="cep">
                </div>

                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Logradouro</span>
                    <input type="text" class="form-control" placeholder="Lougradouro" name="logradouro" id="rua">
                </div>

                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Número</span>
                    <input type="text" class="form-control" placeholder="Número" name="numero" id="numero">
                </div>
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Complemento</span>
                    <input type="text" class="form-control" placeholder="Complemento" name="complemento" id="complemento">
                </div>

                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Bairro</span>
                    <input type="text" class="form-control" placeholder="Bairro" name="bairro" id="bairro">
                </div>

                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Cidade</span>
                    <input type="text" class="form-control" placeholder="Cidade" name="cidade" id="cidade">
                </div>

                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">UF</span>
                    <select class="form-control" name="estado" id="uf">
                        <option value="" selected="selected" disabled="disabled">..Selecione..</option>
                        <option value="AC">AC - Acre</option>
                        <option value="AL">AL - Alagoas</option>
                        <option value="AP">AP - Amapá</option>
                        <option value="AM">AM - Amazonas</option>
                        <option value="BA">BA - Bahia</option>
                        <option value="CE">CE - Ceará</option>
                        <option value="DF">DF - Distrito Federal</option>
                        <option value="GO">GO - Goiás</option>
                        <option value="ES">ES - Espírito Santo</option>
                        <option value="MA">MA - Maranhão</option>
                        <option value="MT">MT - Mato Grosso</option>
                        <option value="MS">MS - Mato Grosso do Sul</option>
                        <option value="MG">MG - Minas Gerais</option>
                        <option value="PA">PA - Pará</option>
                        <option value="PB">PB - Paraiba</option>
                        <option value="PR">PR - Paraná</option>
                        <option value="PE">PE - Pernambuco</option>
                        <option value="PI">PI - Piauí­</option>
                        <option value="RJ">RJ - Rio de Janeiro</option>
                        <option value="RN">RN - Rio Grande do Norte</option>
                        <option value="RS">RS - Rio Grande do Sul</option>
                        <option value="RO">RO - Rondônia</option>
                        <option value="RR">RR - Roraima</option>
                        <option value="SP">SP - São Paulo</option>
                        <option value="SC">SC - Santa Catarina</option>
                        <option value="SE">SE - Sergipe</option>
                        <option value="TO">TO - Tocantins</option>
                    </select>
                </div>
                
            </div>
        </div><!-- fim panel endereco -->

        <div class="panel panel-default">
            <div class="panel-heading">Contatos</div>
            <div class="panel-body">
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Tipo</span>
                    <select class="form-control" name="estado">
                        <option value="" selected="selected" disabled="disabled">..Selecione..</option>
                        <option value="Fixo">Fixo</option>
                        <option value="Celular">Celular</option>
                    </select>
                </div>
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Telefone</span>
                    <input type="text" class="form-control" placeholder="Telefone" name="telefone">
                </div>
                
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">E-mail</span>
                    <input type="text" class="form-control" placeholder="E-mail" name="">
                </div>
            </div>
        </div>


        <div class="panel panel-default ">
            <div class="panel-heading">Dados Admissionais</div>
            <div class="panel-body">
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Código de Admissão</span>
                    <input type="text" class="form-control" placeholder="Código de Admissão" name="">
                </div>
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Cargo</span>
                    <input type="text" class="form-control" placeholder="Cargo" name="">
                </div>
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Data De Admissão</span>
                    <input type="text" class="form-control" placeholder="Data De Admissão" name="">
                </div>
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Salário</span>
                    <input type="text" class="form-control" placeholder="Salário" name="">
                </div>

                <div class="btn-group pull-right" role="group">
                    <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-ok"></span> Salvar</button>
                </div>

            </div>
        </div>
    </form>
</div>

<script type="text/javascript" src="<?=URL?>skin/js/uploadForm.js"></script>
<link href="<?=URL?>skin/js/croper/cropper.min.css" rel="stylesheet">
<link href="<?=URL?>skin/js/croper/main.css" rel="stylesheet">
<script src="<?=URL?>skin/js/croper/cropper.min.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/jquery.maskedinput.min.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/jquery.validate.js"></script>

<script type="text/javascript">
    
 $(function(){
    $('input[name=dataNascimento]').datepicker({ dateFormat: 'dd/mm/yy',changeMonth: true, changeYear: true,yearRange: "-100:+0" });
    $('input[name=cep]').wvmask('cep')
    $('input[name=numero]').wvmask('numero')
    $('input[name=cpf]').mask('999.999.999-99');
    $('input[name=rg]').mask('99.999.999-9');
    $('#form_funcionarios').validaCep();

    //mascara para telefones de 8 e 9 dígitos
    var maskBehavior = function (val) {
        return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
    },
    options = {onKeyPress: function(val, e, field, options) {
        field.mask(maskBehavior.apply({}, arguments), options);
        }
    };
    $('input[name=telefone]').mask(maskBehavior, options);



    $('#form_funcionarios').uploadImage();
   
    $('#form_funcionarios').submit(function(){
        $('#form_funcionarios').uploadForm({
            'reload':true
        });
        return false;
    });

 })   
</script>