<?php
$template = new Template();
$btnCadastrar = $template->btnCadastrar(URL.'funcionarios/home/cadastrar');
echo $template->actions_buttons($btnCadastrar);
?>
<div class="container">
    <div class="page-header">
      <h1>Funcionários</h1>
    </div>
    <div>
        <br><br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br><br><br><br><br><br><br><br><p>conteudo</p>
        <br><br><br><br><br><br><br><br><p>conteudo</p>
        <br><br><br><br><br><br><br><p>fim</p>
    </div>
</div>