<div class="container">
    <?php
       $btnVoltar = $this->templateFactory->getButton("voltar",array('href'=>URL.'produtos/gerenciar/precos'));
        echo $this->templateFactory->getButton("actions_buttons",array('buttons'=>$btnVoltar));    ?>
    <div class="page-header">
      <h1>Tabela de preços<small> Cadastro</small></h1>
    </div>
    <form action="<?=URL?>produtos/marcas/gerenciar/inserir" method="post" id="form_marca">
        <div class="panel panel-default">
            <div class="panel-heading">Dados Gerais</div>
            <div class="panel-body">

                <div class="form-group">
                    <label>Definir como padrão</label>
                    <input type="checkbox" name="preco" >
                </div>
               
                <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-12">
                    <label>Preço</label>
                    <input type="text" class="form-control" placeholder="Preço" name="preco" >
                </div>

                <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-12">
                    <p>Período</p>
                    <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-6">
                        <input type="text" class="form-control" placeholder="De quando" name="de" >
                    </div>
                    <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-6">
                        <input type="text" class="form-control" placeholder="Até quando" name="ate" >
                    </div>
                </div>


                <div class="btn-group pull-right" role="group">
                    <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-ok"></span> Salvar</button>
                </div>
            </div>
        </div>
    </form>
</div>

<script type="text/javascript" src="<?=URL?>skin/js/uploadForm.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/produtos/marcas/cadastrar.js"></script>

<script>
$(function(){
    $( "input[name=de]" ).datepicker({
        defaultDate: "+1w",
        dateFormat: 'dd/mm/yy',
        changeMonth: true, 
        changeYear: true,
        yearRange: "-0:+1",
        numberOfMonths: 2,
        onClose: function( selectedDate ) {
            $( "input[name=ate]" ).datepicker( "option", "minDate", selectedDate );
        }
    });
    $( "input[name=ate]" ).datepicker({
        defaultDate: "+1w",
        dateFormat: 'dd/mm/yy',
        changeMonth: true, 
        changeYear: true,
        yearRange: "-0:+1", 
        numberOfMonths: 2,
        onClose: function( selectedDate ) {
            $( "input[name=de]" ).datepicker( "option", "maxDate", selectedDate );
        }
    });
})
</script>