<div class="container">
	
	<div id="fullscreen" class="fullscreenCheckout hide">
		
		<section id="telaAbrirCaixa" class="hide">
			<div class="containercheckoutAbrirCaixa">
				<figure class="center-block figureLogo thumbnail">
		      		<img src="<?=URL?>skin/img/imagens/logosupermercado.png" alt="">
				</figure>
				<div class="containerHora">
					<output id="hora" class="hora"></output>				
				</div>	
				<div class="containerData">
					<output id="data" class="data"></output>
				</div>
				<form class="form" action="<?=URL?>caixa/checkout/gerenciar/abrircaixa" id="form_abrirCaixa">
					<div class="form-group">
					    <label>Saldo Inicial em caixa</label>
					    <input type="text" class="form-control" placeholder="Saldo" name="saldoinicial">
					</div>
					<button type="submit" class="btn btn-primary pull-right">Abrir caixa</button>
				</form>
			</div>
		</section>




		<section class="container-fluid hide" id="telaVenda">
		    <div class="row telaVenda">
		        <div class="col-sm-3 col-md-2 sidebarcheckout">
		          	<figure class="center-block figureLogo thumbnail">
			      		<img src="<?=URL?>skin/img/imagens/logosupermercado.png" alt="">
					</figure>
					<div class="containerHora">
						<output id="hora" class="hora"></output>
					</div>	
					<div class="containerData">
						<output id="data" class="data"></output>
					</div>
		          	<ul class="nav nav-sidebar">
		            	<li><a href="javascript:void(0)" class="openfullscreen">Tela cheia</a></li>
		          	</ul>
		          	<div class="row">
					  	<div class="col-xs-12 col-md-12">
					  		<?php
                          $fotoFunc = ($usuario->getFuncionario()->getFoto() != '') ? URL.'skin/uploads/funcionarios/p/'.$usuario->getFuncionario()->getFoto() : URL.'skin/img/imagens/perfil-icone.png';
                          ?>
	                        <div class="thumbnail">
					      		<img src="<?=$fotoFunc?>" alt="..." class="img-circle" style="width: 100px; margin:auto; display: table;">
					      		<div class="caption text-center">
					      			<p><?=$usuario->getFuncionario()->getNome().' '.$usuario->getFuncionario()->getSobrenome()?></p>
					      		</div>
						  	</div>
					  	</div>
					</div>
		        </div>
		        <div class="col-sm-4 col-sm-offset-2 col-md-4 col-md-offset-2 bg-primary containerProdutos">
		          	<h1 class="page-header">
		          		PRODUTOS
			      		<label class="pull-right checkoutListAutomatic">
				       		<small>Listagem automática</small>
				       		<input type="checkbox" name="automaticList" checked="checked">
				      	</label>
		          	</h1>
					<div class="row">
						<div class="col-xs-12 col-md-12 col-sm-12 col-lg-12">


							<div>
								<!-- Nav tabs -->
								<ul class="nav nav-tabs" role="tablist">
								    <li role="presentation" class="active"><a href="#porcodigo" aria-controls="porcodigo" role="tab" data-toggle="tab">Por código de barras</a></li>
								    <li role="presentation"><a href="#pordescricao" aria-controls="pordescricao" role="tab" data-toggle="tab">Por descrição</a></li>
								</ul>

								<!-- Tab panes -->
								<div class="tab-content">
								    <div role="tabpanel" class="tab-pane active" id="porcodigo">
										<div class="form-group col-xs-12 col-md-12 col-sm-12 col-lg-12">
						                    <label>Código de barras</label>
						                    <input type="text" class="form-control" name="codigobarras" maxlength="13" placeholder="Código de barras">
						                </div>
								    </div>
								    <div role="tabpanel" class="tab-pane" id="pordescricao">
								    	<div class="form-group col-xs-12 col-md-12 col-sm-12 col-lg-12">
						                    <label>Produtos</label>
						                    <select name="listaproduto" class="form-control">
						                    	<option value="" selected="selected" disabled="disabled"></option>
						                        <?php if(!empty($produtos)):?>
						                        <?php foreach ($produtos as $produtoestoque):?>
						                        <option value="<?=$produtoestoque->getProduto()->getId()?>"><?=$produtoestoque->getProduto()->getNome()?></option>
						                        <?php endforeach;?>
						                        <?php endif;?>
						                    </select>
						                </div>

								    </div>
								</div>
								
							</div>


							<section class="containerProdutoUnitario hide">
								<div class="listProducts">
									<div class="item">
										<h3 id="nomeProduto"></h3>
										<div class="col-xs-12 col-md-12">
										    <div class="thumbnail">
										      	<img src="" alt="" id="fotoProduto">
										    </div>
										</div>
									</div>
								</div>
								<div class="subtotal">
									<div class="form-group">
									    <label class="col-sm-8 control-label">QUANTIDADE</label>
									    <div class="col-sm-4">
									      	<input type="text" class="form-control" value="1,0" min="1" name="quantidade" id="quantidade">
									    </div>
									</div>
									<div class="form-group">
									    <h3 class="col-sm-8 control-label">VALOR UNITÁRIO</h3>
									    <div class="col-sm-4">
									      	<h3 id="valorUnitario"></h3>
									      	<input type="hidden" value="1" name="valorUnitario" class="form-control">
									    </div>
									</div>
									<div class="form-group">
									    <h3 class="col-sm-5 control-label">SUBTOTAL</h3>
									    <div class="col-sm-7">
									      	<h2 id="subtotalProduto" class="text-right"></h2>
									    </div>
									</div>

									<div class="btn-group pull-right">
									  	<button type="button" class="btn btn-success btnListar">Listar</button>
									</div>
								</div>
							</section>
							<a href="#" id="produtoUnitario"></a>
						</div>
					</div>
		        </div>




				<div class="col-sm-4 col-sm-offset-2 col-md-4 col-md-offset-2 bg-primary hide containerPagarCompra">
					<h1 class="page-header">PAGAMENTO</h1>
					<div class="row">
						<div class="col-sm-6 col-md-4">
						    <a href="javascript:void(0)" class="thumbnail btnformaPagamento" type="DINHEIRO">
						    	<figure class="text-center">
						    		<span class="glyphicons glyphicons-money"></span>
						    	</figure>
						      	
						      	<div class="caption">
						        	<h5 class="text-center">DINHEIRO</h5>
						      	</div>
						    </a>
						</div>

						<div class="col-sm-6 col-md-4">
						    <a href="javascript:void(0)" class="thumbnail btnformaPagamento" type="CARTAODEBITO">
						    	<figure  class="text-center">
						    		<span class="glyphicons glyphicons-credit-card"></span>
						    	</figure>
						      	
						      	<div class="caption">
						        	<h5 class="text-center">CARTÃO DE DÉBITO</h5>
						      	</div>
						    </a>
						</div>

						<div class="col-sm-6 col-md-4">
						    <a href="javascript:void(0)" class="thumbnail btnformaPagamento" type="CARTAOCREDITO">
						    	<figure class="text-center">
						    		<span class="glyphicons glyphicons-credit-card"></span>
						    	</figure>
						      	
						      	<div class="caption">
						        	<h5 class="text-center">CARTÃO DE CRÉDITO</h5>
						      	</div>
						    </a>
						</div>
					</div>
				</div>


				<div class="col-sm-4 col-sm-offset-2 col-md-4 col-md-offset-2 bg-primary hide containerFinalizarCompra">
					<h2 class="page-header">FINALIZANDO PAGAMENTO</h2>
					<div class="row">
						<div class="form-group">
						    <h3 class="col-sm-5 control-label">SUBTOTAL</h3>
						    <div class="col-sm-7">
						      	<h2 id="subtotalProduto" class="text-right"></h2>
						      	<input type="text" name="subtotal" value="">
						    </div>
						</div>
						<div class="col-sm-12 col-md-12 hide" id="tipo_DINHEIRO">
							<div class="wel">
							    <h3><small>PAGAMENTO ESCOLHIDO: </small> DINHEIRO</h3>
							    
							    <div class="form-group">
								    <label>Valor pago</label>
								    <input type="text" class="form-control" placeholder="Digite o valor recebido" name="valorrecebido">
								</div>

								<div class="form-group">
								    <label>Troco</label>
								    <p class="form-control" id="troco"></p>
								</div>
							</div>
						</div>

						<div class="col-sm-12 col-md-12 hide" id="tipo_CARTAODEBITO">
							<div class="wel">
							    <h3><small>PAGAMENTO ESCOLHIDO: </small> CARTÃO DE DÉBITO</h3>
								<div class="form-group">
								    <label>Status da operação</label>
								    <p class="form-control">Aguardando cartão</p>
								</div>
							</div>
						</div>

						<div class="col-sm-12 col-md-12 hide" id="tipo_CARTAOCREDITO">
							<div class="wel">
							    <h3><small>PAGAMENTO ESCOLHIDO: </small> CARTÃO DE CRÉDITO</h3>
							    <div class="form-group">
								    <label>Status da operação</label>
								    <p class="form-control">Aguardando cartão</p>
								</div>
							</div>
						</div>

						<div class="btn-group pull-right">
							<button type="button" class="btn btn-success btnFinalizar">Finalizar</button>
						</div>
					</div>
				</div>







		        <div class="col-sm-4 col-sm-offset-2 col-md-6 col-md-offset-6 containerListaCompra">
		          	<h1 class="page-header">LISTA DA COMPRA</h1>
					<div class="row">
					  	<div class="col-xs-12 col-md-12 col-sm-12 col-lg-12">
						  	<table class="table table-striped" cellspacing="0" id="listcarrinho">
							    <thead>
							        <tr>
							        	<th>#</th>
							        	<th>Item</th>
							        	<th>QTDE.</th>
							        	<th>R$ (Unid.)</th>
							        </tr>
							    </thead>
							    <tbody>
							    	
							    </tbody>
							</table>
						</div>
					</div>
					<div class="row">
						<div class="well">TOTAL A PAGAR <small>R$</small> <span id="subtotal"></span></div>
						<div class="btn-group btn-lg">
							<button class="cancelarcompra btn btn-danger">CANCELAR COMPRA <span class="glyphicon glyphicon-remove-circle"></span></button>
							<button class="pagarcompra btn btn-primary ">PAGAR COMPRA <span class="glyphicons glyphicons-usd"></span></button>
						</div>
					</div>
		        </div>


				

		    </div>
	    </section>


	</div>

	<div id="telaPrincipal" class="">
		<div class="containercheckoutInicio">
			<figure class="center-block figureLogo thumbnail">
	      		<img src="<?=URL?>skin/img/imagens/logosupermercado.png" alt="">
			</figure>
			<div class="containerHora">
				<output id="hora"></output>
			</div>	
			<div class="containerData">
				<output id="data"></output>
			</div>
			<a href="javascript:void(0)" class="openfullscreen">Clique para iniciar <span class="glyphicons glyphicons-hand-up"></span></a>
			<!-- <a href="#" class="exitfullscreen" style="display: none">Click to exit fullscreen</a> -->
		</div>
	</div>




</div>
<script type="text/javascript" src="<?=URL?>skin/js/jquery.maskMoney.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/jquery.validate.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/fullscreen/jquery.fullscreen.min.js"></script>
<script type="text/javascript">
	$(function() {
		
		$("input[name=valorrecebido]").maskMoney({decimal:",",thousands:""});
		$('input[name=saldoinicial], input[name=quantidade]').wvmask('numero');

		var isRegisteredMachine = false;
		function checkRegiteredMachine(){
			$.post(url+'caixa/checkout/gerenciar/checkmachine', {}, function(data) {
				if(data == true){
					isRegisteredMachine = true;
					//$('#fullscreen').html($('#telaPrincipal').clone().removeClass('hide'))
				}else
				{
					//$('#fullscreen').html('<div class="alert alert-warning text-center" role="alert"><h3>Esta máquina não está registrada para realizar esta operação!</h3></div>');
					isRegisteredMachine = data;
				}
			});
		}
		checkRegiteredMachine()

		$('#form_abrirCaixa').on('submit', function(event) {
			event.preventDefault();
			$.ajax({
				url: $(this).attr('action'),
				type: 'POST',
				//dataType: 'default: Intelligent Guess (Other values: xml, json, script, or html)',
				data: $(this).serialize(),
			})
			.done(function(data) {
				console.log(data)
				$('#telaAbrirCaixa').addClass('hide')
				$('#telaVenda').removeClass('hide')
			})
			.fail(function(data) {
				$.notify({
                	icon: 'glyphicons glyphicons-alert',
					message: data.responseText,
				},{
					type: "warning",
					placement: {
						from: "top",
						align: "right"
					}
				});
			})
			
	        return false;
		});
		


		// check native support
		$('#support').text($.fullscreen.isNativelySupported() ? 'supports' : 'doesn\'t support');

		// open in fullscreen
		$(document).on('click', '.openfullscreen', function() {
			checkRegiteredMachine()
			if(isRegisteredMachine === true){
				$('.fullscreenCheckout').removeClass('hide').addClass('active')
				$('#telaPrincipal').addClass('hide')
				$('#telaAbrirCaixa').removeClass('hide')
				// $('#fullscreen').fullscreen();
				$('body').fullscreen();
				console.log('passou')
			}else
				$.notify({
                	icon: 'glyphicons glyphicons-alert',
					message: isRegisteredMachine,
				},{
					type: "warning",
					placement: {
						from: "top",
						align: "right"
					}
				});
			return false;
		});

		// exit fullscreen
		$('#fullscreen .exitfullscreen').click(function() {
			$.fullscreen.exit();
			return false;
		});

		// document's event
		$(document).bind('fscreenchange', function(e, state, elem) {
			// if we currently in fullscreen mode
			if ($.fullscreen.isFullScreen()) {
				$('#fullscreen .openfullscreen').hide();
				$('#fullscreen .exitfullscreen').show();
			} else {
				$('#fullscreen .openfullscreen').show();
				$('#fullscreen .exitfullscreen').hide();
			}

			$('#state').text($.fullscreen.isFullScreen() ? '' : 'not');
		});




		jQuery.multipress = function (keys, handler) {
		    'use strict';

		    if (keys.length === 0) {
		        return;
		    }

		    var down = {};
		    jQuery(document).keydown(function (event) {
		        down[event.keyCode] = true;
		    }).keyup(function (event) {
		        // Copy keys array, build array of pressed keys
		        var remaining = keys.slice(0),
		            pressed = Object.keys(down).map(function (num) { return parseInt(num, 10); }),
		            indexOfKey;
		        // Remove pressedKeys from remainingKeys
		        jQuery.each(pressed, function (i, key) {
		            if (down[key] === true) {
		                down[key] = false;
		                indexOfKey = remaining.indexOf(key);
		                if (indexOfKey > -1) {
		                    remaining.splice(indexOfKey, 1);
		                }
		            }
		        });
		        // If we hit all the keys, fire off handler
		        if (remaining.length === 0) {
		            handler(event);
		        }
		    });
		};
		// $(document).bind('keydown', function(event) {
		// 	if(event.keyCode == 122)
		// 		$('#fullscreen').fullscreen();
		// });

		// jQuery.multipress([18], function () { 
		// 	if ($.fullscreen.isFullScreen()) {
		// 		alert('está no fullscreen')
		// 	}else{
		// 		alert('não está no fullscreen')
		// 	} 
		// })




		

	});
</script>
<script type="text/javascript">
	jQuery(window).load(function($){
		atualizaRelogio();
	});
</script>
<script>
	function atualizaRelogio(){ 
		var momentoAtual = new Date();
		
		var vhora = momentoAtual.getHours();
		var vminuto = momentoAtual.getMinutes();
		var vsegundo = momentoAtual.getSeconds();
		
		var vdia = momentoAtual.getDate();
		var vmes = momentoAtual.getMonth() + 1;
		var vano = momentoAtual.getFullYear();

		var Dia = momentoAtual.getDay(); 
		var Mes = momentoAtual.getUTCMonth();

		arrayDia = new Array();
		   arrayDia[0] = "Domingo";
		   arrayDia[1] = "Segunda-Feira";
		   arrayDia[2] = "Terça-Feira";
		   arrayDia[3] = "Quarta-Feira";
		   arrayDia[4] = "Quinta-Feira";
		   arrayDia[5] = "Sexta-Feira";
		   arrayDia[6] = "Sabado";
		 
		var arrayMes = new Array();
		   arrayMes[0] = "Janeiro";
		   arrayMes[1] = "Fevereiro";
		   arrayMes[2] = "Março";      
		   arrayMes[3] = "Abril";
		   arrayMes[4] = "Maio";
		   arrayMes[5] = "Junho";
		   arrayMes[6] = "Julho";
		   arrayMes[7] = "Agosto";
		   arrayMes[8] = "Setembro";
		   arrayMes[9] = "Outubro";
		   arrayMes[10] = "Novembro";
		   arrayMes[11] = "Dezembro";




		if (vdia < 10){ vdia = "0" + vdia;}
		if (vmes < 10){ vmes = "0" + vmes;}
		if (vhora < 10){ vhora = "0" + vhora;}
		if (vminuto < 10){ vminuto = "0" + vminuto;}
		if (vsegundo < 10){ vsegundo = "0" + vsegundo;}

		dataFormat = arrayDia[Dia] + ", " + vdia + " de " + arrayMes[Mes] + " de " + vano;
		horaFormat = vhora + " : " + vminuto + " : " + vsegundo;

		
	
		$('.data').html('<h4 class="text-center">'+dataFormat+'</h4>');
		$('.hora').html('<h4 class="text-center">'+horaFormat+'</h4>');

		// document.getElementById("data").innerHTML = '<p class="text-center">'+dataFormat+'</p>';
		// document.getElementById("hora").innerHTML = '';
		setTimeout("atualizaRelogio()",1000);
	}


</script>

<script type="text/javascript" src="<?=URL?>skin/js/uploadForm.js"></script>
<!-- <script type="text/javascript" src="<?=URL?>skin/js/suprimentos/requisicoes/cadastrar.js"></script> -->
<script>
$(function(){
	var tabactive = '#porcodigo';

	$('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
	  	tabactive = e.target.hash; // newly activated tab
	  	//e.relatedTarget // previous active tab

	  	if(e.relatedTarget.hash == '#porcodigo')
	  	{
	  		$('input[name=codigobarras]').val('');
	  	}
	})


	function getProduto(tipo, value){
		$.ajax({
			url: url+'caixa/checkout/gerenciar/consultaProduto',
			type: 'POST',
			dataType: 'json',
			data: {tipo: tipo, value:value},
		})
		.done(function(data) {
			console.log(data);
			if(data != false)
			{
				$('#fotoProduto').attr('src',data.foto);
				$('#nomeProduto').html(data.nome);
				$('#valorUnitario').html(data.precoFormatado);
				$('input[name=valorUnitario]').val(data.preco);
				calcSubtotalProduto($('input[name=quantidade]').val(), data.preco)
				$('.containerProdutoUnitario').removeClass('hide');
				//window.location.href='#produtoUnitario';
				var target_offset = $("#produtoUnitario").offset();
		        var target_top = target_offset.top;
		        $('.containerProdutos').animate({ scrollTop: target_top }, 500);
			}
		})
		.fail(function(data) {
			console.log("error");
			console.log(data)
		})	
	}


	$('input[name=codigobarras]').bind("change paste keyup", function() {
		var value = '';
		var tipo = 'porcodigo';
		var quantidade = 1;
		
		if(tabactive == '#porcodigo')
		{
			tipo = 'porcodigo';
			value = $('input[name=codigobarras]').val();
			quantidade = $('input[name=quantidade]').val();
			if($('input[name=codigobarras]').val().length == 13)
			{
				getProduto(tipo, value, quantidade);
			}
		}
	});


	$('select[name=listaproduto]').bind("change paste keyup", function() {
		var value = '';
		var tipo = 'pordescricao';
		var quantidade = 1;

		if(tabactive == '#pordescricao'){
			tipo = 'pordescricao';
			value = $('select[name=listaproduto]').val();
			quantidade = $('input[name=quantidade]').val();
			getProduto(tipo, value, quantidade);
		}

	});


	$('.btnAddProduto').on('click', function(event) {
	});
	Number.prototype.formatMoney = function(c, d, t){
	var n = this, c = isNaN(c = Math.abs(c)) ? 2 : c, d = d == undefined ? "," : d, t = t == undefined ? "." : t, s = n < 0 ? "-" : "", i = parseInt(n = Math.abs(+n || 0).toFixed(c)) + "", j = (j = i.length) > 3 ? j % 3 : 0;
	   return s + (j ? i.substr(0, j) + t : "") + i.substr(j).replace(/(\d{3})(?=\d)/g, "$1" + t) + (c ? d + Math.abs(n - i).toFixed(c).slice(2) : "");
	};

	function calcSubtotalProduto(qtd, vUnit){
		qtd = qtd.replace(".","");
        qtd = qtd.replace(",",".");
        qtd = parseFloat(qtd);
		var subtotalProd = qtd*vUnit;
		subtotalProd = subtotalProd.formatMoney(2, ',', '.');
		$('#subtotalProduto').html('R$ '+subtotalProd);

	}


	$('#quantidade').bind('change paste keyup', function(event) {
		calcSubtotalProduto($(this).val(), $('input[name=valorUnitario]').val())
	});

	$('input[name=valorUnitario]').bind('change paste keyup', function(event) {
		calcSubtotalProduto($('input[name=quantidade]').val(), $(this).val())
	});
	

	$(document).on('click','.btnListar', function(){
		var quantidade = $('input[name=quantidade]').val()
		var idproduto = $('select[name=listaproduto]').val();

		$.ajax({
			url: url+'caixa/checkout/gerenciar/addProdutoListaVenda',
			type: 'POST',
			dataType: 'json',
			data: {quantidade: quantidade, idproduto:idproduto},
		})
		.done(function(data) {
			console.log(data);
			listarProdutosCarrinho();
		})
		.fail(function(data) {
			console.log("error");
			console.log(data)
		});

	});

	function listarProdutosCarrinho()
	{
		$('#listcarrinho tbody').html('');
		$.ajax({
			url: url+'caixa/checkout/gerenciar/listarCarrinho',
			type: 'POST',
			dataType: 'json',
			data: {},
		})
		.done(function(data) {
			console.log(data)
			$.each(data, function(index, val) {
				var row = 	'<tr>'
					        	+'<td>'+index+'</td>'
					        	+'<td>'+val.item+'</td>'
					        	+'<td>'+val.qtd+'</td>'
					        	+'<td>'+val.preco+'</td>'
					        +'</tr>';
				$('#listcarrinho tbody').append(row);	        
			});
			$('.pagarcompra').removeAttr('disabled')
			//exibe o subtotal
			consultaSubtotal();
		})
		.fail(function(data) {
			console.log("error");
			console.log(data)
		})
	}

	function consultaSubtotal()
	{
		$.ajax({
			url: url+'caixa/checkout/gerenciar/consultaSubtotalCarrinho',
			type: 'POST',
			dataType: 'json',
			data: {},
		})
		.done(function(data) {
			console.log(data)
			$('#subtotal').html(data.formated);
			$('input[name=subtotal]').val(data.unformated);
		})
		.fail(function(data) {
			console.log("error");
			console.log(data)
		})
	}


	$('.pagarcompra').on('click', function(event) {
		event.preventDefault();
		$(this).attr('disabled', 'disabled')
		
		$('.containerProdutos').addClass('hide')
		$('.containerPagarCompra').removeClass('hide')
	});

	var formapagamento = '';
	$('.btnformaPagamento').on('click', function(event) {
		event.preventDefault();
		formapagamento = $(this).attr('type')
		$('#tipo_'+formapagamento).removeClass('hide')
		$('.containerFinalizarCompra').removeClass('hide')
		$('.containerPagarCompra').addClass('hide')
	});


	$('input[name=valorrecebido]').bind('change paste keyup', function(event) {
		var qtd = $(this).val();
		qtd = qtd.replace(".","");
        qtd = qtd.replace(",",".");
        qtd = parseFloat(qtd);
		var subtotal = qtd - $('input[name=subtotal]').val();

		subtotal = subtotal.formatMoney(2, ',', '.');
		$('#troco').html('R$ '+subtotal);



	});

	$('.btnFinalizar').on('click', function(event) {
		event.preventDefault();
		var valorrecebido = $('input[name=valorrecebido]').val();

		$.ajax({
			url: url+'caixa/checkout/gerenciar/finalizarCompra',
			type: 'POST',
			//dataType: 'default: Intelligent Guess (Other values: xml, json, script, or html)',
			data: {formapagamento: formapagamento, valorrecebido : valorrecebido},
		})
		.done(function(data) {
			console.log(data)
			$.notify({
            	icon: 'glyphicons glyphicons-ok',
				message: 'Compra finalizada',
			},{
				type: "success",
				placement: {
					from: "top",
					align: "right"
				}
			});

			resetCheckout();
		})
		.fail(function(data) {
			$.notify({
            	icon: 'glyphicons glyphicons-alert',
				message: data.responseText,
			},{
				type: "warning",
				placement: {
					from: "top",
					align: "right"
				}
			});
		})
	});


	function resetCheckout()
	{
		formapagamento = '';
		$('input[name=valorrecebido]').val('');
		$('#troco').html('');
		$('#listcarrinho tbody').html('');
		$('#subtotalProduto').html('')
		$('input[name=subtotal]').val('');
		$('#tipo_DINHEIRO, #tipo_CARTAODEBITO, #tipo_CARTAOCREDITO').addClass('hide');
		$('.containerProdutos').removeClass('hide');
		$('.containerProdutoUnitario').addClass('hide')
	}


})
</script>