<div class="container">
	
	<div id="fullscreen" class="fullscreenCheckout">
		
		<div class="container-fluid">
		    <div class="row telaVenda">
		        <div class="col-sm-3 col-md-2 sidebarcheckout">
		          	<figure class="center-block figureLogo thumbnail">
			      		<img src="<?=URL?>skin/img/imagens/logosupermercado.png" alt="">
					</figure>
					<div class="containerHora">
						<output id="hora"></output>				
					</div>	
					<div class="containerData">
						<output id="data"></output>
					</div>
		          	<ul class="nav nav-sidebar">
		            	<li><a href="javascript:void(0)" class="openfullscreen">Tela cheia</a></li>
		            	<li><a href="">Nav item again</a></li>
		            	<li><a href="">One more nav</a></li>
		            	<li><a href="">Another nav item</a></li>
		            	<li><a href="">More navigation</a></li>
		          	</ul>
		          	<div class="row">
					  	<div class="col-xs-12 col-md-12">
				      		<img src="<?=URL?>skin/img/imagens/1439113161_provider.png" alt="..." class="img-circle">
					  	</div>
					</div>
		        </div>
		        <div class="col-sm-4 col-sm-offset-2 col-md-4 col-md-offset-2 bg-primary containerProdutos">
		          	<h1 class="page-header">PRODUTOS</h1>
					<div class="row">
						<div class="col-xs-12 col-md-12 col-sm-12 col-lg-12">
							<div class="form-group">
							    <label for="exampleInputEmail1">Código de barras</label>
							    <input type="text" class="form-control" id="codigobarras" placeholder="Código de barras" maxlength="13">
							</div>
							<div class="listProducts">
								<div class="item">
									<h3>Arroz Camil tipo 1 - 5kg</h3>
									<div class="col-xs-12 col-md-12">
									    <div class="thumbnail">
									      	<img src="<?=URL?>skin/img/imagens/benchmarking.png" alt="">
									    </div>
									</div>
								</div>
							</div>
							<div class="subtotal">
								<div class="form-group">
								    <label class="col-sm-8 control-label">QUANTIDADE</label>
								    <div class="col-sm-4">
								      	<input type="number" class="form-control" value="1" min="1">
								    </div>
								</div>
								<div class="form-group">
								    <label class="col-sm-8 control-label">VALOR UNITÁRIO</label>
								    <div class="col-sm-4">
								      	<p><small>R$</small><span>2,50</span></p>
								    </div>
								</div>
								<div class="form-group">
								    <label class="col-sm-8 control-label">SUBTOTAL</label>
								    <div class="col-sm-4">
								      	<p><small>R$</small><span>2,50</span></p>
								    </div>
								</div>
							</div>
						</div>
					</div>
		        </div>
		        <div class="col-sm-4 col-sm-offset-2 col-md-6 col-md-offset-6 containerListaCompra">
		          	<h1 class="page-header">LISTA DA COMPRA</h1>
					<div class="row">
					  	<div class="col-xs-12 col-md-12 col-sm-12 col-lg-12">
						  	<table class="table table-striped" cellspacing="0">
							    <thead>
							        <tr>
							        	<th>#</th>
							        	<th>Item</th>
							        	<th>QTDE.</th>
							        	<th>R$</th>
							        </tr>
							    </thead>
							    <tbody>
							    	<tr>
							        	<td>01</td>
							        	<td>Arroz Camil tipo 1 - 5kg</td>
							        	<td>1</td>
							        	<td>1,50</td>
							        </tr>
							    </tbody>
							</table>
						</div>

					</div>
		          
		        </div>
		    </div>
	    </div>







	</div>

	<div id="telaPrincipal" class="hide">
		<div class="containercheckoutInicio">
			<figure class="center-block figureLogo thumbnail">
	      		<img src="<?=URL?>skin/img/imagens/logosupermercado.png" alt="">
			</figure>
			<div class="containerHora">
				<output id="hora"></output>				
			</div>	
			<div class="containerData">
				<output id="data"></output>
			</div>
			<a href="javascript:void(0)" class="openfullscreen">Clique para iniciar <span class="glyphicons glyphicons-hand-up"></span></a>
			<!-- <a href="#" class="exitfullscreen" style="display: none">Click to exit fullscreen</a> -->
		</div>
	</div>

	<div id="telaAbrirCaixa" class="hide">
		<div class="containercheckoutAbrirCaixa">
			<figure class="center-block figureLogo thumbnail">
	      		<img src="<?=URL?>skin/img/imagens/logosupermercado.png" alt="">
			</figure>
			<div class="containerHora">
				<output id="hora"></output>				
			</div>	
			<div class="containerData">
				<output id="data"></output>
			</div>
			<form class="form" action="<?=URL?>caixa/checkout/gerenciar/abrircaixa">
				<div class="form-group">
				    <label>Saldo Inicial em caixa</label>
				    <input type="number" class="form-control" placeholder="Saldo">
				</div>
				<button type="submit" class="btn btn-primary pull-right">Abrir caixa</button>
			</form>
		</div>
	</div>


</div>
<script type="text/javascript" src="<?=URL?>skin/js/fullscreen/jquery.fullscreen.min.js"></script>
<script type="text/javascript">
	$(function() {
		var isRegisteredMachine = false;
		$.post(url+'caixa/checkout/gerenciar/checkmachine', {}, function(data) {
			if(data == true){
				isRegisteredMachine = true;
				//$('#fullscreen').html($('#telaPrincipal').clone().removeClass('hide'))
			}else
			{
				//$('#fullscreen').html('<div class="alert alert-warning text-center" role="alert"><h3>Esta máquina não está registrada para realizar esta operação!</h3></div>');
				isRegisteredMachine = data;
			}
		});

		//


		// check native support
		$('#support').text($.fullscreen.isNativelySupported() ? 'supports' : 'doesn\'t support');

		// open in fullscreen
		$(document).on('click', '.openfullscreen', function() {
			if(isRegisteredMachine === true){
				$('#fullscreen').fullscreen();
				//$('#fullscreen').html($('#telaAbrirCaixa').clone().removeClass('hide'))
			}else
				messageDialog(isRegisteredMachine,'warning',true,null);
			return false;
		});

		// exit fullscreen
		$('#fullscreen .exitfullscreen').click(function() {
			$.fullscreen.exit();
			return false;
		});

		// document's event
		$(document).bind('fscreenchange', function(e, state, elem) {
			// if we currently in fullscreen mode
			if ($.fullscreen.isFullScreen()) {
				$('#fullscreen .openfullscreen').hide();
				$('#fullscreen .exitfullscreen').show();
			} else {
				$('#fullscreen .openfullscreen').show();
				$('#fullscreen .exitfullscreen').hide();
			}

			$('#state').text($.fullscreen.isFullScreen() ? '' : 'not');
		});




		jQuery.multipress = function (keys, handler) {
		    'use strict';

		    if (keys.length === 0) {
		        return;
		    }

		    var down = {};
		    jQuery(document).keydown(function (event) {
		        down[event.keyCode] = true;
		    }).keyup(function (event) {
		        // Copy keys array, build array of pressed keys
		        var remaining = keys.slice(0),
		            pressed = Object.keys(down).map(function (num) { return parseInt(num, 10); }),
		            indexOfKey;
		        // Remove pressedKeys from remainingKeys
		        jQuery.each(pressed, function (i, key) {
		            if (down[key] === true) {
		                down[key] = false;
		                indexOfKey = remaining.indexOf(key);
		                if (indexOfKey > -1) {
		                    remaining.splice(indexOfKey, 1);
		                }
		            }
		        });
		        // If we hit all the keys, fire off handler
		        if (remaining.length === 0) {
		            handler(event);
		        }
		    });
		};
		// $(document).bind('keydown', function(event) {
		// 	if(event.keyCode == 122)
		// 		$('#fullscreen').fullscreen();
		// });

		// jQuery.multipress([18], function () { 
		// 	if ($.fullscreen.isFullScreen()) {
		// 		alert('está no fullscreen')
		// 	}else{
		// 		alert('não está no fullscreen')
		// 	} 
		// })




		

	});
</script>
<script type="text/javascript">
	jQuery(window).load(function($){
		atualizaRelogio();
	});
</script>

<script>
	function atualizaRelogio(){ 
		var momentoAtual = new Date();
		
		var vhora = momentoAtual.getHours();
		var vminuto = momentoAtual.getMinutes();
		var vsegundo = momentoAtual.getSeconds();
		
		var vdia = momentoAtual.getDate();
		var vmes = momentoAtual.getMonth() + 1;
		var vano = momentoAtual.getFullYear();

		var Dia = momentoAtual.getDay(); 
		var Mes = momentoAtual.getUTCMonth();

		arrayDia = new Array();
		   arrayDia[0] = "Domingo";
		   arrayDia[1] = "Segunda-Feira";
		   arrayDia[2] = "Terça-Feira";
		   arrayDia[3] = "Quarta-Feira";
		   arrayDia[4] = "Quinta-Feira";
		   arrayDia[5] = "Sexta-Feira";
		   arrayDia[6] = "Sabado";
		 
		var arrayMes = new Array();
		   arrayMes[0] = "Janeiro";
		   arrayMes[1] = "Fevereiro";
		   arrayMes[2] = "Março";      
		   arrayMes[3] = "Abril";
		   arrayMes[4] = "Maio";
		   arrayMes[5] = "Junho";
		   arrayMes[6] = "Julho";
		   arrayMes[7] = "Agosto";
		   arrayMes[8] = "Setembro";
		   arrayMes[9] = "Outubro";
		   arrayMes[10] = "Novembro";
		   arrayMes[11] = "Dezembro";




		if (vdia < 10){ vdia = "0" + vdia;}
		if (vmes < 10){ vmes = "0" + vmes;}
		if (vhora < 10){ vhora = "0" + vhora;}
		if (vminuto < 10){ vminuto = "0" + vminuto;}
		if (vsegundo < 10){ vsegundo = "0" + vsegundo;}

		dataFormat = arrayDia[Dia] + ", " + vdia + " de " + arrayMes[Mes] + " de " + vano;
		horaFormat = vhora + " : " + vminuto + " : " + vsegundo;

		
	


		document.getElementById("data").innerHTML = dataFormat;
		document.getElementById("hora").innerHTML = horaFormat;
		setTimeout("atualizaRelogio()",1000);
	}


</script>