<?php 
$template = new template();
?>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <?=$template->page_header('Editar tipo de telefone: <small>'.$nome_tipo_telefone.'</small>');?>
    <?php
    $btnVoltar = $template->btnVoltar(URL.'configuracoes/tabelas/tipo_telefone/');
    echo $template->actions_buttons($btnVoltar);
    ?>

    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-left">
        <form action="<?=URL?>configuracoes/tabelas/tipo_telefone/atualizar" id="form_tipo_telefone" method="POST">
            
            <div class="form-group has-feedback">
                <label for="estadocivil">Nome do estado civil</label>
                <input type="text" class="form-control" id="estadocivil" placeholder="Nome do tipo de telefone" name="nome" value="<?=$nome_tipo_telefone?>">
            </div>


            <div class="form-group has-feedback">
                <div class="input-group">
                    <span class="input-group-addon"><input type="checkbox" name="status" <?=$status_tipo_telefone?>></span>
                    <input type="text" class="form-control" value="Publicar ?" readonly="readonly" >
                </div>
            </div>

            <input type="hidden" class="form-control" id="id" name="id" value="<?=$id_tipo_telefone?>">
            <button type="submit" class="btn btn-default" name="btn_salvar">Salvar</button>
        </form>
    </div>
</div>
<style>
.popover-content {
  padding: 0px 0px;
}
</style>
<script>
$(function() {    
    $('#form_tipo_telefone').submitForm({
        'resetform':false,
    	'reload' : true
    });
});
</script>