<div class="container">
    <?php
    $btnVoltar = $this->templateFactory->getButton('voltar',array('href'=>URL.'produtos/gerenciar'));
    echo $this->templateFactory->getButton('actions_buttons',array('buttons'=>$btnVoltar));
    ?>
    <div class="page-header">
        <h1>Produtos<small> Cadastro</small></h1>
    </div>
    <form action="<?=URL?>produtos/gerenciar/inserir" method="post" id="form_produto">
        <div class="panel panel-default">
            <div class="panel-heading">Dados Gerais</div>
            <div class="panel-body">

                <div class="row col-xs-6 col-md-3 col-sm-3 col-lg-3">
                    <div class="col-xs-6 col-md-12">
                        <label for="foto" class="thumbnail inputFoto preview-lg">
                            <div class="thumbnail img-preview preview-lg">
                                <img src="<?=URL?>skin/img/imagens/forn.jpg" id="img_previous">
                            </div>
                            <input type="file" name="foto" id="foto" accept="image/*">
                        </label>
                    </div>
                </div>
                <div class="row col-xs-6 col-md-3 col-sm-9 col-lg-9">
                    <div class="input-group">
                        <span class="input-group-addon" id="basic-addon1">Nome</span>
                        <input type="text" class="form-control" placeholder="Nome" aria-describedby="basic-addon1" name="nome">
                    </div>

                    <div class="input-group">
                        <span class="input-group-addon" id="basic-addon1">Marca</span>
                        <select name="marca" id="marca" class="form-control">
                            <option selected="selected" disabled="disabled" value="">..Selecione..</option>
                            <?php if(!empty($marcas)):?>
                            <?php foreach ($marcas as $marcas):?>
                            <option value="<?= $marcas->getId()?>"><?= $marcas->getNome()?></option>
                            <?php endforeach;?>
                            <?php endif;?>
                        </select>
                    </div>
                    <div class="input-group">
                        <span class="input-group-addon" id="basic-addon1">Categoria</span>
                        <select name="categoria" id="categoria" class="form-control">
                            <option selected="selected" disabled="disabled" value="">..Selecione..</option>
                            <?php if(!empty($categorias)):?>
                            <?php foreach ($categorias as $categorias):?>
                            <option value="<?= $categorias->getId()?>"><?= $categorias->getNome()?></option>
                            <?php endforeach;?>
                            <?php endif;?>
                        </select>
                    </div>
                    <div class="input-group">
                        <span class="input-group-addon" id="basic-addon1">Descrição</span>
                        <textarea class="form-control" placeholder="Descrição" name="descricao"></textarea>
                    </div>
                </div>
            </div> 


        </div> <!-- fim panel dados gerais -->
        
        <div class="panel panel-default">
            <div class="panel-heading">Valores</div>
            <div class="panel-body">
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Preço de Venda R$</span>
                    <input type="text" class="form-control" placeholder="Preço de Venda" aria-describedby="basic-addon1" name="preco_venda" name="preco_venda"  value="" >
                    <span class="input-group-addon" id="basic-addon1"><input type="checkbox" name="precoVendaAutomatico">Automático</span>
                </div>

                <div class="input-group boxmarkup" style="display:none" >
                    <span class="input-group-addon" id="basic-addon1">Markup %</span>
                    <input type="text" class="form-control" placeholder="Markup %" aria-describedby="basic-addon1" name="markup" maxlength="6" value="">
                </div>
                
            </div>
        </div>
       
        <div class="panel panel-default">
            <div class="panel-heading">
                Unidades de medida
                <div class="pull-right">
                    <a href="javascript:void(0)" class="btn btn-primary btn-sm btn_addUnidade">Adicionar</a>
                </div> 
            </div>
            <div class="panel-body">
                <div class="alert alert-warning alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <strong>Atenção!</strong> As unidades devem ser cadastradas da menor para a maior unidade.
                </div>
                <div class="row groupUnidades">
                    
                </div>



                
            </div>
            <div class="btn-group pull-right" role="group">
                <button type="submit" class="btn btn-success">Enviar</button>
            </div>
        </div>
    </form>
</div>



<script type="text/javascript" src="<?=URL?>skin/js/uploadForm.js"></script>
<link href="<?=URL?>skin/js/croper/cropper.min.css" rel="stylesheet">
<link href="<?=URL?>skin/js/croper/main.css" rel="stylesheet">
<script src="<?=URL?>skin/js/croper/cropper.min.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/jquery.maskedinput.min.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/jquery.maskMoney.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/jquery.validate.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/produtos/cadastrar.js"></script>