<div class="container">
    <div class="page-header">
      <h1>Produtos<small> Cadastro</small></h1>
    </div>
    <form action="<?=URL?>produtos/home/inserir" method="post" id="form_produtos">
        <div class="panel panel-default">
          <div class="panel-heading">Dados Gerais</div>
          <div class="panel-body">

            <div class="row">
                    <div class="col-xs-6 col-md-3">
                        <label for="foto" class="thumbnail inputFoto preview-lg">
                            <div class="thumbnail img-preview preview-lg">
                                <img src="<?=URL?>skin/img/imagens/forn.jpg" id="img_previous">
                            </div>
                            <input type="file" name="foto" id="foto" accept="image/*">
                        </label>
                    </div>
                </div>
             <div >
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">Nome</span>
                <input type="text" class="form-control" placeholder="Nome" aria-describedby="basic-addon1" name="nome">
            </div>
        </div>

        <div class="input-group">
             <span class="input-group-addon" id="basic-addon1">Marca</span>
                    <select name="marca" id="marca" class="form-control">
                        <option selected="selected" disabled="disabled" value="">..Selecione..</option>
                        <?php if(!empty($marcas)):?>
                        <?php foreach ($marcas as $marcas):?>
                        <option value="<?= $marcas->getId()?>"><?= $marcas->getNome()?></option>
                        <?php endforeach;?>
                        <?php endif;?>
                    </select>
        </div>
        <div class="input-group">
             <span class="input-group-addon" id="basic-addon1">Categoria</span>
                    <select name="ategorias" id="categoria" class="form-control">
                        <option selected="selected" disabled="disabled" value="">..Selecione..</option>
                        <?php if(!empty($categorias)):?>
                        <?php foreach ($categorias as $categorias):?>
                        <option value="<?= $categorias->getId()?>"><?= $categorias->getNome()?></option>
                        <?php endforeach;?>
                        <?php endif;?>
                    </select>
        </div>

        <div >
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">Descrição</span>
                <input type="text" class="form-control" placeholder="Descrição" aria-describedby="basic-addon1" name="descricao">
            </div>
        </div>

         <div class="input-group">
             <span class="input-group-addon" id="basic-addon1">Fornecedor</span>
              <select name="fornecedores" id="fornecedores" class="form-control">
                        <option selected="selected" disabled="disabled" value="">..Selecione..</option>
                        <?php if(!empty($fornecedores)):?>
                        <?php foreach ($fornecedores as $fornecedores):?>
                        <option value="<?= $fornecedores->getId()?>"><?= $fornecedores->getNomeFantasia()?></option>
                        <?php endforeach;?>
                        <?php endif;?>
              </select>
        </div>
        </div> 


        </div> <!-- fim panel dados gerais -->
        
        
       
       <div class="panel panel-default">
  <div class="panel-heading">Valores</div>
  <div class="panel-body">
   
      <div>
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">Preço de Compra</span>
                <input type="text" class="form-control" placeholder="Preço de Compra" aria-describedby="basic-addon1"name="preco_compra">
            </div>
        </div>

        <div>
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">Porcentagem de Lucro</span>
                <input type="text" class="form-control" placeholder="Porcentagem de Lucro" aria-describedby="basic-addon1" name="porcentagem_lucro">
            </div>
        </div>

        <div>
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">Preço de Venda</span>
                <input type="text" class="form-control" placeholder="Preço de Venda" aria-describedby="basic-addon1" name="preco_venda" disabled="disabled" name="preco_venda">
            </div>
        </div>

        <div>
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">Peso </span>
                <input type="text" class="form-control" placeholder="Peso " aria-describedby="basic-addon1" name="peso">
            </div>
        </div>

        <div>
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">Quantidade </span>
                <input type="text" class="form-control" placeholder="Quantidade em Estoque" aria-describedby="basic-addon1" name="quantidade">
            </div>
        </div>
          <div>
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">Unidade de Medida</span>
                <select class="form-control" name="uni_medida">
                    <option value="" selected="selected" disabled="disabled">..Selecione..</option>
                    <option value="g"> Gramas (g)</option>
                    <option value="kg">Kilograma (Kg)</option>
                    <option value="cx">Caixa (Cx)</option>

                </select>
            </div>
        </div>
         <div>
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">Estoque Máximo</span>
                <input type="text" class="form-control" placeholder="Estoque Máximo" aria-describedby="basic-addon1" name="estoque_max">
            </div>
        </div>
         <div>
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">Estoque Mínimo</span>
                <input type="text" class="form-control" placeholder="Estoque Mínimo" aria-describedby="basic-addon1" name="estoque_min">
            </div>
        </div>
                <div class="btn-group pull-right" role="group">
                    <button type="submit" class="btn btn-success">Enviar</button>
                </div>
  </div>
</div><!-- fim panel Valores --> 
                 
    </form>
</div>



<script type="text/javascript" src="<?=URL?>skin/js/uploadForm.js"></script>
<link href="<?=URL?>skin/js/croper/cropper.min.css" rel="stylesheet">
<link href="<?=URL?>skin/js/croper/main.css" rel="stylesheet">
<script src="<?=URL?>skin/js/croper/cropper.min.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/jquery.maskedinput.min.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/jquery.maskMoney.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/jquery.validate.js"></script>
<script type="text/javascript">

 $(function(){
            $("input[name=preco_compra],input[name=preco_venda]").maskMoney({symbol:"R$",decimal:",",thousands:"."});
            


 })
 </script>








 