<div class="container">
    <div class="page-header">
      <h1>Produtos<small> Cadastro</small></h1>
    </div>
    <form action="<?=URL?>produtos/home/inserir" method="post" id="form_produtos">
        <div class="panel panel-default">
          <div class="panel-heading">Dados Gerais</div>
          <div class="panel-body">

            <div class="row">
            <div class="col-xs-6 col-md-3">
                <a href="#" class="thumbnail">
                    <img src="<?=URL?>skin/img/imagens/benchmarking.png" alt="...">
                </a>
            </div>
        </div>
             <div >
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">Nome</span>
                <input type="text" class="form-control" placeholder="Nome" aria-describedby="basic-addon1">
            </div>
        </div>

        <div >
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">Marca</span>
                <input type="text" class="form-control" placeholder="Marca" aria-describedby="basic-addon1">
            </div>
        </div>

        <div >
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">Categoria</span>
                <input type="text" class="form-control" placeholder="Categoria" aria-describedby="basic-addon1">
            </div>
        </div>

        <div >
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">Descrição</span>
                <input type="text" class="form-control" placeholder="Descrição" aria-describedby="basic-addon1">
            </div>
        </div>

        <div >
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">Fornecedor</span>
                <input type="text" class="form-control" placeholder="Fornecedor" aria-describedby="basic-addon1">
            </div>
        </div>
        </div> 


        </div> <!-- fim panel dados gerais -->

        
       
       <div class="panel panel-default">
  <div class="panel-heading">Valores</div>
  <div class="panel-body">
   
      <div>
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">Preço de Compra</span>
                <input type="text" class="form-control" placeholder="Preço de Compra" aria-describedby="basic-addon1">
            </div>
        </div>

        <div>
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">Porcentagem de Lucro</span>
                <input type="text" class="form-control" placeholder="Porcentagem de Lucro" aria-describedby="basic-addon1">
            </div>
        </div>

        <div>
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">Preço de Venda</span>
                <input type="text" class="form-control" placeholder="Preço de Venda" aria-describedby="basic-addon1">
            </div>
        </div>

        <div>
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">Peso Líquido</span>
                <input type="text" class="form-control" placeholder="Peso Líquido " aria-describedby="basic-addon1">
            </div>
        </div>

        <div >
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">Peso Bruto</span>
                <input type="text" class="form-control" placeholder="Peso Bruto" aria-describedby="basic-addon1">
            </div>
        </div>
        <div>
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">Quantidade</span>
                <input type="text" class="form-control" placeholder="Quantidade" aria-describedby="basic-addon1">
            </div>
        </div>
         <div>
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">Estoque Máximo</span>
                <input type="text" class="form-control" placeholder="Estoque Máximo" aria-describedby="basic-addon1">
            </div>
        </div>
         <div>
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">Estoque Mínimo</span>
                <input type="text" class="form-control" placeholder="Estoque Mínimo" aria-describedby="basic-addon1">
            </div>
        </div>
         <div>
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">Total em Estoque</span>
                <input type="text" class="form-control" placeholder="Total em Estoque" aria-describedby="basic-addon1">
            </div>
        </div>
         <div>
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">Dimensões</span>
                <input type="text" class="form-control" placeholder="Dimensões" aria-describedby="basic-addon1">
            </div>
        </div>
          <div>
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">Unidade de Medida</span>
                <select class="form-control">
                    <option value="" selected="selected" disabled="disabled">..Selecione..</option>
                    <option value="g"> Gramas (g)</option>
                    <option value="kg">Kilograma (Kg)</option>
                    <option value="ml">Mililitros (ml)</option>
                    <option value="l">Litros (l)</option>
                </select>
            </div>
        </div>
  </div>
</div><!-- fim panel Valores -->
     
        <div class="btn-group" role="group">
            <button type="submit" class="btn btn-default">Enviar</button>
        </div>
    </form>
</div>












 