<div class="container">
    <div class="page-header">
      <h1>Página de produtos<small>subtitulo</small></h1>
    </div>
    <div>
        <br><br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br><br><br><br><br><br><br><br><p>conteudo</p>
        <br><br><br><br><br><br><br><br><p>conteudo</p>
        <br><br><br><br><br><br><br><p>fim</p>
    </div>
</div>