<?php
/**
*@author Wellington cezar (programador jr) - wellington.infodahora@gmail.com
*/
$template = new template();
?>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" id="rol_membros">
    <?=$template->page_header('Escola Bíblica Dominical <small>Edição do departamento: '.$departamento['nome_departamento_ebd'].'</small>');?>
    <?php
        //page-header
        $btnVoltar = $template->btnVoltar(URL.'ebd/departamentos/');
        echo $template->actions_buttons($btnVoltar);
    ?>

    <div class="panel generalErrors panel-danger" style="text-align:left; display:none;  background-color: #f2dede;">
        <h4 class="panel-heading">Ocorreu(ram) o(s) seguinte(s) erro(s):</h4>
        <div class="alert alert-danger" role="alert">

        </div>
    </div>

    <form id="form_cadastro_departamentos" action="<?=URL?>ebd/departamentos/atualizar" method="POST">
        <!--DADOS FAMILIARES-->
        <div >
            <header class="box_header">
                <h2>Editar o departamento <?=$departamento['nome_departamento_ebd']?></h2>
            </header>

            <div class="content">
                <div class="form-group input-group">
                    <span class="input-group-addon" id="basic-addon1">Nome do departamento</span>
                    <input type="text" class="form-control" placeholder="Nome do departamento" name="nome_departamento" value="<?=$departamento['nome_departamento_ebd']?>">
                </div>
                <div class="form-group input-group">
                    <span class="input-group-addon">Coordenador</span>
                    <select name="coordenador" id="coordenador" class="form-control">
                        <option selected="selected" disabled="disabled" value="">Coordenador:</option>
                        <?php if($coordenadores != false):?>
                        <?php foreach ($coordenadores as $coorden):?>
                        <?php $fotoM = ($coorden['foto_membro'] != '') ? URL.'uploads/membros/p/'.$coorden['foto_membro'] : URL.'img/imagens/perfil-icone.png'?>
                        <?php $sel = ($coorden['id_coordenador_ebd'] == $departamento['id_coordenador_ebd']) ? 'selected="selected"' :''?>
                        <option value="<?=$coorden['id_coordenador_ebd']?>" data-class="avatar" data-style="background-image: url('<?=$fotoM?>');  background-size: 100%;  width: 22px;  height: 22px;" <?=$sel?>><?=$coorden['nome_membro']?> <?=$coorden['sobrenome_membro']?></option>
                        <?php endforeach;?>
                        <?php endif;?>
                    </select>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <input type="hidden" name="id_departamento" value="<?=$departamento['id_departamento_ebd']?>">
                <button type="submit" class="btn btn-success btn_salvar pull-right"><span class="glyphicon glyphicon-ok"></span> Atualizar</button>
            </div>
        </div>
    </form>
</div>

<script type="text/javascript" src="<?=URL?>js/jquery.validate.js"></script>
<script type="text/javascript" src="<?=URL?>js/jquery.maskedinput.min.js"></script>



<script type="text/javascript">
    $(function(){
        $('#form_cadastro_departamentos').submit(function(){
            $('#form_cadastro_departamentos').uploadForm({
                reload:true
            });
            return false;
        });

        /************************************/
        //campos select
        $.widget( "custom.iconselectmenu", $.ui.selectmenu, {
          _renderItem: function( ul, item ) {
            var li = $( "<li>", { text: item.label } );
     
            if ( item.disabled ) {
              li.addClass( "ui-state-disabled" );
            }
     
            $( "<span>", {
              style: item.element.attr( "data-style" ),
              "class": "ui-icon " + item.element.attr( "data-class" )
            })
              .appendTo( li );
            return li.appendTo( ul );
          }
        });

        $( "#coordenador" )
        .iconselectmenu()
        .iconselectmenu( "menuWidget")
        .addClass( "ui-menu-icons avatar" );
        /************************************/

        
    });
</script>

