<?php
/**
*@author Wellington cezar (programador jr) - wellington.infodahora@gmail.com
*/
$template = new template();
?>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" id="rol_membros">
    <?=$template->page_header('Escola Bíblica Dominical <small>Aulas</small>');?>
    <?php
        //page-header
        $btnVoltar = $template->btnVoltar(URL.'ebd/');
        echo $template->actions_buttons($btnVoltar);
    ?>
    <div class="panel generalErrors panel-danger" style="text-align:left; display:none;  background-color: #f2dede;">
        <h4 class="panel-heading">Ocorreu(ram) o(s) seguinte(s) erro(s):</h4>
        <div class="alert alert-danger" role="alert"></div>
    </div>

    <form action="<?=URL?>ebd/classes/home/inserirChamada" id="form_cadastro_chamada" method="post">
        <input type="hidden" name="classe" value="<?=$id_classe?>">

        <div class="form-group input-group">
            <span class="input-group-addon" id="basic-addon1">Data: </span>
            <input type="text" class="form-control" placeholder="Data da aula" name="data_aula">
        </div>
        <div class="form-group input-group">
            <span class="input-group-addon" id="basic-addon1">Hora: </span>
            <input type="time" class="form-control" placeholder="Hora da aula" name="hora_aula">
        </div>

        <div class="row">
            <header class="box_header">
                <h2><small>Selecione os alunos presentes</small></h2>
            </header>
        <?php
        if($alunos != false):
        foreach ($alunos as $aluno):
        ?>
            <div class="col-lg-12">
                <label class="input-group">
                    <span class="input-group-addon ">
                        <input type="checkbox" name="presente[]" value="<?=$aluno['id_aluno']?>">
                    </span>
                    <span class="input-group-addon" style="padding: 0;">
                        <?php $fotoM = ($aluno['foto_aluno'] != '') ? URL.'uploads/membros/p/'.$aluno['foto_aluno'] : URL.'img/imagens/perfil-icone.png'?>
                        <img src="<?=$fotoM?>" style="width: 32px;">
                    </span>
                    <input type="text" class="form-control" value="<?=$aluno['nome_aluno']?>" disabled="disabled">
                </label><!-- /input-group -->
            </div><!-- /.col-lg-6 -->
        <?php
        endforeach;
        endif;
        ?>
        </div><!-- /.row -->

        <div class="form-group">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <button type="submit" class="btn btn-success btn_salvar pull-right"><span class="glyphicon glyphicon-ok"></span> Cadastrar</button>
            </div>
        </div>
    </form>



    <!--BIC CALENDAR-->
    <div id="row" style="display: table;width: 100%;">
        <div class="col-md-12" >
            <div id="calendari_lateral1"></div>
        </div>
    </div>

</div>



<div class="view_aula">
    
</div>
<style type="text/css">
    /*.view_aula{
        position: fixed;
        top: 0;
        bottom: 0;
        right: 0;
        left: 0;
        background-color: rgba(5, 0, 0, 0.68);
        z-index: 99999;
        padding: 15px;
    }*/
</style>



<script type="text/javascript" src="<?=URL?>js/jquery.validate.js"></script>
<script type="text/javascript" src="<?=URL?>js/jquery.maskedinput.min.js"></script>

<link href="<?=URL?>js/bic_calendar/css/bic_calendar.css" rel="stylesheet">
<script src="<?=URL?>js/bic_calendar/js/bic_calendar.js"></script>



<script>
    $(document).ready(function() {
        var monthNames = ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"];
        var dayNames = ["Seg", "Ter", "Qua", "Qui", "Sex", "Sab", "Dom"];
        $('#calendari_lateral1').bic_calendar({
            //list of events in array
            //events: events,
            //enable select
            enableSelect: false,
            //enable multi-select
            multiSelect: false,
            //set day names
            dayNames: dayNames,
            //set month names
            monthNames: monthNames,
            //show dayNames
            showDays: true,
            //set ajax call
            reqAjax: {
                type: 'post',
                parameters : {classe: <?=$id_classe?>},
                url: '<?=URL?>ebd/classes/home/getChamadas/'
            }
            //set popover options
            //popoverOptions: {}
            //set tooltip options
            //tooltipOptions: {}
        });
    });
</script>

<script type="text/javascript">
    $(function(){
        $('input[name=hora_aula]').mask('99:99')
        $('input[name=data_aula]').datepicker({ 
            dateFormat: 'dd/mm/yy',
            changeMonth: true,
            changeYear: true
        });

        $('#form_cadastro_chamada').submit(function(){
            $('#form_cadastro_chamada').uploadForm({
                reload:true
            });
            return false;
        });


        $(document).on('click','a[rel=tooltip]',function(event) {
            
            $.post($(this).attr('href'),{},function(data){
                alert(data);
            });




            return false;
        });
    });
</script>


