<?php
/**
*@author Wellington cezar (programador jr) - wellington.infodahora@gmail.com
*/
$template = new template();
?>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    
    <?=$template->page_header('Escola Bíblica Dominical <small>classes</small>');?>
    <?php
        //page-header
        $btnVoltar = $template->btnVoltar(URL.'ebd/');
        $btnAdiconar = $template->btnAdicionarRegistro(URL.'ebd/classes/home/cadastrar','<span class="glyphicon glyphicon-book"></span> Adicionar classe');
    
        echo $template->actions_buttons($btnVoltar.$btnAdiconar);
    ?>
    <div class="middle-content">
        <?php
        $thead = '  <tr>   
                        <th width="160">Nome</th>
                        <th width="120">Igreja</th>
                        <th width="100">Depart./ Faixa etária</th>
                        <th width="100">Status (Ativo/Inativo)</th>
                        <th width="100">Ações</th>
                    </tr>';
        $tfoot = '  <tr>
                        <th>Nome</th>
                        <th>Igreja</th>
                        <th width="100">Depart./ Faixa etária</th>
                        <th>Status (Ativo/Inativo)</th>
                        <th>Ações</th>
                    </tr>';	 
        if($classes != false):
            $tbody = '';
            foreach ($classes as $classe):
            	$status = ($classe['status_classe_ebd'] == 'Ativo') ? true : false;

                $tbody .='  <tr id="'.$classe['id_classe_ebd'].'">
                                <td>'.$classe['nome_classe_ebd'].'</td>
                                
                                <td>'.$classe['nome_igreja'].'</td>
                                <td width="100">'.$classe['nome_departamento_ebd'].' - de: '.$classe['faixa_etaria_min'].' até '.$classe['faixa_etaria_max'].' anos</td>
                                <td>
                                    '.$template->checkboxStatus($classe['id_classe_ebd'],'status',$status).'
                                </td>
                                <td>
                                    '
                                    .$template->btnAlunos(URL.'ebd/classes/alunos/classe/'.$classe['id_classe_ebd'],'<span class="glyphicon glyphicon-user"></span> Alunos')
                                    .$template->btnProfessores(URL.'ebd/classes/professores/classe/'.$classe['id_classe_ebd'],'<span class="glyphicon glyphicon-education"></span> Professores')
                                    .$template->btnChamadas(URL.'ebd/classes/home/chamadas/'.$classe['id_classe_ebd'],'Chamadas')
                                    .$template->btnEditarRegistro(URL.'ebd/classes/home/editar/'.$classe['id_classe_ebd'])
                                    .$template->btnExcluirRegistro('javascript:void(0)',$classe['id_classe_ebd'])
                                    .'
                                </td>
                            </tr>';
            endforeach;
            echo $template->tabela($thead, $tfoot, $tbody);
        else:
            echo '<h2>Não há registros cadastrados</h2>';
        endif;
        ?>
    </div>

</div>
<script>
$(document).ready(function() {
    var table = $('.dataTable').DataTable({
    	order: [1,'asc']
    });
    table.$('.btn_excluir').on('click',function(){
        var id = $(this).attr('id');
        var status = 'Excluído';

        $("#dialogResult").html('Deseja mesmo excluir?');
		$("#dialogResult").dialog({
			autoOpen: true,
			buttons: [
				{
					text: "Ok",
					click: function() {
						$( this ).dialog( "close" );

				    	$.post(url+'ebd/classes/home/excluir',{id:id,status:status},function(data){
							if(data == true){
								$('tr#'+id).hide();

                                $("#dialogResult").html('Registro enviado para a lixeira');
                                $("#dialogResult").dialog({
                                    autoOpen: true,
                                    buttons: [
                                        {
                                            text: "Ok",
                                            click: function() {
                                                $( this ).dialog( "close" );
                                            }
                                        }
                                    ]
                                });


                            }
						});
					}
				},
				{
					text: "Cancelar",
					click: function() {
						$( this ).dialog( "close" );
					}
				}
			]
		});



		
        
    });

    table.$('input[name=status]').on('change',function(){
    	var id = $(this).attr('id')
    	var status = 'Inativo';
		if($(this).is(':checked'))
			status = 'Ativo';

		$.post(url+'ebd/classes/home/atualizarStatus',{id:id,status:status},function(data){
            
		});

    });


});
</script>