    
       <?php
      //  echo "<pre>";
      // print_r($compromissosagendados);
      // echo "</pre>";
            $thead = '  <tr>
                            <th width="30">Id</th>
                            <th width="30">Fornecedor</th>
                            <th width="300">Titulo</th>
                            <th width="80">Ações</th>
                        </tr>';
            $tfoot = '  <tr>
                            <td>Id</td>
                            <td>Fornecedor</td>
                            <th>Titulo</th>
                            <td>Ações</td>
                        </tr>';  

            $tbody = '';

            foreach ($compromissosagendados as $compromissos):

            $tbody .='  <tr id="'.$compromissos->getId().'">
                            <td>'.$compromissos->getId().'</td>
                            <td>'.$compromissos->getFornecedor()->getNomeFantasia().'</td>
                            <td>'.$compromissos->getTitulo().'</td>
                            <td>'.$dataFormat->formatar($compromissos->getData(),'data').'</td>
                            <td>'
                                .$this->templateFactory->getButton('Adiar', array('href'=>URL.'agenda/gerenciar/adiarCompromissos/'.$compromissos->getId(), 'title'=>'Adiar')).

                            '</td>
                        </tr>';
                endforeach;
                echo $this->templateFactory->getTable('tabela', array('thead'=>$thead, 'tfoot'=>$tfoot, 'tbody'=>$tbody, 'moreContent' => ''));
            ?>

<script type="text/javascript">
    $(function(){

            $('.dataTable').show()
            
            // //DATATABLE
            // var table = $('.dataTable').DataTable({
            //     order: [0,'asc']
            // });
            // //ADIAR
            // table.$(' .btn_adiar').on('click',function(){
            //     var idCompromissosAgendados = $(this).attr('idCompromissosAgendados')
            //     $.post($(this).attr('href'),{},function(data){
            //         if(data == true){
            //             messageDialog('Produto aprovado','success',false,null);
            //             $('.btn_adiar[idCompromissosAgendados='+idCompromissosAgendados+']').attr('disabled', 'disabled');
            //         }else
            //         {
            //             messageDialog(data,'warning',false,null);
            //         }
            //     });
            //     return false;
            // });

        

    })
</script>

