<div class="container">

    <?php
    $btnCadastrar = $this->templateFactory->getButton("cadastrar",array('href'=>URL.'agenda/gerenciar/cadastrar'));
    echo $this->templateFactory->getButton("actions_buttons",array('buttons'=>$btnCadastrar));
    ?>

    <div class="page-header">
      <h1>Agenda de fornecedores</h1>
    </div>
    <div class="middle-content">
        <div id="row" style="display: table;width: 100%;">
            <div class="col-md-12" >
                <div id="agendaFornecedores"></div>
            </div>
        </div>
    </div>
</div>



<!-- Modal -->
<div class="modal fade" id="modalAgenda" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

<link href="<?=URL?>skin/js/bic_calendar/css/bic_calendar.css" rel="stylesheet">
<script src="<?=URL?>skin/js/bic_calendar/js/bic_calendar.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
        var monthNames = ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"];
        var dayNames = ["Seg", "Ter", "Qua", "Qui", "Sex", "Sab", "Dom"];
        $('#agendaFornecedores').bic_calendar({
            //list of events in array
            //events: events,
            //enable select
            enableSelect: false,
            //enable multi-select
            multiSelect: false,
            //set day names
            dayNames: dayNames,
            //set month names
            monthNames: monthNames,
            //show dayNames
            showDays: true,
            //set ajax call
            reqAjax: {
                type: 'post',
                //parameters : {classe: 1},
                url: '<?=URL?>fornecedores/agenda/listar'
            }
            //set popover options
            //popoverOptions: {}
            //set tooltip options
            //tooltipOptions: {}
        });

        $(document).on('click', '#agendaFornecedores a[rel=tooltip]', function(event) {
            event.preventDefault();
            $('#modalAgenda').modal('show')
        });
    });
</script>


