<?php 
$template = new template();

?>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <?=$template->page_header('Adicionar estado civil');?>
    <?php
    $btnVoltar = $template->btnVoltar(URL.'configuracoes/tabelas/estado_civil/');
    echo $template->actions_buttons($btnVoltar);
    ?>
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-left">
        <form action="<?=URL?>configuracoes/tabelas/estado_civil/inserir" id="form_estado_civil" method="POST">
            <div class="form-group has-feedback">
                <label for="estadocivil">Nome do estado civil</label>
                <input type="text" class="form-control" id="estadocivil" placeholder="Nome do estado civil" name="nome">
                
            </div>

            <div class="form-group has-feedback">
                <div class="input-group">
                    <span class="input-group-addon"><input type="checkbox" name="status" ></span>
                    <input type="text" class="form-control" value="Publicar ?" readonly="readonly">
                </div>
            </div>
            <button type="submit" class="btn btn-default" name="btn_salvar">Salvar</button>
        </form>
    </div>
</div>
<style>
.popover-content {
  padding: 0px 0px;
}
</style>
<script>
$(function() {    
    $('#form_estado_civil').submitForm({
    	'reload' : true
    });
});




</script>