<?php 
$template = new template();
?>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <?=$template->page_header('Editar estado civil: <small>'.$nome_estado_civil.'</small>');?>
    <?php
    $btnVoltar = $template->btnVoltar(URL.'configuracoes/tabelas/estado_civil/');
    echo $template->actions_buttons($btnVoltar);
    ?>

    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-left">
        <form action="<?=URL?>configuracoes/tabelas/estado_civil/atualizar" id="form_estado_civil" method="POST">
            <div class="form-group has-feedback">
                <label for="estadocivil">Nome do estado civil</label>
                <input type="text" class="form-control" id="estadocivil" placeholder="Nome do estado civil" name="nome" value="<?=$nome_estado_civil?>">
            </div>

            <div class="form-group has-feedback">
                <div class="input-group">
                    <span class="input-group-addon"><input type="checkbox" name="status" <?=$status_estado_civil?>></span>
                    <input type="text" class="form-control" value="Publicar ?" readonly="readonly" >
                </div>
            </div>

            <input type="hidden" class="form-control" id="id" name="id" value="<?=$id_estado_civil?>">
            <button type="submit" class="btn btn-default" name="btn_salvar">Salvar</button>
        </form>
    </div>
</div>
<style>
.popover-content {
  padding: 0px 0px;
}
</style>
<script>
$(function() {    
    $('#form_estado_civil').submitForm({
    	'reload' : true
    });
});
</script>