<div class="container">
    <?php

        $btnCadastrar = $this->templateFactory->getButton("cadastrar",array('href'=>URL.'suprimentos/cotacoes/gerenciar/cadastrar'), URL.'suprimentos/cotacoes/gerenciar/cadastrar');
        echo $this->templateFactory->getButton("actions_buttons",array('buttons'=>$btnCadastrar));
    ?>
    <div class="page-header">
      <h1>Cotações</h1>
    </div>
    <div class="middle-content">
        <img src="<?=URL?>img/loading3.gif" style="display: block;  margin: auto;  width: 200px;" id="loadTable">
        <table class="dataTable rwd-table" cellspacing="0" width="100%" style="display:none">
            <thead>
                <tr>   
                    <th width="100">Código</th>
                    <th width="160">Requisição</th>
                    <th width="160">Titulo</th>
                    <th width="160">Fornecedor</th>
                    <th width="160">Data</th>
                    <th width="160">Status</th>
                    <th width="180">Ações</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                   <td width="100">Código</td>
                    <td width="160">Requisição</td>
                    <td width="160">Titulo</td>
                    <td width="160">Fornecedor</td>
                    <th width="160">Data</th>
                    <td width="160">Status</td>
                    <td width="180">Ações</td>
                </tr>
            </tfoot>
            <tbody>
            <?php
            if(!empty($cotacoes)):
                foreach ($cotacoes as $cotacao):
            ?>
                <tr id="<?=$requsicao->getId()?>">
                    <td><?=$requsicao->getCodigo()?></td>
                    <td><?=$requsicao->getUsuario()->getNome()?></td>
                    <td><?=$requsicao->getTitulo()?></td>
                    <td><?=$requsicao->getData()?></td>
                    <td><?=$requsicao->getStatus()?></td>
                    <td><?=$requsicao->getAcoes()?></td>

                    <td>
                        <?= $this->templateFactory->getButton('visualizar', array('id'=> $cotacao->getId()), URL.'suprimentos/cotacoes/gerenciar/visualizar/')?>
                        <?= $this->templateFactory->getButton('cotar', array('id'=> $cotacao->getId()), URL.'suprimentos/cotacoes/gerenciar/cotar/')?>
                       <?= $this->templateFactory->getButton('ignorar', array('id'=> $cotacao->getId()), URL.'suprimentos/cotacoes/gerenciar/visualizar/')?>
                        
                    </td>
                </tr>
            <?php
                endforeach;
            endif;
            ?>
        
            </tbody>
        </table>
    </div>

</div>

<script type="text/javascript">
    $(function(){
        //DATATABLE
        var table = $('.dataTable').DataTable({
            order: [0,'asc']
        });

        //EXCLUIR
        table.$('.btn_cancelar').on('click',function(){
            var id = $(this).attr('id');
            var status = $(this).data('value');
            var modalDelete = $('#modalDelete').modal('show')
            $('.btn_ok','#modalDelete').on('click', function(event) {
                $.post(url+'suprimentos/cotacoes/gerenciar/cancelar',{id:id,status:status},function(data){
                    console.log(data)
                    if(data == true){
                        $('#modalDelete').modal('hide');
                        $('tr#'+id).hide();
                    }
                });
            });
        });


    })
</script>

