<div class="container">
    <?php
       $btnVoltar = $this->templateFactory->getButton("voltar",array('href'=>URL.'estoque/lotes'));
        echo $this->templateFactory->getButton("actions_buttons",array('buttons'=>$btnVoltar));    
    ?>
    <div class="page-header">
      <h1>Estoque<small> Entrada de mercadorias</small></h1>
    </div>
    <form action="<?=URL?>estoque/lotes/gerenciar/inserir" method="post" id="form_requisicao">
        <div class="panel panel-default">
            <div class="panel-heading">Dados Gerais</div>
            <div class="panel-body">
            	<div class="form-group col-xs-12 col-md-12 col-sm-12 col-lg-12">
					<div class="btn-group" role="group">
					  	<button type="button" class="btn btn-default" data-toggle="modal" data-target="#modalPesquisaProduto">Pesquisar produto</button>
					</div>
				</div>

				<!-- Modal -->
				<div class="modal fade" id="modalPesquisaProduto" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
				  	<div class="modal-dialog" role="document">
				    	<div class="modal-content">
				      		<div class="modal-header">
				        		<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				        		<h4 class="modal-title" id="myModalLabel">Pesquisar produto</h4>
				      		</div>
				      		<div class="modal-body">
								
								<div>
									<!-- Nav tabs -->
									<ul class="nav nav-tabs" role="tablist">
									    <li role="presentation" class="active"><a href="#porcodigo" aria-controls="porcodigo" role="tab" data-toggle="tab">Por código de barras</a></li>
									    <li role="presentation"><a href="#pordescricao" aria-controls="pordescricao" role="tab" data-toggle="tab">Por descrição</a></li>
									</ul>

									<!-- Tab panes -->
									<div class="tab-content">
									    <div role="tabpanel" class="tab-pane active" id="porcodigo">
											<div class="form-group col-xs-12 col-md-12 col-sm-12 col-lg-12">
							                    <label>Código de barras (GTI)</label>
							                    <input type="text" class="form-control" name="codigobarras" maxlength="13">
							                </div>
									    </div>
									    <div role="tabpanel" class="tab-pane" id="pordescricao">
									    	<div class="form-group col-xs-12 col-md-12 col-sm-12 col-lg-12">
							                    <label>Produtos</label>
							                    <select name="listaproduto" class="form-control">
							                        <?php if(!empty($produtos)):?>
							                        <?php foreach ($produtos as $produto):?>
							                        <option value="<?=$produto->getId()?>"><?=$produto->getNome()?></option>
							                        <?php endforeach;?>
							                        <?php endif;?>
							                    </select>
							                </div>

									    </div>
									</div>

								</div>



				      		</div>
				      		<div class="modal-footer">
				        		<button type="button" class="btn btn-default btnAddProduto">Ok</button>
				      		</div>
				    	</div>
				  	</div>
				</div>


		

			<?php 
			/*


                <div class="form-group col-xs-12 col-md-6 col-sm-4 col-lg-4">
                    <label>Nome</label>
                    <input type="text" class="form-control" placeholder="Nome" aria-describedby="basic-addon1" name="nome">
                </div>
                
                <div class="form-group col-xs-12 col-md-6 col-sm-4 col-lg-4">
                    <label>Código</label>
                    <input type="text" class="form-control" placeholder="Código" name="codigo" >
                </div>
                <div class="form-group col-xs-12 col-md-6 col-sm-4 col-lg-4">
                    <label>Nome</label>
                    <input type="text" class="form-control" placeholder="Nome" name="nome" >
                </div>
                 <div class="form-group col-xs-12 col-md-6 col-sm-4 col-lg-4">
                    <label>Estoque</label>
                    <input type="text" class="form-control" placeholder="Estoque Atual" name="estoqueatual" >
                </div>
                <div class="form-group col-xs-12 col-md-6 col-sm-4 col-lg-4">
                    <label>Estoque Minimo</label>
                    <input type="text" class="form-control" placeholder="Estoque minimo" name="estoqueminimo" >
                </div>
                <div class="form-group col-xs-12 col-md-6 col-sm-4 col-lg-4">
                    <label>Estoque Maximo</label>
                    <input type="text" class="form-control" placeholder="Estoque Maximo" name="estoquemaximo" >
                </div>
                 <div class="form-group col-xs-12 col-md-6 col-sm-4 col-lg-4">
                    <label>Observações</label>
                    <textarea  class="form-control" placeholder="Observações" name="observacoes" ></textarea>
                </div>


                
                    <div class="col-sm-6 col-md-2 modeloItemProduto hide" >
                        <input type="hidden" name="id_produto_requisicao" value="">
                        <input type="hidden" name="id_produto" value="">
                        <div class="thumbnail">
                            <img src="" class="imgProduct">
                            <div class="caption">
                                <div class="form-group">
                                    <label class="productname">Produto</label>
                                </div>
                                <label>Qtd.</label>
                                <div class="form-group col-xs-12 col-md-6 col-sm-4 col-lg-4">
                                    <input type="number" name="quantidade" value="0" class="form-control">
                                    <p class="form-control unidadeMedida"></p>
                                    <input type="hidden" name="idUnidadeMedida" value="">
                                </div>
                                <p><a href="javascript:void(0)" class="btn btn-danger btn_excluir" role="button">Remover</a></p>
                            </div>
                        </div>
                    </div>

                <div class="listProdutos row">
                    
                </div>
                <div class="btn-group pull-right" role="group">
                    <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-ok"></span> Salvar</button>
                </div>
                */
                ?>
            </div>
        </div>
    </form>
</div>






<script type="text/javascript" src="<?=URL?>skin/js/uploadForm.js"></script>
<!-- <script type="text/javascript" src="<?=URL?>skin/js/suprimentos/requisicoes/cadastrar.js"></script> -->
<script>
$(function(){
	var tabactive = '#porcodigo';

	$('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
	  	tabactive = e.target.hash; // newly activated tab
	  	//e.relatedTarget // previous active tab

	  	if(e.relatedTarget.hash == '#porcodigo')
	  	{
	  		$('input[name=codigobarras]').val('');
	  	}
	})

	$('.btnAddProduto').on('click', function(event) {
		event.preventDefault();
		var value = '';
		var tipo = 'porcodigo';
		if(tabactive == '#porcodigo')
		{
			tipo = 'porcodigo';
			value = $('input[name=codigobarras]').val()
		}else
		if(tabactive == '#pordescricao'){
			tipo = 'pordescricao';
			value = $('select[name=listaproduto]').val()
		}
		
		$.ajax({
			url: url+'estoque/gerenciar/pesquisarproduto',
			type: 'POST',
			data: {tipo: tipo, value:value},
		})
		.done(function(data) {
			console.log(data);
		})
		.fail(function() {
			console.log("error");
		})
		



	});
})
</script>