<?php
$template = new template();
?>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <?=$template->page_header('Usuários do sistema');?>
    <?php
        //page-header
        $btnAdiconar = $template->btnAdicionarRegistro(URL.'configuracoes/usuarios/usuarios/cadastrar','Adicionar usuário');
        $btnUserGroup = $template->btnAdicionarRegistro(URL.'configuracoes/usuarios/grupo_usuarios','Grupo de usuários');
        echo $template->actions_buttons($btnUserGroup.$btnAdiconar);
    ?>
    <div class="middle-content">
        <?php
        $thead = '  <tr>
                        <th>Nome</th>
                        <th width="120">Grupo de permissão</th>
                        <th width="120">Data de cadastro</th>
                        <th width="100">Status (Ativo/Inativo)</th>
                        <th width="180">Ações</th>
                    </tr>';
        $tfoot = '  <tr>
                        <th>Nome</th>
                        <th>Grupo de permissão</th>
                        <th>Data de cadastro</th>
                        <th>Status (Ativo/Inativo)</th>
                        <th>Ações</th>
                    </tr>';	 
        if($usuarios != false):
            $tbody = '';
            foreach ($usuarios as $usuario):
            	$status = ($usuario['status_usuario'] == 'Ativo') ? true : false;

                if($usuario['permissao_usuario'] != 'Administrador')
                {
                    $tbody .='  <tr id="'.$usuario['id_usuario'].'">
                                    <td>'.$usuario['nome_usuario'].'</td>
                                    
                                    <td>'.$usuario['nome_permissao'].'</td>
                                    <td>'.date('d/m/Y H:i:s', strtotime($usuario['data_cadastro'])).'</td>
                                    <td>
                                        '.$template->checkboxStatus($usuario['id_usuario'],'status',$status).'
                                    </td>
                                    <td>
                                        '.$template->btnEditarRegistro(URL.'configuracoes/tabelas/usuario/editar/'.$usuario['id_usuario']).
                                        $template->btnExcluirRegistro('javascript:void(0)',$usuario['id_usuario']).
                                    '</td>
                                </tr>';
                }else
                {
                    $tbody .='  <tr id="'.$usuario['id_usuario'].'">
                                    <td>'.$usuario['nome_usuario'].'</td>
                                    
                                    <td>Administrador geral</td>
                                    <td></td>
                                    <td>
                                        
                                    </td>
                                    <td>
                                    </td>
                                </tr>';
                }
            endforeach;
            echo $template->tabela($thead, $tfoot, $tbody);
        else:
            echo '<h2>Não há registros cadastrados</h2>';
        endif;
        ?>
    </div>

</div>
<script>
$(document).ready(function() {
    var table = $('.dataTable').DataTable({
    	order: []
    });
    table.$('.btn_excluir').on('click',function(){
        var id = $(this).attr('id');
        var status = 'Excluído';

        $("#dialogResult").html('Deseja mesmo excluir?');
		$("#dialogResult").dialog({
			autoOpen: true,
			buttons: [
				{
					text: "Ok",
					click: function() {
						$( this ).dialog( "close" );

				    	$.post(url+'configuracoes/usuarios/usuarios/excluir',{id:id,status:status},function(data){
							console.log(data)
                            if(data == true)
								$('tr#'+id).hide();
						});
					}
				},
				{
					text: "Cancelar",
					click: function() {
						$( this ).dialog( "close" );
					}
				}
			]
		});



		
        
    });

    table.$('input[name=status]').on('change',function(){
    	var id = $(this).attr('id')
    	var status = 'Inativo';
		if($(this).is(':checked'))
			status = 'Ativo';

		$.post(url+'configuracoes/usuarios/usuarios/atualizarStatus',{id:id,status:status},function(data){
            
		});

    });


});
</script>