<?php
$template = new template();
?>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <?=$template->page_header('Grupos de permissões de acesso');?>
    <?php
        //page-header
        $btnAdiconar = $template->btnAdicionarRegistro(URL.'configuracoes/usuarios/grupo_usuarios/cadastrar','Adicionar Grupo');
        
        echo $template->actions_buttons($btnAdiconar);
    ?>
    <div class="middle-content">
        <?php
        $thead = '  <tr>
                        <th>Nome</th>
                        <th width="180">Ações</th>
                    </tr>';
        $tfoot = '  <tr>
                        <th>Nome</th>

                        <th>Ações</th>
                    </tr>';	 
        if($gruposUsuarios != false):
            $tbody = '';
            foreach ($gruposUsuarios as $grupo):
            	

                $tbody .='  <tr id="'.$grupo['id_grupo_permissao'].'">
                                <td>'.$grupo['nome_permissao'].'</td>
                                <td>
                                    '.$template->btnEditarRegistro(URL.'configuracoes/usuarios/grupo_usuarios/editar/'.$grupo['id_grupo_permissao']).
                                    $template->btnExcluirRegistro('javascript:void(0)',$grupo['id_grupo_permissao']).
                                '</td>
                            </tr>';
            endforeach;
            echo $template->tabela($thead, $tfoot, $tbody);
        else:
            echo '<h2>Não há registros cadastrados</h2>';
        endif;
        ?>
    </div>

</div>
<script>
$(document).ready(function() {
    var table = $('.dataTable').DataTable({
    	order: []
    });
    table.$('.btn_excluir').on('click',function(){
        var id = $(this).attr('id');
        var status = 'Excluído';

        $("#dialogResult").html('Deseja mesmo excluir?');
		$("#dialogResult").dialog({
			autoOpen: true,
			buttons: [
				{
					text: "Ok",
					click: function() {
						$( this ).dialog( "close" );

				    	$.post(url+'configuracoes/usuarios/grupo_usuarios/excluir',{id:id,status:status},function(data){
							 console.log(data);
                            if(data == true)
								$('tr#'+id).hide();
						});
					}
				},
				{
					text: "Cancelar",
					click: function() {
						$( this ).dialog( "close" );
					}
				}
			]
		});



		
        
    });

    table.$('input[name=status]').on('change',function(){
    	var id = $(this).attr('id')
    	var status = 'Inativo';
		if($(this).is(':checked'))
			status = 'Ativo';

		$.post(url+'configuracoes/tabelas/usuario/atualizarStatus',{id:id,status:status},function(data){

		})

    });


});
</script>