<?php
/**
*@author Wellington cezar (programador jr) - wellington.infodahora@gmail.com
*/
$template = new template();
?>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" id="rol_membros">
    <?=$template->page_header('Escola Bíblica Dominical <small>Visualizar dados do professor</small>');?>
    <?php
        //page-header
        $btnVoltar = $template->btnVoltar(URL.'ebd/classes/');
        echo $template->actions_buttons($btnVoltar);
        $format = new dataFormat();
    ?>

    <div class="panel generalErrors panel-danger" style="text-align:left; display:none;  background-color: #f2dede;">
        <h4 class="panel-heading">Ocorreu(ram) o(s) seguinte(s) erro(s):</h4>
        <div class="alert alert-danger" role="alert">

        </div>
    </div>

    

    <div>
        <header class="box_header">
            <h2>Dados Pessoais</h2>
        </header>


        <div class="content">
            <div class="foto">
                <label class="col-xs-12 col-md-12" for="foto">
                    <div class="thumbnail img-preview preview-lg">
                        <?php $fotoMembro = ($membro['foto_membro'] != '') ? URL.'uploads/membros/'.$membro['foto_membro'] : URL.'img/imagens/rol-de-membros-icone.png';
                        ?>
                        <img src="<?=$fotoMembro?>" id="img_previous">
                    </div>
                    <input type="hidden" value="<?=$membro['foto_membro']?>" name="nomefoto">
                </label>
            </div>
            <?php
            if($membro['sexo_membro'] == 'M')
                $sexo = 'Masculino';
            else
                $sexo = 'Feminino';
            ?>
            <div class="form-group has-feedback">
                <input type="text" name="nome" placeholder="Nome" class="form-control" value="<?=$sexo?>" readonly="readonly"/>
            </div>
            <div class="form-group has-feedback">
                <input type="text" name="nome" placeholder="Nome" class="form-control" value="<?=$membro['nome_membro']?> <?=$membro['sobrenome_membro']?>" readonly="readonly"/>
            </div>
            <?php
            $date = new DateTime( '1991-02-04' ); // data de nascimento
            $interval = $date->diff( new DateTime( date('Y-m-d') ) ); // data definida
            $idade = $interval->format( '%Y Anos' ); // 110 Anos, 2 Meses e 2 Dias
            ?>
            <div class="form-group has-feedback">
                <input type="text" name="idade" placeholder="Idade" class="form-control" value="<?=$idade?>" readonly="readonly"/>
            </div>
        </div>
    </div>
    <!--/DADOS PESSOAIS-->
</div>
