<?php
/**
*@author Wellington cezar (programador jr) - wellington.infodahora@gmail.com
*/
$template = new template();
?>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    
    <?=$template->page_header('Escola Bíblica Dominical <small>Superintendentes</small>');?>
    <?php
        //page-header
        $btnAdiconar = $template->btnAdicionarRegistro(URL.'ebd/superintendentes/cadastrar','<span class="glyphicon glyphicon-user"></span> Adicionar superintendentes');
    
        echo $template->actions_buttons($btnAdiconar);
    ?>
    <div class="middle-content">
        <?php
        $thead = '  <tr>   
                        <th width="40">Foto</th>
                        <th width="160">Nome</th>
                        <th width="120">Data Início</th>
                        <th width="100">Data Fim</th>
                        <th width="100">Status (Ativo/Inativo)</th>
                        <th width="100">Ações</th>
                    </tr>';
        $tfoot = '  <tr>
                        <th>Foto</th>
                        <th>Nome</th>
                        <th>Data Início</th>
                        <th>Data Fim</th>
                        <th>Status (Ativo/Inativo)</th>
                        <th>Ações</th>
                    </tr>';	 
        if($superintendentes != false):
            $tbody = '';
            foreach ($superintendentes as $superint):
            	$status = ($superint['status_superintendente_ebd'] == 'Ativo') ? true : false;
                $foto = ($superint['foto_membro'] != '') ? URL.'uploads/membros/p/'.$superint['foto_membro'] : URL.'img/imagens/perfil-icone.png';

                $tbody .='  <tr id="'.$superint['id_superintendente_ebd'].'">
                                <td><img src="'.$foto.'" style="width: 60px;"></td>
                                <td>'.$superint['nome_membro'].' '.$superint['sobrenome_membro'].'</td>
                                
                                <td>'.date('d/m/Y', strtotime($superint['data_inicio_superintendente_ebd'])).'</td>
                                <td>'.date('d/m/Y', strtotime($superint['data_fim_superintendente_ebd'])).'</td>
                                <td>
                                    '.$template->checkboxStatus($superint['id_superintendente_ebd'],'status',$status).'
                                </td>
                                <td>
                                    '.$template->btnEditarRegistro(URL.'ebd/superintendentes/editar/'.$superint['id_superintendente_ebd']).$template->btnExcluirRegistro('javascript:void(0)',$superint['id_superintendente_ebd']).
                                '</td>
                            </tr>';
                

            endforeach;
            echo $template->tabela($thead, $tfoot, $tbody);
        else:
            echo '<h2>Não há registros cadastrados</h2>';
        endif;
        ?>
    </div>

</div>
<script>
$(document).ready(function() {
    var table = $('.dataTable').DataTable({
    	order: [1,'asc']
    });
    table.$('.btn_excluir').on('click',function(){
        var id = $(this).attr('id');
        var status = 'Excluído';

        $("#dialogResult").html('Deseja mesmo excluir?');
		$("#dialogResult").dialog({
			autoOpen: true,
			buttons: [
				{
					text: "Ok",
					click: function() {
						$( this ).dialog( "close" );

				    	$.post(url+'ebd/superintendentes/excluir',{id:id,status:status},function(data){
							if(data == true){
								$('tr#'+id).hide();

                                $("#dialogResult").html('Registro enviado para a lixeira');
                                $("#dialogResult").dialog({
                                    autoOpen: true,
                                    buttons: [
                                        {
                                            text: "Ok",
                                            click: function() {
                                                $( this ).dialog( "close" );
                                            }
                                        }
                                    ]
                                });


                            }
						});
					}
				},
				{
					text: "Cancelar",
					click: function() {
						$( this ).dialog( "close" );
					}
				}
			]
		});



		
        
    });

    table.$('input[name=status]').on('change',function(){
    	var id = $(this).attr('id')
    	var status = 'Inativo';
		if($(this).is(':checked'))
			status = 'Ativo';

		$.post(url+'ebd/superintendentes/atualizarStatus',{id:id,status:status},function(data){
            console.log(data)
		});
    });


});
</script>