<!DOCTYPE html>
<html lang="pt-br" ng-app>
<head>
    <meta charset="utf-8">
    <!--[if lt IE 9]>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <![endif]-->
    <title>SAC - Sistema de Automação Comercial</title>
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    
    <link rel="stylesheet" type="text/css" href="skin/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="skin/css/normalize.css" />
    <link rel="stylesheet" type="text/css" href="skin/css/animate.css" />
    <link rel="stylesheet" type="text/css" href="skin/css/main.css" />
    <link rel="stylesheet" type="text/css" href="skin/css/large_desktops.css" />
    <link rel="stylesheet" type="text/css" href="skin/css/desktops.css" />
    <link rel="stylesheet" type="text/css" href="skin/css/tablets.css" />
    <link rel="stylesheet" type="text/css" href="skin/css/extra_small_devices.css" />
    

    <meta name="robots" content="noindex, nofollow" />
    <!--[if IE]>
        <link rel="shortcut icon" href="img/favicon.ico">
    <![endif]-->
    <link rel="icon" href="img/favicon.png" />
    

    <script type="text/javascript" src="skin/js/angular.min.js"></script>
    <script type="text/javascript" src="skin/js/jquery-1.11.3.min.js"></script>
    <script type="text/javascript" src="skin/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="skin/js/main.js"></script>

</head>
<body>
    <div id="wrap" >
        <section class="col-xs-12 col-sm-12 col-md-12 col-lg-12" id="container_login">
            <div class="box_login">
                <header>
                    <img src="skin/img/logo/logo.png">
                </header>
                <form class="form-horizontal" id="form_login" action="login/logar">
                    <label class="input-group">
                        <span class="input-group-addon glyphicon glyphicon-user"></span>
                        <input type="text" class="form-control" id="login" name="login" placeholder="login">
                    </label>

                    <label class="input-group">
                        <span class="input-group-addon glyphicons glyphicons-keys"></span>
                        <input type="password" class="form-control" id="senha" name="senha" placeholder="Senha">
                    </label>

                    <!--capcha - para 5 ou mais tentativas de login incorreta-->
                    <label class="captcha input-group">
                        <div class="img">
                            <img src="login/captcha" style="width: 96%;">
                        </div>
                        <input type="text" class="form-control" id="captcha" name="captcha" placeholder="Insira o código">
                    </label>

                    <button type="submit" class="btn btn_login"><span class="glyphicon glyphicon-log-in" aria-hidden="true"></span> Entrar</button>
                </form>
                <a href="" class="recupera">Recuperar senha</a>
            </div>

        </section>
    </div><!--wrap-->

</body>
</html>
