<?php
$template = new template();
?>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <?=$template->page_header('Registros na lixeira');?>
    <?php
        //page-header

        echo $template->actions_buttons('');
    ?>
    <div class="middle-content">
        <?php
        $thead = '  <tr>
                        <th width="180">Data de Exclusão</th>
                        <th>Nome</th>
                        <th width="180">Tabela</th>
                        <th width="180">Ações</th>
                    </tr>';
        $tfoot = '  <tr>
                        <th>Data de Exclusão</th>
                        <th>Nome</th>
                        <th>Tabela</th>
                        <th>Ações</th>
                    </tr>';	 
        if($lixeira != false):
            $tbody = '';
            foreach ($lixeira as $lixo):
                $tbody .='  <tr id="'.$lixo['id_lixeira'].'">
                                <td>'.
                                date('d/m/Y H:i', strtotime($lixo['data_exclusao']))
                                .'</td>
                                <td>'.$lixo['nome'].'</td>
                                <td>
                                    '.$lixo['tabela'].'
                                </td>
                                <td>
                                    '/*.$template->btnEditarRegistro(URL.'configuracoes/tabelas/tipo_telefone/editar/'.$lixo['id_tipo_telefone'])*/.
                                    $template->btnRestaurarRegistro('javascript:void(0)',$lixo['id_lixeira']).
                                    $template->btnExcluirRegistro('javascript:void(0)',$lixo['id_lixeira']).
                                '</td>
                            </tr>';
            endforeach;
            echo $template->tabela($thead, $tfoot, $tbody);
        else:
            echo '<h2>Não há registros cadastrados</h2>';
        endif;

        
        ?>
    </div>

</div>
<script>
$(document).ready(function() {
    var table = $('.dataTable').DataTable({
    	order: []
    });
    table.$('.btn_excluir').on('click',function(){
        var id = $(this).attr('id');
        var status = 'Excluído';

        $("#dialogResult").html('Deseja mesmo excluir?');
		$("#dialogResult").dialog({
			autoOpen: true,
			buttons: [
				{
					text: "Ok",
					click: function() {
						$( this ).dialog( "close" );

				    	$.post(url+'lixeira/home/excluir',{id:id,status:status},function(data){
							if(data == true){
                                location.reload();
								$('tr#'+id).hide();
                            }
						});
					}
				},
				{
					text: "Cancelar",
					click: function() {
						$( this ).dialog( "close" );
					}
				}
			]
		});
    });


    table.$('.btn_restaurar').on('click',function(){
        var id = $(this).attr('id');
        var status = 'Inativo';

        $("#dialogResult").html('Deseja mesmo restaurar?');
        $("#dialogResult").dialog({
            autoOpen: true,
            buttons: [
                {
                    text: "Ok",
                    click: function() {
                        $( this ).dialog( "close" );

                        $.post(url+'lixeira/home/restaurar',{id:id},function(data){
                            console.log(data)
                            if(data == true){
                                location.reload();
                                $('tr#'+id).hide();
                            }
                            
                        });
                    }
                },
                {
                    text: "Cancelar",
                    click: function() {
                        $( this ).dialog( "close" );
                    }
                }
            ]
        });
    });



    table.$('input[name=status]').on('change',function(){
    	var id = $(this).attr('id')
    	var status = 'Inativo';
		if($(this).is(':checked'))
			status = 'Ativo';

		$.post(url+'configuracoes/tabelas/tipo_telefone/atualizarStatus',{id:id,status:status},function(data){

		})

    });


});
</script>