<?php
$template = new template();
?>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" id="rol_membros">
    <?=$template->page_header('Criar relatório específico de membros');?>
    <?php
        //page-header
        $btnAdiconar = $template->btnVoltar(URL.'rol-de-membros/relatorios/relatorio_especifico');
        echo $template->actions_buttons($btnAdiconar);
    ?>

    <div class="panel generalErrors panel-danger" style="text-align:left; display:none;  background-color: #f2dede;">
        <h4 class="panel-heading">Ocorreu(ram) o(s) seguinte(s) erro(s):</h4>
        <div class="alert alert-danger" role="alert">
        </div>
    </div>

    <form id="form_gera_relatorio" action="javascript:void(0)" method="POST">
        <!--DADOS PESSOAIS-->
        <div class="text-left">
            

            <style>
            .content .panel{
                padding: 0px;
            }
            </style>

            <div class="content" id="container1">
                <div class="panel panel-default col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="panel-body">
                        <header class="box_header">
                            <h2>Filtrar por:</h2>
                        </header>
                        <select class="col-xs-12 col-sm-5 col-md-5 col-lg-5" multiple="multiple" name="sel1" id="sel1" size="10">
                            <option value="data_nascimento">Data de Nascimento</option>
                            <option value="sexo">Sexo</option>
                            <option value="estado_civil">Estado Civil</option>
                            <option value="data_casamento">Data de Casamento</option>
                            <option value="data_recebimento_membro">Data de recebimento como membro</option>
                            <option value="data_batismo">Data de batismo</option>
                            <option value="data_profissao_fe">Data profissão de fé</option>
                            <option value="tipo_recebimento">Tipo de recebimento</option>
                            <option value="tipo_membro">Tipo de membro</option>
                            <option value="oficial_igreja">Oficial da igreja</option>
                            <option value="dizimista">Dizimista</option>
                            <option value="status">Status</option>
                            <option value="igreja">Igreja</option>
                            <option value="data_cadastro">Data de cadastro</option>
                            <option value="busca_especifica">Busca específica</option>
                        </select>
                        <div class="col-xs-12 col-sm-2 col-md-2 col-lg-2 text-center">
                            <a href="javascript:void(0)" onclick="insertSelected(getElementById('sel2'), getElementById('sel1'));" class="btn btn-default" id="transferLeft"> <span class="glyphicon glyphicon-chevron-left"></span> </a>
                            <a href="javascript:void(0)" onclick="insertSelected(getElementById('sel1'), getElementById('sel2'));" class="btn btn-default" id="transferRight"> <span class="glyphicon glyphicon-chevron-right"></span> </a>
                        </div>

                        <select name="sel2" id="sel2" size="10" multiple="multiple" class="col-xs-12 col-sm-5 col-md-5 col-lg-5">

                        </select>
                    </div>
                </div>
                <div class="panel panel-default col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <a href="javascript:void(0)" class="btn btn-default proximo1" style="float:right">Próximo</a>
                </div>
            </div>


            <div class="content " style="clear:both;display:none" id="container2">
                <div class="panel panel-default col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <a href="javascript:void(0)" class="btn btn-default voltar1" style="float:right">Voltar</a>
                    <header class="box_header">
                        <h2>Dados de filtragem:</h2>
                    </header>
                </div>
                <div class="panel panel-default col-xs-12 col-sm-12 col-md-12 col-lg-12 item" id="box_data_nascimento" style="display:none">
                    <div class="panel-heading">Data de Nascimento</div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="input-group">
                                    <div class="row">
                                        <div class="col-lg-6">
                                            <div class="input-group">
                                                <input type="text" class="form-control" name="data_nascimento_de" placeholder="De">
                                            </div><!-- /input-group -->
                                        </div><!-- /.col-lg-6 -->
                                        
                                        <div class="col-lg-6">
                                            <div class="input-group">
                                                <input type="text" class="form-control" name="data_nascimento_ate" placeholder="Até">
                                            </div><!-- /input-group -->
                                        </div><!-- /.col-lg-6 -->
                                    </div><!-- /.row-->
                                </div><!-- /input-group -->
                            </div><!-- /.col-lg-6 -->
                        </div><!-- /.row -->
                    </div>
                </div>

                

                <div class="panel panel-default col-xs-12 col-sm-12 col-md-12 col-lg-12 item" id="box_sexo" style="display:none">
                    <div class="panel-heading">Sexo</div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="input-group">
                                    <div class="row">
                                        <div class="col-lg-6">
                                            <div class="input-group">
                                                <span class="input-group-addon">
                                                    <input type="checkbox" name="sexo[]" value="M">
                                                </span>
                                                <input type="text" class="form-control" value="Masculino" readonly="readonly">
                                            </div><!-- /input-group -->
                                        </div><!-- /.col-lg-6 -->
                                        <div class="col-lg-6">
                                            <div class="input-group">
                                                <span class="input-group-addon">
                                                    <input type="checkbox" name="sexo[]" value="F">
                                                </span>
                                                <input type="text" class="form-control" value="Feminino" readonly="readonly">
                                            </div><!-- /input-group -->
                                        </div><!-- /.col-lg-6 -->
                                    </div><!-- /.row -->
                                </div><!-- /input-group -->
                            </div><!-- /.col-lg-6 -->
                        </div><!-- /.row -->
                    </div>
                </div>
                

                <div class="panel panel-default col-xs-12 col-sm-12 col-md-12 col-lg-12  item" id="box_estado_civil" style="display:none">
                    <div class="panel-heading">
                        Estado civil
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="input-group">
                                    <div class="row">
                                    <?php
                                    if($estadocivil != false):
                                    foreach ($estadocivil as $estCiv):
                                    ?>
                                        <div class="col-lg-4">
                                            <div class="input-group">
                                                <span class="input-group-addon">
                                                    <input type="checkbox" name="estado_civil[]" value="<?=$estCiv['id_estado_civil']?>">
                                                </span>
                                                <input type="text" class="form-control" value="<?=$estCiv['nome_estado_civil']?>" readonly="readonly">
                                            </div><!-- /input-group -->
                                        </div><!-- /.col-lg-6 -->
                                    <?php
                                    endforeach;
                                    endif;
                                    ?>
                                    </div><!-- /.row -->
                                </div><!-- /input-group -->
                            </div><!-- /.col-lg-6 -->
                        </div><!-- /.row -->
                    </div>
                </div>


                <div class="panel panel-default col-xs-12 col-sm-12 col-md-12 col-lg-12 item" id="box_data_casamento" style="display:none">
                    <div class="panel-heading">Data de Casamento</div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="input-group">
                                    <div class="row">
                                        <div class="col-lg-6">
                                            <div class="input-group">
                                                <input type="text" class="form-control" name="data_casamento_de"  placeholder="De">
                                            </div><!-- /input-group -->
                                        </div><!-- /.col-lg-6 -->
                                        
                                        <div class="col-lg-6">
                                            <div class="input-group">
                                                <input type="text" class="form-control" name="data_casamento_ate" placeholder="Até">
                                            </div><!-- /input-group -->
                                        </div><!-- /.col-lg-6 -->
                                    </div><!-- /.row-->
                                </div><!-- /input-group -->
                            </div><!-- /.col-lg-6 -->
                        </div><!-- /.row -->
                    </div>
                </div>

                <div class="panel panel-default col-xs-12 col-sm-12 col-md-12 col-lg-12 item" id="box_data_recebimento_membro" style="display:none">
                    <div class="panel-heading">Data de Recebimento como membro</div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="input-group">
                                    <div class="row">
                                        <div class="col-lg-6">
                                            <div class="input-group">
                                                <input type="text" class="form-control" name="data_recebimento_membro_de"  placeholder="De">
                                            </div><!-- /input-group -->
                                        </div><!-- /.col-lg-6 -->
                                        
                                        <div class="col-lg-6">
                                            <div class="input-group">
                                                <input type="text" class="form-control" name="data_recebimento_membro_ate" placeholder="Até">
                                            </div><!-- /input-group -->
                                        </div><!-- /.col-lg-6 -->
                                    </div><!-- /.row-->
                                </div><!-- /input-group -->
                            </div><!-- /.col-lg-6 -->
                        </div><!-- /.row -->
                    </div>
                </div>
                <div class="panel panel-default col-xs-12 col-sm-12 col-md-12 col-lg-12 item" id="box_data_batismo" style="display:none">
                    <div class="panel-heading">Data de Batismo</div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="input-group">
                                    <div class="row">
                                        <div class="col-lg-6">
                                            <div class="input-group">
                                                <input type="text" class="form-control" name="data_batismo_de" placeholder="De">
                                            </div><!-- /input-group -->
                                        </div><!-- /.col-lg-6 -->
                                        
                                        <div class="col-lg-6">
                                            <div class="input-group">
                                                <input type="text" class="form-control" name="data_batismo_ate" placeholder="Até">
                                            </div><!-- /input-group -->
                                        </div><!-- /.col-lg-6 -->
                                    </div><!-- /.row-->
                                </div><!-- /input-group -->
                            </div><!-- /.col-lg-6 -->
                        </div><!-- /.row -->
                    </div>
                </div>


                <div class="panel panel-default col-xs-12 col-sm-12 col-md-12 col-lg-12 item" id="box_data_profissao_fe" style="display:none">
                    <div class="panel-heading">Data de Profissão de fé</div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="input-group">
                                    <div class="row">
                                        <div class="col-lg-6">
                                            <div class="input-group">
                                                <input type="text" class="form-control" name="data_profissao_fe_de" placeholder="De">
                                            </div><!-- /input-group -->
                                        </div><!-- /.col-lg-6 -->
                                        
                                        <div class="col-lg-6">
                                            <div class="input-group">
                                                <input type="text" class="form-control" name="data_profissao_fe_ate" placeholder="Até">
                                            </div><!-- /input-group -->
                                        </div><!-- /.col-lg-6 -->
                                    </div><!-- /.row-->
                                </div><!-- /input-group -->
                            </div><!-- /.col-lg-6 -->
                        </div><!-- /.row -->
                    </div>
                </div>



                <div class="panel panel-default col-xs-12 col-sm-12 col-md-12 col-lg-12 item" id="box_tipo_recebimento" style="display:none">
                    <div class="panel-heading">
                        Tipo de Recebimento
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="input-group">
                                    <div class="row">
                                    <?php
                                    if($tipoRecebimento != false):
                                    foreach ($tipoRecebimento as $tipoReceb):
                                    ?>
                                        <div class="col-lg-6">
                                            <div class="input-group">
                                                <span class="input-group-addon">
                                                    <input type="checkbox" name="tipo_recebimento[]" value="<?=$tipoReceb['id_tipo_recebimento']?>">
                                                </span>
                                                <input type="text" class="form-control" value="<?=$tipoReceb['nome_tipo_recebimento']?>" readonly="readonly">
                                            </div><!-- /input-group -->
                                        </div><!-- /.col-lg-6 -->
                                    <?php
                                    endforeach;
                                    endif;
                                    ?>
                                    </div>
                                </div><!-- /input-group -->
                            </div><!-- /.col-lg-6 -->
                        </div><!-- /.row -->
                    </div>
                </div>

                <div class="panel panel-default col-xs-12 col-sm-12 col-md-12 col-lg-12 item" id="box_tipo_membro" style="display:none">
                    <div class="panel-heading">
                        Tipo de Membro
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="input-group">
                                    <div class="row">
                                        <?php
                                        if($tipoMembro != false):
                                        foreach ($tipoMembro as $tipoMemb):
                                        ?>
                                            <div class="col-lg-6">
                                                <div class="input-group">
                                                    <span class="input-group-addon">
                                                        <input type="checkbox" name="tipo_membro[]" value="<?=$tipoMemb['id_tipo_membro']?>">
                                                    </span>
                                                    <input type="text" class="form-control" value="<?=$tipoMemb['nome_tipo_membro']?>" readonly="readonly">
                                                </div><!-- /input-group -->
                                            </div><!-- /.col-lg-6 -->
                                        <?php
                                        endforeach;
                                        endif;
                                        ?>
                                    </div>
                                </div><!-- /input-group -->
                            </div><!-- /.col-lg-6 -->
                        </div><!-- /.row -->
                    </div>
                </div>


                <div class="panel panel-default col-xs-12 col-sm-12 col-md-12 col-lg-12 item" id="box_oficial_igreja" style="display:none">
                    <div class="panel-heading">
                        Oficial da igreja
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="input-group">
                                    <div class="row">
                                    <?php
                                    if($tipoOficioIgreja != false):
                                    foreach ($tipoOficioIgreja as $tipoOficIgreja):
                                    ?>
                                        <div class="col-lg-6">
                                            <div class="input-group">
                                                <span class="input-group-addon">
                                                    <input type="checkbox" name="tipo_oficial_igreja[]" value="<?=$tipoOficIgreja['id_tipo_oficio_igreja']?>">
                                                </span>
                                                <input type="text" class="form-control" value="<?=$tipoOficIgreja['nome_tipo_oficio_igreja']?>" readonly="readonly">
                                            </div><!-- /input-group -->
                                        </div><!-- /.col-lg-6 -->
                                    <?php
                                    endforeach;
                                    endif;
                                    ?>
                                    </div>
                                </div><!-- /input-group -->
                            </div><!-- /.col-lg-6 -->
                        </div><!-- /.row -->
                    </div>
                </div>

                <div class="panel panel-default col-xs-12 col-sm-12 col-md-12 col-lg-12 item" id="box_dizimista" style="display:none">
                    <div class="panel-heading">
                        Dizimista
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="input-group">
                                    <div class="row">
                                        <div class="col-lg-6">
                                            <div class="input-group">
                                                <span class="input-group-addon">
                                                    <input type="checkbox" value="Sim" name="dizimista[]">
                                                </span>
                                                <input type="text" class="form-control" value="Sim" readonly="readonly">
                                            </div><!-- /input-group -->
                                        </div><!-- /.col-lg-6 -->
                                        <div class="col-lg-6">
                                            <div class="input-group">
                                                <span class="input-group-addon">
                                                    <input type="checkbox" name="dizimista[]" value="Não">
                                                </span>
                                                <input type="text" class="form-control" value="Não" readonly="readonly" >
                                            </div><!-- /input-group -->
                                        </div><!-- /.col-lg-6 -->
                                    </div>
                                </div><!-- /input-group -->
                            </div><!-- /.col-lg-6 -->
                        </div><!-- /.row -->
                    </div>
                </div>

                <div class="panel panel-default col-xs-12 col-sm-12 col-md-12 col-lg-12 item" id="box_status" style="display:none">
                    <div class="panel-heading">
                        Status
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="input-group">
                                    <div class="row">

                                        <div class="col-lg-6">
                                            <div class="input-group">
                                                <span class="input-group-addon">
                                                    <input type="checkbox" name="status[]" value="Ativo">
                                                </span>
                                                <input type="text" class="form-control" value="Ativo" readonly="readonly">
                                            </div><!-- /input-group -->
                                        </div><!-- /.col-lg-6 -->

                                        <div class="col-lg-6">
                                            <div class="input-group">
                                                <span class="input-group-addon">
                                                    <input type="checkbox" name="status[]" value="Inativo">
                                                </span>
                                                <input type="text" class="form-control" value="Inativo" readonly="readonly">
                                            </div><!-- /input-group -->
                                        </div><!-- /.col-lg-6 -->

                                    </div>
                                </div><!-- /input-group -->
                            </div><!-- /.col-lg-6 -->
                        </div><!-- /.row -->
                    </div>
                </div>


                <div class="panel panel-default col-xs-12 col-sm-12 col-md-12 col-lg-12 item" id="box_igreja" style="display:none">
                    <div class="panel-heading">
                        Igreja
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="input-group">
                                    <div class="row">
                                    <?php
                                    if($igreja != false):
                                    foreach ($igreja as $igre):
                                    ?>
                                        <div class="col-lg-6">
                                            <div class="input-group">
                                                <span class="input-group-addon">
                                                    <input type="checkbox" name="igreja[]" value="<?=$igre['id_igreja']?>">
                                                </span>
                                                <input type="text" class="form-control" value="<?=$igre['nome_igreja']?>" readonly="readonly">
                                            </div><!-- /input-group -->
                                        </div><!-- /.col-lg-6 -->
                                    <?php
                                    endforeach;
                                    endif;
                                    ?>
                                    </div>
                                </div><!-- /input-group -->
                            </div><!-- /.col-lg-6 -->
                        </div><!-- /.row -->
                    </div>
                </div>



                <div class="panel panel-default col-xs-12 col-sm-12 col-md-12 col-lg-12 item" id="box_data_cadastro" style="display:none">
                    <div class="panel-heading">Data de Cadastro</div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="input-group">
                                    <div class="row">
                                        <div class="col-lg-6">
                                            <div class="input-group">
                                                <input type="text" class="form-control" name="data_cadastro_de" placeholder="De">
                                            </div><!-- /input-group -->
                                        </div><!-- /.col-lg-6 -->
                                        
                                        <div class="col-lg-6">
                                            <div class="input-group">
                                                <input type="text" class="form-control" name="data_cadastro_ate" placeholder="Até">
                                            </div><!-- /input-group -->
                                        </div><!-- /.col-lg-6 -->
                                    </div><!-- /.row-->
                                </div><!-- /input-group -->
                            </div><!-- /.col-lg-6 -->
                        </div><!-- /.row -->
                    </div>
                </div>


                <div class="panel panel-default col-xs-12 col-sm-12 col-md-12 col-lg-12 item" id="box_busca_especifica" style="display:none">
                    <div class="panel-heading">Busca Específica</div>
                    <div class="panel-body">
                        <div class="col-lg-12">
                            <input type="text" class="form-control" name="busca_especifica" placeholder="Busca específica">
                        </div><!-- /.col-lg-6 -->
                    </div>
                </div>

                <div class="panel panel-default col-xs-12 col-sm-12 col-md-12 col-lg-12 item">
                    <a href="javascript:void(0)" class="btn btn-default proximo2" style="float:right">Próximo</a>
                </div>
            </div>


            <div class="content" id="container3" style="display:none">
                <div class="panel panel-default col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <a href="javascript:void(0)" class="btn btn-default voltar2" style="float:right">Voltar</a>
                </div>
                <div class="panel panel-default col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="panel-body">
                        <header class="box_header">
                            <h2>Campos da tabela:</h2>
                        </header>
                        <select class="col-xs-12 col-sm-5 col-md-5 col-lg-5" multiple="multiple" name="selCampos1" id="selCampos1" size="10">
                            <option value="nome">Nome</option>
                            <option value="sobrenome">Sobrenome</option>
                            <option value="data_nascimento">Data de Nascimento</option>
                            <option value="sexo">Sexo</option>
                            <option value="rg">RG</option>
                            <option value="cpf">CPF</option>
                            <option value="estado_civil">Estado Civil</option>
                            <option value="data_casamento">Data de Casamento</option>
                            <option value="endereco">Endereço</option>
                            <option value="telefones">Telefones</option>
                            <option value="email">E-mails</option>
                            <option value="profissao">Profissão</option>
                            <option value="igreja">Igreja</option>
                            <option value="num_rol">Nº Rol</option>
                            <option value="data_recebimento_membro">Data de recebimento como membro</option>
                            <option value="data_batismo">Data do batismo</option>
                            <option value="data_profissao_fe">Data da profissão de fé</option>
                            <option value="celebrante_batismo">Celebrante do batismo</option>
                            <option value="local_batismo">Local do batismo</option>
                            <option value="tipo_recebimento">Tipo de recebimento</option>
                            <option value="tipo_membro">Tipo de membro</option>
                            <option value="oficial_igreja">Oficial da Igreja</option>
                            <option value="dizimista">Dizimista</option>
                            <option value="data_cadastro">Data de cadastro</option>
                            <option value="status">Status</option>
                        </select>
                        <div class="col-xs-12 col-sm-2 col-md-2 col-lg-2 text-center">
                            <a href="javascript:void(0)" onclick="insertSelected(getElementById('selCampos2'), getElementById('selCampos1'));" class="btn btn-default" id="transferLeft"> <span class="glyphicon glyphicon-chevron-left"></span> </a>
                            <a href="javascript:void(0)" onclick="insertSelected(getElementById('selCampos1'), getElementById('selCampos2'));" class="btn btn-default" id="transferRight"> <span class="glyphicon glyphicon-chevron-right"></span> </a>
                        </div>

                        <select name="selCampos2" id="selCampos2" size="10" multiple="multiple" class="col-xs-12 col-sm-5 col-md-5 col-lg-5">

                        </select>
                    </div>

                </div>
                <div class="panel panel-default col-xs-12 col-sm-12 col-md-12 col-lg-12 item">
                    <a href="javascript:void(0)" class="btn btn-default previsualizar" style="float:right">Pré-visualizar Relatório</a>
                </div>
            </div>
        </div>
        <!--/DADOS PESSOAIS-->


        <div class="content" id="container4">
            <div class="panel panel-default col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <a href="javascript:void(0)" class="btn btn-default voltar3" style="float:right">Voltar</a>
            </div>
            <div class="list">

            </div>

            <div class="col-lg-12">
                <input type="text" class="form-control" name="nome_relatorio" placeholder="Nome do relatório">
            </div><!-- /.col-lg-6 -->

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-success btn_salvar"><span class="glyphicon glyphicon-ok"></span> Cadastrar</button>
                </div>
            </div>
        </div>

    </form>
</div>


<script type="text/javascript" src="<?=URL?>js/jquery.validate.js"></script>
<script type="text/javascript" src="<?=URL?>js/jquery.maskedinput.min.js"></script>

<script type="text/javascript">
    $(function(){

        function dateToFrom(from,to)
        {
            $( from ).datepicker({
              defaultDate: "+1w",
              changeMonth: true,
              changeYear: true,
              numberOfMonths: 1,
              dateFormat: 'dd/mm/yy',
              showButtonPanel: true,
              onClose: function( selectedDate ) {
                $( to ).datepicker( "option", "minDate", selectedDate );
              }
            });
            $( to ).datepicker({
              defaultDate: "+1w",
              changeMonth: true,
              changeYear: true,
              numberOfMonths: 1,
              dateFormat: 'dd/mm/yy',
              showButtonPanel: true,
              onClose: function( selectedDate ) {
                $( from ).datepicker( "option", "maxDate", selectedDate );
              }
            });
        }


        dateToFrom("input[name=data_nascimento_de]", "input[name=data_nascimento_ate]");
        dateToFrom("input[name=data_casamento_de]", "input[name=data_casamento_ate]");
        dateToFrom("input[name=data_recebimento_membro_de]", "input[name=data_recebimento_membro_ate]");
        dateToFrom("input[name=data_batismo_de]", "input[name=data_batismo_ate]");
        dateToFrom("input[name=data_profissao_fe_de]", "input[name=data_profissao_fe_ate]");
        dateToFrom("input[name=data_cadastro_de]", "input[name=data_cadastro_ate]");
        

        //mascaras de campos
            
        $('.voltar1').click(function(event) {
            $('#container2').slideUp();
            $('#container1').slideDown();
        });

        $('.voltar2').click(function(event) {
            $('#container3').slideUp();
            $('#container2').slideDown();
        });

        $('.voltar3').click(function(event) {
            $('#container4').slideUp();
            $('#container3').slideDown();
        });



        $('.proximo1').click(function(event) {
            $('select[name=sel1] option').each(function(){
                $('#box_'+$(this).attr('value')+'').hide();  
            });
            $('select[name=sel2] option').each(function(){
                $('#box_'+$(this).attr('value')+'').show();  
            });

            $('#container1').slideUp();
            $('#container2').slideDown();
        });

        $('.proximo2').click(function(event) {
            $('#container2').slideUp();
            $('#container3').slideDown();
        });
        
        $('.previsualizar').click(function(event) {
            event.preventDefault();
            $('input, select, textarea','#form_gera_relatorio').css('box-shadow','none');
            $('.generalErrors .alert').html('');
            $('.generalErrors').hide();

            $('#container3').slideUp();
            //$('#container2').slideUp();
            var campos = Array();
            $('select[name=sel2] option').each(function(){
                campos.push($(this).attr('value'));
            });

            var camposTh = Array();
            $('select[name=selCampos2] option').each(function(){
                camposTh.push($(this).attr('value'));
            });

         
            $.post('<?=URL?>rol-de-membros/relatorios/relatorio_especifico/previsualizarRelatorio',  $('#form_gera_relatorio').serialize()+'&'+$.param({'campos': campos, 'camposTh':camposTh})).done(function( data ) {
                data = $.parseJSON(data);
                if(data.result == true){
                    $('#container4 .list').html(data.tabela);
                    $('#container4').slideDown();

                    var table = $('.table').DataTable({
                        order: [1,'asc']
                    });
                }else{
                    $('#container4').slideDown();
                    data = data.error;
                    $('.generalErrors').show();
                    $.each(data, function(index, error) {
                        $.each(error, function(index, value) {
                            var value = ''+value;
                            var values = value.split(',');
                            $.each(values, function(id, val) {
                                $('.generalErrors .alert').append('<p>'+val+'</p>');
                            });
                            $('[name='+index+']','#form_gera_relatorio').css('box-shadow','0 0 1px 1px #F00');
                        });
                    });
                    var erroTop = ($('.generalErrors').offset().top)
                    $('body,html').animate({scrollTop : erroTop},600);
                }

            });
           
        });


        $('.btn_salvar').click(function(){
            event.preventDefault();
            $('input, select, textarea','#form_gera_relatorio').css('box-shadow','none');
            $('.generalErrors .alert').html('');
            $('.generalErrors').hide();

            $('#container3').slideUp();
            //$('#container2').slideUp();
            var campos = Array();
            $('select[name=sel2] option').each(function(){
                campos.push($(this).attr('value'));
            });

            var camposTh = Array();
            $('select[name=selCampos2] option').each(function(){
                camposTh.push($(this).attr('value'));
            });
            $.post('<?=URL?>rol-de-membros/relatorios/relatorio_especifico/previsualizarRelatorio',  $('#form_gera_relatorio').serialize()+'&'+$.param({'campos': campos, 'camposTh':camposTh, 'action' : 'Salvar'  })).done(function( data ) {
                console.log(data)
                if(data == true)
                {
                    location.reload();
                }
                //data = $.parseJSON(data);
                /*if(data.result == true){
                    $('#container4 .list').html(data.tabela);
                    $('#container4').slideDown();

                    var table = $('.table').DataTable({
                        order: [1,'asc']
                    });
                }else{
                    $('#container4').slideDown();
                    data = data.error;
                    $('.generalErrors').show();
                    $.each(data, function(index, error) {
                        $.each(error, function(index, value) {
                            var value = ''+value;
                            var values = value.split(',');
                            $.each(values, function(id, val) {
                                $('.generalErrors .alert').append('<p>'+val+'</p>');
                            });
                            $('[name='+index+']','#form_gera_relatorio').css('box-shadow','0 0 1px 1px #F00');
                        });
                    });
                    var erroTop = ($('.generalErrors').offset().top)
                    $('body,html').animate({scrollTop : erroTop},600);
                }*/

            });
        })

    });
</script>

<style type="text/css">
#container4{
    clear: both;
    display: none;
    /*position: fixed;*/
    left: 0;
    z-index: 9999;
    background: rgba(255, 255, 255, 255);
    top: 0;
    bottom: 0;
    overflow: auto;
    width: 100%;
    text-align: left;
}

#container4 .panel{
  /*position: fixed;*/
}
#container4 .list{
    margin-top: 50px;
}
#container4 .list table{
  background: #EEE;
}

#tablePrevisualizar th{
    /*white-space: nowrap;*/
    background: #B6B6B6;
    text-align: center;
}

.ui-button{
    display: none;
}
.ui-datepicker{
    z-index: 2!important;
}
</style>




     
<script language="javascript">
function insertSelected(campoOrig, campoDest){
    x = campoOrig.value;
    if (x == "") {
        alert("Selecione um Item"); 
        return;
    }
    Origem = campoOrig;
    Destino = campoDest;
    var len = Destino.length;
    for (var i = 0; i < Origem.length; i++) {
        if ((Origem.options[i] != null) && (Origem.options[i].selected)) {
            Destino.options[len] = new Option(Origem.options[i].text, Origem.options[i].value);
            len++;
            Origem.options[i] = null;
            i--;
        }
    }
    return false;
}
</script>