<?php
$template = new template();
?>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <?=$template->page_header('Lista de relatórios específicos');?>
    <?php
        //page-header
        $btnAdiconar = $template->btnAdicionarRegistro(URL.'rol-de-membros/relatorios/relatorio_especifico/cadastrar','<span class="glyphicon glyphicon-list-alt"></span> Adicionar relatório');
    
        echo $template->actions_buttons($btnAdiconar);
    ?>
    <div class="middle-content">
        <?php
        $thead = '  <tr>   
                        <th width="160">Nome</th>
                        <th width="100">Data registrada</th>
                        <th width="100">Autor</th>
                        <th width="100">Ações</th>
                    </tr>';
        $tfoot = '  <tr>
                        <th>Nome</th>
                        <th>Data registrada</th>
                        <th>Autor</th>
                        <th>Ações</th>
                    </tr>';	 
        if($relatorios != false):
            $tbody = '';
            foreach ($relatorios as $relatorio):
                $tbody .='  <tr id="'.$relatorio['id_relatorio_especifico'].'">
                                <td>'.$relatorio['nome_relatorio'].'</td>
                                <td>'.date('d/m/Y', strtotime($relatorio['data_cadastro_relatorio'])).'</td>
                                <td>'.$relatorio['autor_relatorio'].'</td>
                                <td>
                                    '.$template->btnVisualizarRegistro(URL.'rol-de-membros/relatorios/relatorio_especifico/visualizar/'.$relatorio['id_relatorio_especifico']).
                                    $template->btnExcluirRegistro('javascript:void(0)',$relatorio['id_relatorio_especifico']).
                                '</td>
                            </tr>';
                

            endforeach;
            echo $template->tabela($thead, $tfoot, $tbody);
        else:
            echo '<h2>Não há registros cadastrados</h2>';
        endif;
        ?>
    </div>

</div>
<script>
$(document).ready(function() {
    var table = $('.dataTable').DataTable({
    	order: []
    });
    table.$('.btn_excluir').on('click',function(){
        var id = $(this).attr('id');
        var status = 'Excluído';

        $("#dialogResult").html('Deseja mesmo excluir?');
		$("#dialogResult").dialog({
			autoOpen: true,
			buttons: [
				{
					text: "Ok",
					click: function() {
						$( this ).dialog( "close" );

				    	$.post(url+'rol-de-membros/relatorios/relatorio_especifico/atualizarStatus',{id:id,status:status},function(data){
							console.log(data);
                            if(data == true){
								$('tr#'+id).hide();
                                $("#dialogResult").html('Registro enviado para a lixeira');
                                $("#dialogResult").dialog({
                                    autoOpen: true,
                                    buttons: [
                                        {
                                            text: "Ok",
                                            click: function() {
                                                $( this ).dialog( "close" );
                                            }
                                        }
                                    ]
                                });


                            }
						});
					}
				},
				{
					text: "Cancelar",
					click: function() {
						$( this ).dialog( "close" );
					}
				}
			]
		});



		
        
    });

    table.$('input[name=status]').on('change',function(){
    	var id = $(this).attr('id')
    	var status = 'Inativo';
		if($(this).is(':checked'))
			status = 'Ativo';

		$.post(url+'rol-de-membros/home/atualizarStatus',{id:id,status:status},function(data){
            
		});

    });


});
</script>