<?php
$template = new template();
?>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" id="rol_membros">
    <?=$template->page_header('Visualizar Relatório: <small>'.$relatorio['nome_relatorio'].'</small>');?>
    <?php
        //page-header
        $btnAdiconar = $template->btnVoltar(URL.'rol-de-membros/relatorios/relatorio_especifico');
        $btnConverterToXls = $template->btnConvetToXls(URL.'rol-de-membros/relatorios/relatorio_especifico/convertToXls/'.$id_relatorio);
        $btnConverterToPdf = $template->btnConvetToPdf(URL.'rol-de-membros/relatorios/relatorio_especifico/convertToPdf/'.$id_relatorio);
        echo $template->actions_buttons($btnAdiconar.$btnConverterToXls.$btnConverterToPdf);
    ?>

    <div class="relatorioView" style="text-align:left">
        <h4>Autor: <?=$relatorio['autor_relatorio']?></h4>
        <?php
        $dataFormat = new dataFormat();
        ?>
        <h4>Data: <?=$dataFormat->formatar($relatorio['data_cadastro_relatorio'],'datahora')?></h4>
        <?php
        $tabelaRelatorio = json_decode($relatorio['content_relatorio'],true);
        $thead = '';
        $tfoot = '';
        $tbody = '';
        $th = '';
        $td = '';
        foreach ($tabelaRelatorio['thead'] as $thead)
        {
            $th .= '<th>'.$thead.'</th>';
        }

        foreach ($tabelaRelatorio['tbody'] as $tbody)
        {
            $td .= '<tr>';
            foreach ($tbody as $value) 
            {
                $td .= '<td>'.$value.'</td>';    
            }
            $td .='</tr>';
        }


        $thead = $th;
        $tfoot = $th;
        $tbody = $td;
        echo $template->simplesTabela($thead, $tfoot, $tbody, 'id="tablePrevisualizar"');
        ?>
    </div>
</div>
<script type="text/javascript">
    $(function(){
        var table = $('.table').DataTable({
            order: []
        });
    })

</script>
