<div class="container">
    <?php
       $btnVoltar = $this->templateFactory->getButton("voltar",array('href'=>URL.'suprimentos/requisicoes'));
        echo $this->templateFactory->getButton("actions_buttons",array('buttons'=>$btnVoltar));    
    ?>
    <div class="page-header">
      <h1>Requisições<small> Cadastro</small></h1>
    </div>
    <form action="<?=URL?>suprimentos/requisicoes/gerenciar/inserir" method="post" id="form_pedido">
        <div class="panel panel-default">
            <div class="panel-heading">Dados Gerais</div>
            <div class="panel-body">
                
                
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Código</span>
                    <input type="text" class="form-control" placeholder="Código" name="codigo" >
                </div>
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Produtos</span>
                    <select name="listaproduto" class="form-control">
                        <?php if(!empty($produtos)):?>
                        <?php foreach ($produtos as $produto):?>
                        <option value="<?= $produto->getId()?>"><?=$produto->getNome()?></option>
                        <?php endforeach;?>
                        <?php endif;?>
                    </select>
                    <span class="input-group-addon" id="basic-addon1"><a href="javascript:void(0)" class="addProduto"><span class="glyphicons glyphicons-plus"></span></a></span>
                </div>
                <div class="listProdutos">
                </div>


                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Nome</span>
                    <input type="text" class="form-control" placeholder="Nome" name="nome" >
                </div>
                <div class="btn-group pull-right" role="group">
                    <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-ok"></span> Salvar</button>
                </div>
            </div>
        </div>
    </form>
</div>

<script type="text/javascript" src="<?=URL?>skin/js/uploadForm.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/orcamentos/pedidos/cadastrar.js"></script>
