<div class="container">
    <?php

        $btnCadastrar = $this->templateFactory->getButton("cadastrar",array('href'=>URL.'suprimentos/requisicoes/gerenciar/cadastrar'), URL.'suprimentos/requisicoes/gerenciar/cadastrar');
        echo $this->templateFactory->getButton("actions_buttons",array('buttons'=>$btnCadastrar));
    ?>
    <div class="page-header">
      <h1>Requisições Automáticas e Manuais</h1>
    </div>
    <div class="middle-content">
        <?php
            $thead = '  <tr>
                            <th width="100">Código</th>
                            <th width="160">Usuário</th>
                            <th width="160">Titulo</th>
                            <th width="160">Data</th>
                            <th width="160">Status</th>
                            <th width="180">Ações</th>
                        </tr>';
            $tfoot = '  <tr>
                            <td width="100">Código</td>
                            <td width="160">Usuário</td>
                            <td width="160">Titulo</td>
                            <td width="160">Data</td>
                            <td width="160">Status</td>
                            <td width="180">Ações</td>
                        </tr>';  

                $tbody = '';
                foreach ($requisicoes as $requisicao):

                    $ativo = ($requisicao->getStatus() == status::ATIVO) ? 'selected="selected"' : '';
                    $inativo = ($requisicao->getStatus() == status::INATIVO) ? 'selected="selected"' : '';
                    
            $tbody .='  <tr id="'.$requisicao->getId().'">
                            <td>'.$requisicao->getCodigo().'</td>
                            <td>'.$requisicao->getUsuarioCadastrado().'</td>
                            <td>'.$requisicao->getTitulo().'</td>
                            <td>'.$requisicao->getData().'</td>
                            <td>
                                <select name="status" id="'.$requisicao->getId().'" class="statusSelect">
                                    <option value="'.status::ATIVO.'" class="active" '.$ativo.'>Ativo</option>
                                    <option value="'.status::INATIVO.'" class="inactive" '.$inativo.'>Inativo</option>
                                </select>
                            </td>
                            <td>'
                                .$this->templateFactory->getButton('cancelar', array('id'=> $requisicao->getId()), URL.'funcionarios/gerenciar/excluir/').
                                $this->templateFactory->getButton('cotar',array('id'=> $requisicao->getId()), URL.'funcionarios/gerenciar/excluir/').
                            '</td>
                        </tr>';
                endforeach;
                echo $this->templateFactory->getTable('tabela', array('thead'=>$thead, 'tfoot'=>$tfoot, 'tbody'=>$tbody));
            ?>
        
            </tbody>
        </table>
    </div>

</div>

<script type="text/javascript">
    $(function(){
        //DATATABLE
        var table = $('.dataTable').DataTable({
            order: [0,'asc']
        });

        //EXCLUIR
        table.$('.btn_cancelar').on('click',function(){
            var id = $(this).attr('id');
            var status = $(this).data('value');
            var modalDelete = $('#modalDelete').modal('show')
            $('.btn_ok','#modalDelete').on('click', function(event) {
                $.post(url+'suprimentos/requisicoes/gerenciar/cancelar',{id:id,status:status},function(data){
                    console.log(data)
                    if(data == true){
                        $('#modalDelete').modal('hide');
                        $('tr#'+id).hide();
                    }
                });
            });
        });


    })
</script>

