<?php
$template = new template();
?>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" id="rol_membros">
    <?=$template->page_header('Cadastrar igreja');?>
    <?php
        //page-header
        $btnAdiconar = $template->btnVoltar(URL.'igreja/home/');
        echo $template->actions_buttons($btnAdiconar);
    ?>

    <div class="panel generalErrors panel-danger" style="text-align:left; display:none;  background-color: #f2dede;">
        <h4 class="panel-heading">Ocorreu(ram) o(s) seguinte(s) erro(s):</h4>
        <div class="alert alert-danger" role="alert">
        </div>
    </div>

    <form id="form_cadastro_igreja" action="<?=URL?>igreja/home/inserir" method="POST">
        <div class="form-group">
            <input type="text" name="nome" placeholder="Nome" class="form-control" />
        </div>
        <!--<div class="group_input">-->
        <div class="form-group">
            <input type="text" name="cep" placeholder="CEP" class="form-control" id="cep"/>
        </div>
        <div class="form-group">
            <input type="text" name="rua" placeholder="Rua" class="form-control" id="rua"/>
        </div>
        <div class="form-group">
            <input type="text" name="numero" placeholder="Número" class="form-control" />
        </div>
        <div class="form-group">
            <input type="text" name="complemento" placeholder="Complemento" class="form-control" />
        </div>
        <div class="form-group">
            <input type="text" name="bairro" placeholder="Bairro" class="form-control" id="bairro"/>
        </div>
        <div class="form-group">
            <input type="text" name="cidade" placeholder="Cidade" class="form-control" id="cidade"/>
        </div>

        <div class="form-group">
            <select name="estado" class="form-control" id="uf">
                 <option value="AC">AC - Acre</option>
                 <option value="AL">AL - Alagoas</option>
                 <option value="AP">AP - Amapá</option>
                 <option value="AM">AM - Amazonas</option>
                 <option value="BA">BA - Bahia</option>
                 <option value="CE">CE - Ceará</option>
                 <option value="DF">DF - Distrito Federal</option>
                 <option value="GO">GO - Goiás</option>
                 <option value="ES">ES - Espírito Santo</option>
                 <option value="MA">MA - Maranhão</option>
                 <option value="MT">MT - Mato Grosso</option>
                 <option value="MS">MS - Mato Grosso do Sul</option>
                 <option value="MG">MG - Minas Gerais</option>
                 <option value="PA">PA - Pará</option>
                 <option value="PB">PB - Paraiba</option>
                 <option value="PR">PR - Paraná</option>
                 <option value="PE">PE - Pernambuco</option>
                 <option value="PI">PI - Piauí­</option>
                 <option value="RJ">RJ - Rio de Janeiro</option>
                 <option value="RN">RN - Rio Grande do Norte</option>
                 <option value="RS">RS - Rio Grande do Sul</option>
                 <option value="RO">RO - Rondônia</option>
                 <option value="RR">RR - Roraima</option>
                 <option value="SP">SP - São Paulo</option>
                 <option value="SC">SC - Santa Catarina</option>
                 <option value="SE">SE - Sergipe</option>
                 <option value="TO">TO - Tocantins</option>
            </select>
        </div>

        <div id="defaultCampos">
            <div class="radio telefones" id="defaultTel" style="margin-bottom:5px;display:none">
                <span class="input-group-addon">
                    <a href="javascript:void(0)" class="delCel" style="float:right"><img src="<?=URL?>img/close.png"></a>
                    <input type="text" name="telefone" placeholder="Telefone" class="form-control" />
                    <input type="text" name="operadora" placeholder="Operadora" class="form-control" />
                </span>
            </div>
        </div>

        <div class="form-group group_tel">
            <a href="javascript:void(0)" class="addTel addCel"><span class="glyphicon glyphicon-phone-alt"></span> Adicionar telefones</a>
        </div>


        <div class="form-group">
            <input type="text" name="data_fundacao" placeholder="Data de fundação" class="form-control" />
        </div>

        <div class="form-group">
            <select name="tipo_igreja" class="form-control">
                <option value="Sede">Sede</option>
                <option value="Congregação">Congregação</option>
            </select>
        </div>

        <div class="form-group">
            <input type="text" name="cnpj" placeholder="CNPJ" class="form-control" />
        </div>

        <div class="form-group">
            <input type="text" name="pastor" placeholder="Pastor" class="form-control" />
        </div>

        <div class="form-group">
            <div class="col-sm-12">
                <button type="submit" class="btn btn-success btn_cadastrar"><span class="glyphicon glyphicon-ok"></span> Cadastrar</button>
            </div>
        </div>
   </form>
</div>
<script type="text/javascript" src="<?=URL?>js/jquery.validate.js"></script>
<script type="text/javascript" src="<?=URL?>js/jquery.maskedinput.min.js"></script>
<script type="text/javascript">
    $(function(){
        //telefone
        $('.addTel').on('click',function(){
            var error = 0;
            var campTel = $('#defaultCampos #defaultTel').clone().removeAttr('id').removeAttr('style');
            campTel.find('input').val('');
            $(this).before(campTel);
        });
        
        $(document).on('click','.delCel',function(){
            $(this).parent().parent().remove();
        });


        $('input[name=data_fundacao]').datepicker({ dateFormat: 'dd/mm/yy' });
        $('input[name=cep]').wvmask('cep')
        $('input[name=numero]').wvmask('numero')
        $('input[name=cnpj]').mask('999.999.999-99');
        //mascara para telefones de 8 e 9 dígitos
        var maskBehavior = function (val) {
            return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
        },
        options = {onKeyPress: function(val, e, field, options) {
            field.mask(maskBehavior.apply({}, arguments), options);
            }
        };
        $('input[name=telefone]').mask(maskBehavior, options);

        $('#form_cadastro_igreja').validaCep();

        $('#form_cadastro_igreja').ajaxSubmit.debug=true;

        $('#form_cadastro_igreja').submit(function(){
            var telefones = Object();
            //telefones
            var iTel = 0;
            $('.group_tel .telefones').each(function(){
                var aux = Object();
                var telefone = $('input[name=telefone]',this).val();
                var operadora = $('input[name=operadora]',this).val();

                aux['telefone'] = telefone;
                aux['operadora'] = operadora;

                telefones[iTel] = aux;
                iTel++;
            });
            var parameters = Object();
                parameters['telefones'] = telefones;
                console.log(telefones)
            $('#form_cadastro_igreja').uploadForm({
                'parameters': parameters
            });
            return false;
        });

        


    });

</script>