<?php
$template = new template();
?>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" id="rol_membros">
    <?=$template->page_header('Editar igreja');?>
    <?php
        //page-header
        $btnAdiconar = $template->btnVoltar(URL.'igreja/home/');
        echo $template->actions_buttons($btnAdiconar);
    ?>

    <div class="panel generalErrors panel-danger" style="text-align:left; display:none;  background-color: #f2dede;">
        <h4 class="panel-heading">Ocorreu(ram) o(s) seguinte(s) erro(s):</h4>
        <div class="alert alert-danger" role="alert">
        </div>
    </div>

    <form id="form_cadastro_igreja" action="<?=URL?>igreja/home/atualizar" method="POST">
        <div class="form-group">
            <input type="text" name="nome" placeholder="Nome" class="form-control" value="<?=$igreja['nome_igreja']?>"/>
        </div>
        <!--<div class="group_input">-->
        <div class="form-group">
            <input type="text" name="cep" placeholder="CEP" class="form-control" id="cep"  value="<?=$igreja['cep_igreja']?>"/>
        </div>
        <div class="form-group">
            <input type="text" name="rua" placeholder="Rua" class="form-control" id="rua"  value="<?=$igreja['rua_igreja']?>"/>
        </div>
        <div class="form-group">
            <input type="text" name="numero" placeholder="Número" class="form-control"  value="<?=$igreja['numero_igreja']?>"/>
        </div>
        <div class="form-group">
            <input type="text" name="complemento" placeholder="Complemento" class="form-control"  value="<?=$igreja['complemento_igreja']?>"/>
        </div>
        <div class="form-group">
            <input type="text" name="bairro" placeholder="Bairro" class="form-control" id="bairro"  value="<?=$igreja['bairro_igreja']?>"/>
        </div>
        <div class="form-group">
            <input type="text" name="cidade" placeholder="Cidade" class="form-control" id="cidade"  value="<?=$igreja['cidade_igreja']?>"/>
        </div>
        <?php
        $estados = array('AC'=>'','AL'=>'','AP'=>'','AM'=>'','BA'=>'','CE'=>'','DF'=>'','GO'=>'','ES'=>'','MA'=>'','MT'=>'','MS'=>'','MG'=>'','PA'=>'','PB'=>'','PR'=>'','PE'=>'','PI'=>'','RJ'=>'','RN'=>'','RS'=>'','RO'=>'','RR'=>'','SP'=>'','SC'=>'','SE'=>'','TO'=>'');
        extract($estados);
        if($igreja['estado_igreja'] != '')
            $$igreja['estado_igreja'];
        ?>
        <div class="form-group">
            <select name="estado" class="form-control" id="uf">
                <option value="AC" <?=$AC?>>AC - Acre</option>
                <option value="AL" <?=$AL?>>AL - Alagoas</option>
                <option value="AP" <?=$AP?>>AP - Amapá</option>
                <option value="AM" <?=$AM?>>AM - Amazonas</option>
                <option value="BA" <?=$BA?>>BA - Bahia</option>
                <option value="CE" <?=$CE?>>CE - Ceará</option>
                <option value="DF" <?=$DF?>>DF - Distrito Federal</option>
                <option value="GO" <?=$GO?>>GO - Goiás</option>
                <option value="ES" <?=$ES?>>ES - Espírito Santo</option>
                <option value="MA" <?=$MA?>>MA - Maranhão</option>
                <option value="MT" <?=$MT?>>MT - Mato Grosso</option>
                <option value="MS" <?=$MS?>>MS - Mato Grosso do Sul</option>
                <option value="MG" <?=$MG?>>MG - Minas Gerais</option>
                <option value="PA" <?=$PA?>>PA - Pará</option>
                <option value="PB" <?=$PB?>>PB - Paraiba</option>
                <option value="PR" <?=$PR?>>PR - Paraná</option>
                <option value="PE" <?=$PE?>>PE - Pernambuco</option>
                <option value="PI" <?=$PI?>>PI - Piauí­</option>
                <option value="RJ" <?=$RJ?>>RJ - Rio de Janeiro</option>
                <option value="RN" <?=$RN?>>RN - Rio Grande do Norte</option>
                <option value="RS" <?=$RS?>>RS - Rio Grande do Sul</option>
                <option value="RO" <?=$RO?>>RO - Rondônia</option>
                <option value="RR" <?=$RR?>>RR - Roraima</option>
                <option value="SP" <?=$SP?>>SP - São Paulo</option>
                <option value="SC" <?=$SC?>>SC - Santa Catarina</option>
                <option value="SE" <?=$SE?>>SE - Sergipe</option>
                <option value="TO" <?=$TO?>>TO - Tocantins</option>
            </select>
        </div>

        <div id="defaultCampos">
            <div class="radio telefones" id="defaultTel" style="margin-bottom:5px;display:none">
                <span class="input-group-addon">
                    <a href="javascript:void(0)" class="delCel" style="float:right"><img src="<?=URL?>img/close.png"></a>
                    <input type="hidden" name="id_telefone" placeholder="Id" class="form-control" value="" />
                    <input type="text" name="telefone" placeholder="Telefone" class="form-control" />
                    <input type="text" name="operadora" placeholder="Operadora" class="form-control" />
                </span>
            </div>
        </div>

        <div class="form-group group_tel">
            <?php
            if($telefones != false):
            foreach ($telefones as $telefone):
            ?>
            <div class="radio telefones" id="defaultTel" style="margin-bottom:5px;">
                <span class="input-group-addon">
                    <a href="javascript:void(0)" class="delCel" style="float:right" id="<?=$telefone['id_telefone_igreja']?>"><img src="<?=URL?>img/close.png"></a>
                    <input type="hidden" name="id_telefone" placeholder="Id" class="form-control" value="<?=$telefone['id_telefone_igreja']?>" />
                    <input type="text" name="telefone" placeholder="Telefone" class="form-control" value="<?=$telefone['telefone_igreja']?>"/>
                    <input type="text" name="operadora" placeholder="Operadora" class="form-control" value="<?=$telefone['operadora_igreja']?>"/>
                </span>
            </div>
            <?php
            endforeach;
            endif;
            ?>

            <a href="javascript:void(0)" class="addTel addCel"><span class="glyphicon glyphicon-phone-alt"></span> Adicionar telefones</a>
        </div>

        <?php
        $dataFormat = new dataFormat();
        ?>
        <div class="form-group">
            <input type="text" name="data_fundacao" placeholder="Data de fundação" class="form-control" value="<?=$dataFormat->formatar($igreja['data_fundacao'],'data')?>" />
        </div>
        
        <div class="form-group">
            <select name="tipo_igreja" class="form-control">
                <option value="Sede" <?=($igreja['tipo_igreja'] == 'Sede') ? 'selected' : ''?>>Sede</option>
                <option value="Congregação" <?=($igreja['tipo_igreja'] == 'Congregação') ? 'selected' : ''?>>Congregação</option>
            </select>
        </div>

        <div class="form-group">
            <input type="text" name="cnpj" placeholder="CNPJ" class="form-control" value="<?=$igreja['cnpj']?>"/>
        </div>

        <div class="form-group">
            <input type="text" name="pastor" placeholder="Pastor" class="form-control" value="<?=$igreja['pastor']?>"/>
        </div>

        <div class="form-group">
            <div class="col-sm-12">
                <input type="hidden" name="id" value="<?=$igreja['id_igreja']?>">
                <button type="submit" class="btn btn-success btn_cadastrar"><span class="glyphicon glyphicon-ok"></span> Cadastrar</button>
            </div>
        </div>
   </form>
</div>
<script type="text/javascript" src="<?=URL?>js/jquery.validate.js"></script>
<script type="text/javascript" src="<?=URL?>js/jquery.maskedinput.min.js"></script>
<script type="text/javascript">
    $(function(){
        $('input[name=data_fundacao]').datepicker({ dateFormat: 'dd/mm/yy' });
        $('input[name=cep]').wvmask('cep')
        $('input[name=numero]').wvmask('numero')
        $('input[name=cnpj]').mask('999.999.999-99');
        //mascara para telefones de 8 e 9 dígitos
        var maskBehavior = function (val) {
            return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
        },
        options = {onKeyPress: function(val, e, field, options) {
            field.mask(maskBehavior.apply({}, arguments), options);
            }
        };
        $('input[name=telefone]').mask(maskBehavior, options);
        //telefone
        $('.addTel').on('click',function(){
            var error = 0;
            var campTel = $('#defaultCampos #defaultTel').clone().removeAttr('id').removeAttr('style');
            campTel.find('input').val('');
            $(this).before(campTel);
            $('input[name=telefone]').mask(maskBehavior, options);
        });
        
        var listTelExcluir = Array();
        $(document).on('click','.delCel',function(){
            $(this).parent().parent().remove();
            if($(this).attr('id') != '')
                listTelExcluir.push($(this).attr('id'));
        });



        $('#form_cadastro_igreja').validaCep();

        $('#form_cadastro_igreja').ajaxSubmit.debug=true;



        $('#form_cadastro_igreja').submit(function(){
            var telefones = Object();
            //telefones
            var iTel = 0;
            $('.group_tel .telefones').each(function(){
                var aux = Object();
                var id = $('input[name=id_telefone]',this).val();
                var telefone = $('input[name=telefone]',this).val();
                var operadora = $('input[name=operadora]',this).val();

                aux['id_telefone'] = id;
                aux['telefone'] = telefone;
                aux['operadora'] = operadora;

                telefones[iTel] = aux;
                iTel++;
            });
            var parameters = Object();
                parameters['telefones'] = telefones;
                parameters['listTelExcluir'] = listTelExcluir;

            $('#form_cadastro_igreja').uploadForm({
                'parameters': parameters,
                'reload' : true,
                'resetform' :false
            });
            return false;
        });
    });
</script>