<?php
$template = new template();
?>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <?=$template->page_header('Lista das igrejas');?>
    <?php
        //page-header
        $btnAdiconar = $template->btnAdicionarRegistro(URL.'igreja/home/cadastrar','Adicionar igreja');
    
        echo $template->actions_buttons($btnAdiconar);
    ?>
    <div class="middle-content">
        <?php
        $thead = '  <tr>   
                        <th width="160">Nome</th>
                        <th width="120">Endereço</th>
                        <th width="100">Sede/Congregação</th>
                        <th width="100">Pastor</th>
                        <th width="100">CNPJ</th>
                        <th width="100">Status</th>
                        <th width="100">Ações</th>
                    </tr>';
        $tfoot = '  <tr>
                        <th>Nome</th>
                        <th>Endereço</th>
                        <th>Sede/Congregação</th>
                        <th>Pastor</th>
                        <th>CNPJ</th>
                        <th>Status</th>
                        <th>Ações</th>
                    </tr>';	 
        if($igrejas != false):
            $tbody = '';
            foreach ($igrejas as $igreja):
            	$status = ($igreja['status_igreja'] == 'Ativo') ? true : false;
               

                $tbody .='  <tr id="'.$igreja['id_igreja'].'">
                                <td>'.$igreja['nome_igreja'].'</td>
                                
                                <td>'.$igreja['rua_igreja'].' nº'.$igreja['numero_igreja'].' - '.$igreja['bairro_igreja'].' - '.$igreja['cidade_igreja'].' - '.$igreja['estado_igreja'].'</td>
                                <td>'.$igreja['tipo_igreja'].'</td>
                                <td>'.$igreja['pastor'].'</td>
                                <td>'.$igreja['cnpj'].'</td>

                                <td>
                                    '.$template->checkboxStatus($igreja['id_igreja'],'status',$status).'
                                </td>
                                <td>
                                    '.$template->btnEditarRegistro(URL.'igreja/home/editar/'.$igreja['id_igreja']).
                                    $template->btnExcluirRegistro('javascript:void(0)',$igreja['id_igreja']).
                                '</td>
                            </tr>';
                

            endforeach;
            echo $template->tabela($thead, $tfoot, $tbody);
        else:
            echo '<h2>Não há registros cadastrados</h2>';
        endif;
        ?>
    </div>

</div>
<script>
$(document).ready(function() {
    var table = $('.dataTable').DataTable({
    	order: [1,'asc']
    });
    table.$('.btn_excluir').on('click',function(){
        var id = $(this).attr('id');
        var status = 'Excluído';

        $("#dialogResult").html('Deseja mesmo excluir?');
		$("#dialogResult").dialog({
			autoOpen: true,
			buttons: [
				{
					text: "Ok",
					click: function() {
						$( this ).dialog( "close" );

				    	$.post(url+'igreja/home/atualizarStatus',{id:id,status:status},function(data){
							if(data == true){
								$('tr#'+id).hide();

                                $("#dialogResult").html('Registro enviado para a lixeira');
                                $("#dialogResult").dialog({
                                    autoOpen: true,
                                    buttons: [
                                        {
                                            text: "Ok",
                                            click: function() {
                                                $( this ).dialog( "close" );
                                            }
                                        }
                                    ]
                                });


                            }
						});
					}
				},
				{
					text: "Cancelar",
					click: function() {
						$( this ).dialog( "close" );
					}
				}
			]
		});



		
        
    });

    table.$('input[name=status]').on('change',function(){
    	var id = $(this).attr('id')
    	var status = 'Inativo';
		if($(this).is(':checked'))
			status = 'Ativo';

		$.post(url+'igreja/home/atualizarStatus',{id:id,status:status},function(data){
            console.log(data);
		});

    });


});
</script>